### ISSUE TITLE
imaplib.IMAP4.error: Unknown IMAP4 UID command: MOVE

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-functions-core-tools#1048]
I am receiving the following error in my python function app deployed in azure. This error does not exist in local 3.6 environment running in VS Code.
An Error occuredTraceback (most recent call last):
  File "/home/site/wwwroot/SharedCode/EmailReader.py", line 27, in moveMessage
    result = M.uid('MOVE', msg_uid, '/Processed')
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/imaplib.py", line 867, in uid
    raise self.error("Unknown IMAP4 UID command: %s" % command)
imaplib.IMAP4.error: Unknown IMAP4 UID command: MOVE

This is a valid command in python as can be seen here:
https://bugs.python.org/issue33336
for all versions of python.
Seems like something is out of date in the azure environment.
How to resolve the issue in the deployed function app?

**Comment by ahmelsayed** [comment]
can you share a code snippet that reproduces the issue?

**Comment by docgregt** [comment]
M = imaplib.IMAP4_SSL …

    resp, data = M.fetch(msgid, "(UID)")
    try:
        msg_uid = parse_uid(data[0].decode())
        result = M.uid('MOVE', msg_uid, '/Processed')
    except:
        e = traceback.format_exc()
        logging.info("Unable to move email message for id(" + str(msg_uid) + "):" + e)

Code works fine in local dev environment with Python 3.6
Gregory Turner
Chief Architect
________________________________________
i4 Insight, Inc.

cell: +1.720.335.1744
greg.turner@i4-insight.com<mailto:greg.turner@i4-insight.com>

A member of the Lloyd’s Register Group

**Comment by docgregt** [comment]
HI, Any ideas or more questions on this?
