### ISSUE TITLE
func azure functionapp publish with --build-native-deps

### ISSUE THREAD

**Issue by sandorbihary** [Azure/azure-functions-core-tools#1058]
Hi All!
I am tryting to publish a python function but I got an error message.
I used this command: 
` func azure functionapp publish sanyifunction  --build-native-deps`

Environment is Centos7 and Python 3.6.7

This is the error message:

```
Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker exec -t 088384 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp /tmp/15pjtmni.l2t/. 088384:/home/site/wwwroot'..done
Running 'docker kill 088384'..done

Error running docker cp /tmp/15pjtmni.l2t/. 08838429b9ba5e734c977c03f3008ff86b6616f7f66c68063d3bafd3fc63a6dc:/home/site/wwwroot.
output:
Error: No such container:path: 08838429b9ba5e734c977c03f3008ff86b6616f7f66c68063d3bafd3fc63a6dc:/home/site
```

This is the requirements.txt

```
cat requirements.txt
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b3
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.12.0
azure
azure-mgmt-resource
azure-datalake-store
azure-mgmt-datalake-store
azure-mgmt-datalake-analytics
```

The code is running locally. Also I have to use the --build-native-deps otherwise I get this error message:

`There was an error restoring dependencies.ERROR: cannot install cryptography-2.5 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish`

Can it be a bug? Or maybe I am doing something wrong?

**Comment by ankitkumarr** [comment]
@sandorbihary, I think you'd have to use the `--build-native-deps`, so that' fine that you are seeing the error asking you to use a Docker container.

The error message while using the Docker container is interesting. The error says "no such path" for `/home/site` although the previous command should have taken care of it.

Could you restart you docker daemon and try again?

**Comment by sandorbihary** [comment]
Hi @ankitkumarr,

I have restarted the deamon, but I got the same error message. I have even restarted the OS.
After the restart, the first error message was different, though. 

```
# systemctl restart docker
Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12285'....done
Running 'docker exec -t cafc14 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp /tmp/jwrctfvz.blo/. cafc14:/home/site/wwwroot'..done
Running 'docker cp /tmp/tmphDh3Dz.tmp cafc14:python_docker_build.sh'..done
Running 'docker cp /tmp/tmpB0kgqX.tmp cafc14:python_bundle_script.py'..done
Running 'docker exec -t cafc14 chmod +x /python_docker_build.sh'..done
Running 'docker kill cafc14'..done
Error running docker exec -t cafc14053a29d11c91ad0c2b9fb1c259765666451f9fd4eb8a02018d5b978803 chmod +x /python_docker_build.sh.
output:

Error: No such container: cafc14053a29d11c91ad0c2b9fb1c259765666451f9fd4eb8a02018d5b978803


[root@devvm MyFunctionProj]# func azure functionapp publish sanyifunction  --build-native-deps
Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12285'..done
Running 'docker exec -t 899933 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp /tmp/1apjuguy.vkj/. 899933:/home/site/wwwroot'..done
Running 'docker kill 899933'..done
Error running docker cp /tmp/1apjuguy.vkj/. 8999336e47cdb6968d93892268596b9111150fd6a3400051d27fee37ba21a85b:/home/site/wwwroot.
output:

Error: No such container:path: 8999336e47cdb6968d93892268596b9111150fd6a3400051d27fee37ba21a85b:/home/site


[root@devvm MyFunctionProj]#

```

**Comment by ahmelsayed** [comment]
@sandorbihary can you run with `CLI_DEBUG=1 func azure functionapp publish sanyifunction  --build-native-deps` and share the output? 

**WARNING** You may wanna delete some of the ARM request response stuff since they may contain some secrets, or just share the output starting from `Running 'docker pull...`

**Comment by ahmelsayed** [comment]
Also @ankitkumarr this is another example of not needing docker to perform the build since they are already running on a linux system. I'd expect local venv to work in our image since both are linux.

**Comment by sandorbihary** [comment]
Hi @ahmelsayed 
Sure, I copied the output below. 

```
Getting site publishing info...
> docker ps
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12285'.> docker pull mcr.microsoft.com/azure-functions/python:2.0.12285
.done
Output: 2.0.12285: Pulling from azure-functions/python
Digest: sha256:7b074a529c6e7b9802f05ec67d14857b8eb258fdc24717d0bee3383f148c9f1c
Status: Image is up to date for mcr.microsoft.com/azure-functions/python:2.0.12285


Error:

Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12285'.> docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12285
.done
Output: 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705


Error:

Running 'docker exec -t 7618a8 mkdir -p /home/site/wwwroot/'.> docker exec -t 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705 mkdir -p /home/site/wwwroot/
.done
Output:

Error:

Running 'docker cp /tmp/iav2nibl.mni/. 7618a8:/home/site/wwwroot'.> docker cp /tmp/iav2nibl.mni/. 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705:/home/site/wwwroot
.done
Running 'docker kill 7618a8'.> docker kill 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705
.done
Output:

Error: Error response from daemon: Cannot kill container: 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705: No such container: 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705


Azure.Functions.Cli.Common.CliException: Error running docker cp /tmp/iav2nibl.mni/. 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705:/home/site/wwwroot.
output:

Error: No such container:path: 7618a87498206ae16406cf61d0f9f0fb8cf239815f2a6fb237d3e33ee9f64705:/home/site


   at Azure.Functions.Cli.Helpers.DockerHelpers.InternalRunDockerCommand(String args, Boolean ignoreError)
   at Azure.Functions.Cli.Helpers.DockerHelpers.RunDockerCommand(String args, String containerId, Boolean ignoreError) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\DockerHelpers.cs:line 76
   at Azure.Functions.Cli.Helpers.PythonHelpers.InternalPreparePythonDeploymentInDocker(IEnumerable`1 files, String functionAppRoot, String additionalPackages, Boolean noBundler) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\PythonHelpers.cs:line 217
   at Azure.Functions.Cli.Helpers.PythonHelpers.InternalPreparePythonDeploymentInDocker(IEnumerable`1 files, String functionAppRoot, String additionalPackages, Boolean noBundler) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\PythonHelpers.cs:line 252
   at Azure.Functions.Cli.Helpers.PythonHelpers.GetPythonDeploymentPackage(IEnumerable`1 files, String functionAppRoot, Boolean buildNativeDeps, Boolean noBundler, String additionalPackages) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\PythonHelpers.cs:line 154
   at Azure.Functions.Cli.Helpers.ZipHelper.GetAppZipFile(WorkerRuntime workerRuntime, String functionAppRoot, Boolean buildNativeDeps, Boolean noBundler, GitIgnoreParser ignoreParser, String additionalPackages, Boolean ignoreDotNetCheck) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\ZipHelper.cs:line 23
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 289
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 160
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
```

**Comment by ankitkumarr** [comment]
@ahmelsayed, from https://github.com/Azure/azure-functions-core-tools/issues/1030, it seemed like we should use docker even if we are on Linux?

**Comment by ahmelsayed** [comment]
hmmm, I think the container is failing to start, but we're not capturing all the logs correctly. What do you get if you just run 

```
docker run --rm -it mcr.microsoft.com/azure-functions/python:2.0.12285
```

**Comment by sandorbihary** [comment]
Yes, you are right. The container startup fails:

```
docker run --rm -it mcr.microsoft.com/azure-functions/python:2.0.12285

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied. ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.Program.BuildWebHost(String[] args) in /azure-functions-host-9b7c0fa24b604a9c840415247a97944967c78300/src/WebJobs.Script.WebHost/Program.cs:line 37
   at Microsoft.Azure.WebJobs.Script.WebHost.Program.Main(String[] args) in /azure-functions-host-9b7c0fa24b604a9c840415247a97944967c78300/src/WebJobs.Script.WebHost/Program.cs:line 22

```
