### ISSUE TITLE
Cannot access a disposed object. Object name: 'IServiceProvider' on Linux

### ISSUE THREAD

**Issue by matedu** [Azure/azure-functions-core-tools#1062]
I'm experiencing troubles with running locally JavaScript template, generated by VS Code 1.31.1 with Azure Functions 0.40 extension.

```
func host start 

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.4.317 Commit hash: 63e1996b6c281079427e7c9b8a0a1c633988a195)
Function Runtime Version: 2.0.12285.0
Cannot access a disposed object.
Object name: 'IServiceProvider'.
Application is shutting down...
```

```
$ dotnet --version
2.2.104
$ func --version
2.4.317
```

I've tried to change port as said in #907 but nothing changes.

**Comment by ahmelsayed** [comment]
is this a consistent issue for you? The error is coming from the framework, so I'm not sure if setting `CLI_DEBUG=1` would print more logs, but you can give it a try and see if some more logs get printed, that would be useful.

**Comment by matedu** [comment]
Yes, it's consistent, it's fresh install, and error occurs since very first run attempt.

Indeed, there is more information, when `CLI_DEBUG=1`:
```
$ export CLI_DEBUG=1
$ func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.4.317 Commit hash: 63e1996b6c281079427e7c9b8a0a1c633988a195)
Function Runtime Version: 2.0.12285.0
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 224
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
Application is shutting down...
```

**Comment by ahmelsayed** [comment]
@fabiocav is there a way we can get more info about why that exception is being thrown from I`WebHost.RunAsync()`?

Last time we saw it it was due to port in use, though back then the exception was also just as generic. This time it doesn't seem to be a port issue, so I'm not sure what it could be.

**Comment by skitching-um** [comment]
I'm experiencing exactly the same issue. Am running azure-functions-cli (no runtime build) in a docker container.

# /path/to/dotnet /path/to/func.dll host start -p 8899

Azure Functions Core Tools (2.4.419 Commit hash: c9c1724d002bd90b2e6b41393915ea3a26bcf0ce)
Function Runtime Version: 2.0.12332.0
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 224
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54

and FYI:
# /path/to/dotnet --version
2.2.105

**Comment by matedu** [comment]
After updating to 2.4.419 works well.

**Comment by mohsinonxrm** [comment]
Getting same on Raspberry Pi 4B using azure function core tools built on Raspberry Pi 4B itself.
`
pi@raspberrypi:~/queueazfunc/queuetrigger/queuetrigger $ func start --no-build

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1 Commit hash: N/A)
Function Runtime Version: 2.0.12763.0
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in /home/pi/azure-functions-core-tools/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs:line 247
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in /home/pi/azure-functions-core-tools/src/Azure.Functions.Cli/ConsoleApp.cs:line 64
Application is shutting down...

`

**Comment by ahmelsayed** [comment]
Please open a separate issue.
