### ISSUE TITLE
Unable to connect to azure function locally - connect error for worker

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [Azure/azure-functions-core-tools#1121]
Hello,

I have created a simple v2 nodejs function and got the default http trigger. I wanted to run the function locally to test it. I installed azure functions on windows with npm without any issues. However when I try to start it using` func start `then this is the error I get. I tried reinstalling but same error. Does anyone know what could solve this?
![image](https://user-images.githubusercontent.com/6192200/54154109-6b94fd00-4441-11e9-8c3d-77fec425693c.png)

**Comment by imollov** [comment]
I'm having the same issue.

Environment:
- Windows 10
- azure-functions-core-tools@2.7.1480
- node v10.16.0 (also tried with v8.11.1)
- npm 6.9.0

Here's the complete log:

```
> Executing task: func host start <


                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1480 Commit hash: 8c6876cebeeca3dd6a1b895bd0e21acba4af8053)
Function Runtime Version: 2.0.12555.0
Windows Setting AzureWebJobsStorage = 
.NET Setting FUNCTIONS_WORKER_RUNTIME = node
.NET Setting WEBSITE_HOSTNAME = localhost:7071
.NET Setting AzureWebJobsScriptRoot = c:\Users\dir
.NET Setting AZURE_FUNCTIONS_ENVIRONMENT = Development
[7/24/2019 8:32:08 AM] Building host: startup suppressed:False, configuration suppressed: False
[7/24/2019 8:32:10 AM] Initializing Host.
[7/24/2019 8:32:10 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[7/24/2019 8:32:10 AM] LoggerFilterOptions
[7/24/2019 8:32:10 AM] {
[7/24/2019 8:32:10 AM]   "MinLevel": "None",
[7/24/2019 8:32:10 AM]   "Rules": [
[7/24/2019 8:32:10 AM]     {
[7/24/2019 8:32:10 AM]       "ProviderName": null,
[7/24/2019 8:32:10 AM]       "CategoryName": null,
[7/24/2019 8:32:10 AM]       "LogLevel": null,
[7/24/2019 8:32:10 AM]       "Filter": "<AddFilter>b__0"
[7/24/2019 8:32:10 AM]     },
[7/24/2019 8:32:10 AM]     {
[7/24/2019 8:32:10 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[7/24/2019 8:32:10 AM]       "CategoryName": null,
[7/24/2019 8:32:10 AM]       "LogLevel": "None",
[7/24/2019 8:32:10 AM]       "Filter": null
[7/24/2019 8:32:10 AM]     },
[7/24/2019 8:32:10 AM]     {
[7/24/2019 8:32:10 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[7/24/2019 8:32:10 AM]       "CategoryName": null,
[7/24/2019 8:32:10 AM]       "LogLevel": null,
[7/24/2019 8:32:10 AM]       "Filter": "<AddFilter>b__0"
[7/24/2019 8:32:10 AM]     }
[7/24/2019 8:32:10 AM]   ]
[7/24/2019 8:32:10 AM] }
[7/24/2019 8:32:10 AM] FunctionResultAggregatorOptions
[7/24/2019 8:32:10 AM] {
[7/24/2019 8:32:10 AM]   "BatchSize": 1000,
[7/24/2019 8:32:10 AM]   "FlushTimeout": "00:00:30",
[7/24/2019 8:32:10 AM]   "IsEnabled": true
[7/24/2019 8:32:10 AM] }
[7/24/2019 8:32:10 AM] SingletonOptions
[7/24/2019 8:32:10 AM] {
[7/24/2019 8:32:10 AM]   "LockPeriod": "00:00:15",
[7/24/2019 8:32:10 AM]   "ListenerLockPeriod": "00:00:15",
[7/24/2019 8:32:10 AM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[7/24/2019 8:32:10 AM]   "LockAcquisitionPollingInterval": "00:00:05",
[7/24/2019 8:32:10 AM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[7/24/2019 8:32:10 AM] }
[7/24/2019 8:32:10 AM] Starting JobHost
[7/24/2019 8:32:10 AM] Starting Host (HostId=jocu1k4y03-1900319153, InstanceId=f4543cdf-8bbb-479d-b821-1fdc31e2adc4, Version=2.0.12555.0, ProcessId=17960, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[7/24/2019 8:32:10 AM] Loading functions metadata
[7/24/2019 8:32:10 AM] 1 functions loaded
[7/24/2019 8:32:10 AM] Loading proxies metadata
[7/24/2019 8:32:10 AM] Initializing Azure Function proxies
[7/24/2019 8:32:11 AM] 0 proxies loaded
[7/24/2019 8:32:11 AM] Starting language worker process:node  --inspect=9229 "C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 56633 --workerId b1b051ce-2e13-462b-983b-52dac09ac390 --requestId 7c969c27-725f-4e1e-9d33-c92b465040ca --grpcMaxMessageLength 134217728
[7/24/2019 8:32:11 AM] node process with Id=10388 started
[7/24/2019 8:32:11 AM] Generating 1 job function(s)
[7/24/2019 8:32:11 AM] Found the following functions:
[7/24/2019 8:32:11 AM] Host.Functions.AddErrorLog
[7/24/2019 8:32:11 AM]
[7/24/2019 8:32:11 AM] Host initialized (1238ms)
[7/24/2019 8:32:11 AM] Host started (1251ms)
[7/24/2019 8:32:11 AM] Job host started
[7/24/2019 8:32:11 AM] Debugger listening on ws://127.0.0.1:9229/95788ba6-7156-4302-86e5-b64e4c5fd738
[7/24/2019 8:32:11 AM] For help, see: https://nodejs.org/en/docs/inspector
Hosting environment: Production
Content root path: c:\Users\dir
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        AddErrorLog: [POST] http://localhost:7071/api/func

[7/24/2019 8:32:12 AM] Worker b1b051ce-2e13-462b-983b-52dac09ac390 connecting on 127.0.0.1:56633
[7/24/2019 8:32:12 AM] [error] Worker b1b051ce-2e13-462b-983b-52dac09ac390 encountered event stream error:  { Error: 14 UNAVAILABLE: Connect Failed
[7/24/2019 8:32:12 AM] Worker b1b051ce-2e13-462b-983b-52dac09ac390 exited with code 1
[7/24/2019 8:32:12 AM] [error] Worker b1b051ce-2e13-462b-983b-52dac09ac390 uncaught exception: Error: 14 UNAVAILABLE: Connect Failed Error: 14 UNAVAILABLE: Connect Failed
[7/24/2019 8:32:12 AM]     at Object.module.exports.exports.createStatusError (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[7/24/2019 8:32:12 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7313:26)
[7/24/2019 8:32:12 AM]     at ClientDuplexStream._receiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7291:8)
[7/24/2019 8:32:12 AM]     at Object.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20234:15)
[7/24/2019 8:32:12 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19496:42)
[7/24/2019 8:32:12 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19546:8)
[7/24/2019 8:32:12 AM]     at C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20051:18
[7/24/2019 8:32:12 AM]   code: 14,
[7/24/2019 8:32:12 AM]   metadata: Metadata { _internal_repr: {} },
[7/24/2019 8:32:12 AM]   details: 'Connect Failed' }
[7/24/2019 8:32:12 AM]     at Object.module.exports.exports.createStatusError (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[7/24/2019 8:32:12 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7313:26)
[7/24/2019 8:32:12 AM]     at ClientDuplexStream._receiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7291:8)
[7/24/2019 8:32:12 AM]     at Object.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20234:15)
[7/24/2019 8:32:12 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19496:42)
[7/24/2019 8:32:12 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19546:8)
[7/24/2019 8:32:12 AM]     at C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20051:18
[7/24/2019 8:32:12 AM] Starting language worker process:node  --inspect=9229 "C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 56633 --workerId a4073be8-ea2e-4c5b-adc5-ce5c6023eb92 --requestId 43a5e7d3-e2c6-4f20-9388-cda7a2b6d323 --grpcMaxMessageLength 134217728
[7/24/2019 8:32:12 AM] node process with Id=19348 started
[7/24/2019 8:32:12 AM] Debugger listening on ws://127.0.0.1:9229/cc3a514a-4dd4-4466-90cd-bc194d508063
[7/24/2019 8:32:12 AM] For help, see: https://nodejs.org/en/docs/inspector
[7/24/2019 8:32:12 AM] Worker a4073be8-ea2e-4c5b-adc5-ce5c6023eb92 connecting on 127.0.0.1:56633
[7/24/2019 8:32:13 AM] [error] Worker a4073be8-ea2e-4c5b-adc5-ce5c6023eb92 encountered event stream error:  { Error: 14 UNAVAILABLE: Connect Failed
[7/24/2019 8:32:13 AM] Worker a4073be8-ea2e-4c5b-adc5-ce5c6023eb92 exited with code 1
[7/24/2019 8:32:13 AM] [error] Worker a4073be8-ea2e-4c5b-adc5-ce5c6023eb92 uncaught exception: Error: 14 UNAVAILABLE: Connect Failed Error: 14 UNAVAILABLE: Connect Failed
[7/24/2019 8:32:13 AM]     at Object.module.exports.exports.createStatusError (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7313:26)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._receiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7291:8)
[7/24/2019 8:32:13 AM]     at Object.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20234:15)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19496:42)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19546:8)
[7/24/2019 8:32:13 AM]     at C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20051:18
[7/24/2019 8:32:13 AM]   code: 14,
[7/24/2019 8:32:13 AM]   metadata: Metadata { _internal_repr: {} },
[7/24/2019 8:32:13 AM]   details: 'Connect Failed' }
[7/24/2019 8:32:13 AM]     at Object.module.exports.exports.createStatusError (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7313:26)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._receiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7291:8)
[7/24/2019 8:32:13 AM]     at Object.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20234:15)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19496:42)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19546:8)
[7/24/2019 8:32:13 AM]     at C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20051:18
[7/24/2019 8:32:13 AM] Starting language worker process:node  --inspect=9229 "C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 56633 --workerId 9f0a9a1a-4e68-4460-b55b-f231b5ca455c --requestId 0a41f48d-b357-4f09-85c9-62c1d330922b --grpcMaxMessageLength 134217728
[7/24/2019 8:32:13 AM] node process with Id=15860 started
[7/24/2019 8:32:13 AM] Debugger listening on ws://127.0.0.1:9229/dd38e412-a2b2-4992-8d59-a18da9e9318e
[7/24/2019 8:32:13 AM] For help, see: https://nodejs.org/en/docs/inspector
[7/24/2019 8:32:13 AM] Worker 9f0a9a1a-4e68-4460-b55b-f231b5ca455c connecting on 127.0.0.1:56633
[7/24/2019 8:32:13 AM] [error] Worker 9f0a9a1a-4e68-4460-b55b-f231b5ca455c encountered event stream error:  { Error: 14 UNAVAILABLE: Connect Failed
[7/24/2019 8:32:13 AM] Worker 9f0a9a1a-4e68-4460-b55b-f231b5ca455c exited with code 1
[7/24/2019 8:32:13 AM]     at Object.module.exports.exports.createStatusError (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[7/24/2019 8:32:13 AM] [error] Worker 9f0a9a1a-4e68-4460-b55b-f231b5ca455c uncaught exception: Error: 14 UNAVAILABLE: Connect Failed Error: 14 UNAVAILABLE: Connect Failed
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7313:26)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._receiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7291:8)
[7/24/2019 8:32:13 AM]     at Object.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20234:15)
[7/24/2019 8:32:13 AM] Exceeded language worker restart retry count for runtime:node. Shutting down Functions Host
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19496:42)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19546:8)
[7/24/2019 8:32:13 AM]     at C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20051:18
[7/24/2019 8:32:13 AM]   code: 14,
[7/24/2019 8:32:13 AM]   metadata: Metadata { _internal_repr: {} },
[7/24/2019 8:32:13 AM]   details: 'Connect Failed' }
[7/24/2019 8:32:13 AM]     at Object.module.exports.exports.createStatusError (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7313:26)
[7/24/2019 8:32:13 AM]     at ClientDuplexStream._receiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7291:8)
[7/24/2019 8:32:13 AM]     at Object.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20234:15)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19496:42)
[7/24/2019 8:32:13 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:19546:8)
[7/24/2019 8:32:13 AM]     at C:\Users\mollov\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:20051:18
[7/24/2019 8:32:13 AM] Stopping host...
[7/24/2019 8:32:13 AM] Stopping JobHost
[7/24/2019 8:32:13 AM] Job host stopped
[7/24/2019 8:32:13 AM] Host shutdown completed.
Application is shutting down...

Terminal will be reused by tasks, press any key to close it.
```

As a side note, someone reported a similar case on stackoverflow: https://stackoverflow.com/questions/55264418/hello-world-application-for-azure-functions-with-typescript-fails-to-start-with

It's true I'm behind a corporate proxy and firewall but I have the http_proxy settings already done, as the solution suggests.

**Comment by ahmedelnably** [comment]
Closing as stale, please upgrade to the new version and open a new issue if the error persists
