### ISSUE TITLE
func command failing due to unhandled error

### ISSUE THREAD

**Issue by t-eckert** [Azure/azure-functions-core-tools#1136]
When I run the `func` command with any function app, I get the error:

``` 
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\v-thecke\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin/func ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:19)
    at onErrorNT (internal/child_process.js:413:16)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:244:12)
    at onErrorNT (internal/child_process.js:413:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```

## Steps Taken

1. Rebooted machine
2. Deleted the npm module and reinstalled the latest version using `npm`

## Machine Details

Windows 10 Enterprise 1809

## Repro

I am not sure exactly what steps led to this occurring. Currently, it happens regardless of which function app I run the command against.  
This error does not occur when I run the function app using Visual Studio, only in the CLI.  
This morning, I did install a Microsoft internal tool using Chocolaty. It may be the source of the issue, but probably best talked about on a private channel.  

## Contact

For private details, I can be contacted via teams as theckert

**Comment by t-eckert** [comment]
Closing. The issue resolved itself, but I have no idea why.
