### ISSUE TITLE
Error calling sync triggers (BadRequest). Python runtime on Linux

### ISSUE THREAD

**Issue by wasuaje** [Azure/azure-functions-core-tools#1181]
#1130 
I've been having this error since a while, i commented in previous issue, but was closed without a solution, I'm deploying same function app in another regionw 
Working in US East

NOT Working West Europe

the error:
```
2019-04-05T22:44:20.5461684Z ##[section]Starting: Bash Script
2019-04-05T22:44:20.5465640Z ==============================================================================
2019-04-05T22:44:20.5465692Z Task         : Bash
2019-04-05T22:44:20.5465724Z Description  : Run a Bash script on macOS, Linux, or Windows
2019-04-05T22:44:20.5465796Z Version      : 3.148.2
2019-04-05T22:44:20.5465827Z Author       : Microsoft Corporation
2019-04-05T22:44:20.5465861Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
2019-04-05T22:44:20.5465933Z ==============================================================================
2019-04-05T22:44:21.3653171Z Generating script.
2019-04-05T22:44:21.3656730Z Formatted command: . '/home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/ReleaseFunctionApps.sh' --AZURE_RM_CLIENTID "0d0d30ab-a5fd-4a60-90e1-07e50a483d10" --AZURE_RM_SECRET "***" --AZURE_RM_TENANTID "5b973f99-77df-4beb-b27d-aa0c70b8482c" --AZURE_RM_SUBID "5aeb8557-cab7-41ac-8603-9f94ad233efc" --SOFTWARE_SAS "***" --CurDir "/home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/"
2019-04-05T22:44:21.3657810Z ========================== Starting Command Output ===========================
2019-04-05T22:44:21.3660582Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/7f504aa6-8e74-47cd-8300-e43896edd0dd.sh
2019-04-05T22:44:21.3660862Z deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ xenial main
2019-04-05T22:44:21.3660918Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-04-05T22:44:21.3661010Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-04-05T22:44:21.3661042Z 
2019-04-05T22:44:21.3661286Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2019-04-05T22:44:21.3661538Z 100   983  100   983    0     0   6091      0 --:--:-- --:--:-- --:--:--  6105
2019-04-05T22:44:22.2956743Z OK
2019-04-05T22:44:34.3242499Z Reading package lists...
2019-04-05T22:44:34.5080207Z Building dependency tree...
2019-04-05T22:44:34.5321388Z Reading state information...
2019-04-05T22:44:34.6803603Z apt-transport-https is already the newest version (1.2.29ubuntu0.1).
2019-04-05T22:44:34.6804490Z 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
2019-04-05T22:44:34.6810539Z install Azure CLI...
2019-04-05T22:44:34.8733332Z Get:1 http://ppa.launchpad.net/apt-fast/stable/ubuntu xenial InRelease [17.5 kB]
2019-04-05T22:44:34.9287466Z Hit:2 http://azure.archive.ubuntu.com/ubuntu xenial InRelease
2019-04-05T22:44:34.9289143Z Get:3 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
2019-04-05T22:44:34.9289741Z Get:4 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease [23.8 kB]
2019-04-05T22:44:34.9328986Z Hit:5 http://ppa.launchpad.net/mercurial-ppa/releases/ubuntu xenial InRelease
2019-04-05T22:44:34.9368673Z Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease
2019-04-05T22:44:34.9498397Z Get:7 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
2019-04-05T22:44:34.9532693Z Get:8 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease [23.9 kB]
2019-04-05T22:44:34.9822349Z Hit:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial InRelease
2019-04-05T22:44:35.0012056Z Get:10 https://dl.yarnpkg.com/debian stable InRelease [13.3 kB]
2019-04-05T22:44:35.0027301Z Get:11 https://cli-assets.heroku.com/apt ./ InRelease [2,533 B]
2019-04-05T22:44:35.0096136Z Get:12 http://dl.google.com/linux/chrome/deb stable Release [943 B]
2019-04-05T22:44:35.0226678Z Get:13 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
2019-04-05T22:44:35.0335855Z Get:14 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
2019-04-05T22:44:35.0734363Z Get:15 https://packages.microsoft.com/repos/azure-cli xenial InRelease [3,188 B]
2019-04-05T22:44:35.0916737Z Get:17 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease [3,225 B]
2019-04-05T22:44:35.1056370Z Get:18 https://download.mono-project.com/repo/ubuntu stable-xenial InRelease [5,143 B]
2019-04-05T22:44:35.1989178Z Get:19 http://ppa.launchpad.net/apt-fast/stable/ubuntu xenial/main amd64 Packages [492 B]
2019-04-05T22:44:35.3985795Z Get:16 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8,993 B]
2019-04-05T22:44:35.4587555Z Get:20 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main Sources [333 kB]
2019-04-05T22:44:35.4924456Z Get:21 http://azure.archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2,536 B]
2019-04-05T22:44:35.5054118Z Get:22 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [254 kB]
2019-04-05T22:44:35.5179210Z Get:23 http://azure.archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8,764 B]
2019-04-05T22:44:35.5297393Z Get:24 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [936 kB]
2019-04-05T22:44:35.5536572Z Get:25 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [376 kB]
2019-04-05T22:44:35.5677242Z Get:26 http://azure.archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [7,616 B]
2019-04-05T22:44:35.5781456Z Get:27 http://azure.archive.ubuntu.com/ubuntu xenial-updates/restricted Translation-en [2,272 B]
2019-04-05T22:44:35.5890385Z Get:28 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [745 kB]
2019-04-05T22:44:35.6125872Z Get:29 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [309 kB]
2019-04-05T22:44:35.6225518Z Get:30 http://azure.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.7 kB]
2019-04-05T22:44:35.6229415Z Get:31 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages [52.6 kB]
2019-04-05T22:44:35.6631785Z Get:32 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main Translation-en [29.0 kB]
2019-04-05T22:44:35.7369560Z Get:33 https://dl.yarnpkg.com/debian stable/main amd64 Packages [8,545 B]
2019-04-05T22:44:35.7456106Z Get:34 https://dl.yarnpkg.com/debian stable/main all Packages [8,545 B]
2019-04-05T22:44:35.8467622Z Get:35 https://cli-assets.heroku.com/apt ./ Packages [616 B]
2019-04-05T22:44:35.9256069Z Get:36 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,114 B]
2019-04-05T22:44:35.9731995Z Get:37 https://packages.microsoft.com/repos/azure-cli xenial/main amd64 Packages [5,765 B]
2019-04-05T22:44:36.0429582Z Get:38 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [75.0 kB]
2019-04-05T22:44:36.0880146Z Get:39 https://download.mono-project.com/repo/ubuntu stable-xenial/main amd64 Packages [49.6 kB]
2019-04-05T22:44:36.2301309Z Get:40 http://security.ubuntu.com/ubuntu xenial-security/main Sources [145 kB]
2019-04-05T22:44:36.3311736Z Get:41 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages [25.0 kB]
2019-04-05T22:44:36.4110969Z Get:42 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [104 kB]
2019-04-05T22:44:36.4813397Z Hit:43 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
2019-04-05T22:44:36.5195883Z Get:44 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [3,416 B]
2019-04-05T22:44:36.6045695Z Get:45 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [637 kB]
2019-04-05T22:44:36.8536067Z Get:46 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [261 kB]
2019-04-05T22:44:36.9577248Z Get:47 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [433 kB]
2019-04-05T22:44:37.0762144Z Get:48 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [175 kB]
2019-04-05T22:44:37.1744438Z Get:49 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [5,604 B]
2019-04-05T22:44:42.7756566Z Fetched 5,440 kB in 2s (2,334 kB/s)
2019-04-05T22:44:43.6699338Z Reading package lists...
2019-04-05T22:44:43.7312250Z Reading package lists...
2019-04-05T22:44:43.8660339Z Building dependency tree...
2019-04-05T22:44:43.8673368Z Reading state information...
2019-04-05T22:44:43.9779290Z The following packages will be upgraded:
2019-04-05T22:44:43.9781206Z   azure-cli
2019-04-05T22:44:44.1941519Z 1 upgraded, 0 newly installed, 0 to remove and 430 not upgraded.
2019-04-05T22:44:44.1941637Z Need to get 45.3 MB of archives.
2019-04-05T22:44:44.1942238Z After this operation, 3,684 kB disk space will be freed.
2019-04-05T22:44:44.1943073Z Get:1 https://packages.microsoft.com/repos/azure-cli xenial/main amd64 azure-cli all 2.0.61-1~xenial [45.3 MB]
2019-04-05T22:44:45.8946825Z debconf: unable to initialize frontend: Dialog
2019-04-05T22:44:45.8947600Z debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
2019-04-05T22:44:45.8947843Z debconf: falling back to frontend: Readline
2019-04-05T22:44:45.9449953Z debconf: unable to initialize frontend: Readline
2019-04-05T22:44:45.9450381Z debconf: (This frontend requires a controlling tty.)
2019-04-05T22:44:45.9450642Z debconf: falling back to frontend: Teletype
2019-04-05T22:44:45.9485665Z dpkg-preconfigure: unable to re-open stdin: 
2019-04-05T22:44:46.0052127Z Fetched 45.3 MB in 1s (34.3 MB/s)
2019-04-05T22:44:47.3725915Z (Reading database ... 
2019-04-05T22:44:47.3726469Z (Reading database ... 5%
2019-04-05T22:44:47.3726579Z (Reading database ... 10%
2019-04-05T22:44:47.3726743Z (Reading database ... 15%
2019-04-05T22:44:47.3726848Z (Reading database ... 20%
2019-04-05T22:44:47.3726890Z (Reading database ... 25%
2019-04-05T22:44:47.3726977Z (Reading database ... 30%
2019-04-05T22:44:47.3727019Z (Reading database ... 35%
2019-04-05T22:44:47.3727060Z (Reading database ... 40%
2019-04-05T22:44:47.3727146Z (Reading database ... 45%
2019-04-05T22:44:47.3727187Z (Reading database ... 50%
2019-04-05T22:44:48.0668878Z (Reading database ... 55%
2019-04-05T22:44:49.5912795Z (Reading database ... 60%
2019-04-05T22:44:51.2156462Z (Reading database ... 65%
2019-04-05T22:44:52.2751923Z (Reading database ... 70%
2019-04-05T22:44:55.4560600Z (Reading database ... 75%
2019-04-05T22:44:57.4111747Z (Reading database ... 80%
2019-04-05T22:44:59.1752478Z (Reading database ... 85%
2019-04-05T22:45:02.2637321Z (Reading database ... 90%
2019-04-05T22:45:05.6018839Z (Reading database ... 95%
2019-04-05T22:45:05.6019758Z (Reading database ... 100%
2019-04-05T22:45:05.6019991Z (Reading database ... 244960 files and directories currently installed.)
2019-04-05T22:45:05.6184567Z Preparing to unpack .../azure-cli_2.0.61-1~xenial_all.deb ...
2019-04-05T22:45:07.1985576Z Unpacking azure-cli (2.0.61-1~xenial) over (2.0.59-1~xenial) ...
2019-04-05T22:45:51.2995918Z Setting up azure-cli (2.0.61-1~xenial) ...
2019-04-05T22:45:54.3752673Z /opt/hostedtoolcache/node/8.15.1/x64/bin/func -> /opt/hostedtoolcache/node/8.15.1/x64/lib/node_modules/azure-functions-core-tools/lib/main.js
2019-04-05T22:45:54.3754779Z /opt/hostedtoolcache/node/8.15.1/x64/bin/azfun -> /opt/hostedtoolcache/node/8.15.1/x64/lib/node_modules/azure-functions-core-tools/lib/main.js
2019-04-05T22:45:54.3756066Z /opt/hostedtoolcache/node/8.15.1/x64/bin/azurefunctions -> /opt/hostedtoolcache/node/8.15.1/x64/lib/node_modules/azure-functions-core-tools/lib/main.js
2019-04-05T22:45:54.3978466Z 
2019-04-05T22:45:54.3980777Z > azure-functions-core-tools@2.5.553 postinstall /opt/hostedtoolcache/node/8.15.1/x64/lib/node_modules/azure-functions-core-tools
2019-04-05T22:45:54.3981484Z > node lib/install.js
2019-04-05T22:45:54.3981650Z 
2019-04-05T22:45:54.5741048Z attempting to GET "https://functionscdn.azureedge.net/public/2.5.553/Azure.Functions.Cli.linux-x64.2.5.553.zip"
2019-04-05T22:46:02.3763081Z 
2019-04-05T22:46:02.4775706Z + azure-functions-core-tools@2.5.553
2019-04-05T22:46:02.4776604Z added 52 packages from 32 contributors in 9.577s
2019-04-05T22:46:02.4877647Z installing dotnet core
2019-04-05T22:46:29.7866613Z dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.202/dotnet-sdk-2.1.202-linux-x64.tar.gz
2019-04-05T22:46:32.3476890Z dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.202/dotnet-sdk-2.1.202-linux-x64.tar.gz
2019-04-05T22:46:45.8949031Z dotnet-install: Adding to current process PATH: `/home/vsts/.dotnet`. Note: This change will be visible only when sourcing script.
2019-04-05T22:46:45.8950218Z dotnet-install: Installation finished successfully.
2019-04-05T22:46:45.8951241Z Starting Function Apps install
2019-04-05T22:46:45.8951496Z Loggining In
2019-04-05T22:46:48.1672642Z [
2019-04-05T22:46:48.1681041Z   }
2019-04-05T22:46:48.1681154Z ]
2019-04-05T22:46:49.2162215Z Uplading Json FIle
2019-04-05T22:46:50.6462989Z 
2019-04-05T22:46:50.6463245Z Alive[################################################################]  100.0000%
2019-04-05T22:46:50.6552564Z Finished[#############################################################]  100.0000%
2019-04-05T22:46:50.6552705Z {
2019-04-05T22:46:50.6552737Z   "etag": "\"0x8D6BA1897A2CDBF\"",
2019-04-05T22:46:50.6553334Z   "lastModified": "2019-04-05T22:46:50+00:00"
2019-04-05T22:46:50.6553391Z }
2019-04-05T22:46:50.7190054Z Installing extensions
2019-04-05T22:47:04.3689551Z Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
2019-04-05T22:47:04.3689826Z Copyright (C) Microsoft Corporation. All rights reserved.
2019-04-05T22:47:04.3689956Z 
2019-04-05T22:47:13.4913140Z   Restoring packages for /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/extensions.csproj...
2019-04-05T22:47:19.3497841Z   Installing System.Threading.ThreadPool 4.0.10.
2019-04-05T22:47:19.3976642Z   Installing Microsoft.Win32.Registry 4.0.0.
2019-04-05T22:47:19.3977124Z   Installing System.Runtime.Serialization.Xml 4.1.1.
2019-04-05T22:47:19.3977293Z   Installing System.Diagnostics.Process 4.1.0.
2019-04-05T22:47:19.3977734Z   Installing System.Text.Encoding.CodePages 4.0.1.
2019-04-05T22:47:19.3977916Z   Installing System.Diagnostics.TraceSource 4.0.0.
2019-04-05T22:47:19.3978062Z   Installing System.Collections.NonGeneric 4.0.1.
2019-04-05T22:47:19.3978241Z   Installing System.Resources.Reader 4.0.0.
2019-04-05T22:47:19.3978386Z   Installing System.Threading.Thread 4.0.0.
2019-04-05T22:47:19.3978529Z   Installing Microsoft.Build.Utilities.Core 15.3.409.
2019-04-05T22:47:19.3978694Z   Installing Microsoft.Build.Framework 15.3.409.
2019-04-05T22:47:19.3978840Z   Installing System.Runtime.Loader 4.3.0.
2019-04-05T22:47:19.3978984Z   Installing Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator 1.0.2.
2019-04-05T22:47:37.0090914Z   Generating MSBuild file /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/obj/extensions.csproj.nuget.g.props.
2019-04-05T22:47:37.0101505Z   Generating MSBuild file /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/obj/extensions.csproj.nuget.g.targets.
2019-04-05T22:47:37.0220005Z   Restore completed in 23.64 sec for /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/extensions.csproj.
2019-04-05T22:47:51.1719883Z   extensions -> /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/bin/extensions.dll
2019-04-05T22:47:51.3710200Z 
2019-04-05T22:47:51.3711099Z Build succeeded.
2019-04-05T22:47:51.3711348Z     0 Warning(s)
2019-04-05T22:47:51.3711543Z     0 Error(s)
2019-04-05T22:47:51.3714545Z 
2019-04-05T22:47:51.3714664Z Time Elapsed 00:00:45.84
2019-04-05T22:47:51.3868750Z 
2019-04-05T22:47:51.3880173Z 
2019-04-05T22:47:51.3965579Z Uploading Function Apps
2019-04-05T22:47:55.7059961Z Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
2019-04-05T22:47:55.7067627Z Copyright (C) Microsoft Corporation. All rights reserved.
2019-04-05T22:47:55.7067892Z 
2019-04-05T22:47:56.3856840Z   Restore completed in 37.33 ms for /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/extensions.csproj.
2019-04-05T22:47:56.7170497Z   extensions -> /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/bin/extensions.dll
2019-04-05T22:47:56.8070926Z 
2019-04-05T22:47:56.8071575Z Build succeeded.
2019-04-05T22:47:56.8071829Z     0 Warning(s)
2019-04-05T22:47:56.8071920Z     0 Error(s)
2019-04-05T22:47:56.8072818Z 
2019-04-05T22:47:56.8073049Z Time Elapsed 00:00:01.05
2019-04-05T22:47:56.8218578Z 
2019-04-05T22:47:56.8244436Z 
2019-04-05T22:47:56.8301289Z Getting site publishing info...
2019-04-05T22:48:46.6303499Z Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12309'...........................................done
2019-04-05T22:49:00.9408454Z Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12309'...............done
2019-04-05T22:49:01.6574764Z Running 'docker exec -t 9598b7 mkdir -p /home/site/wwwroot/'..done
2019-04-05T22:49:02.6658608Z Running 'docker cp "/tmp/sq5pghbs.4lw/." 9598b7:"/home/site/wwwroot"'..done
2019-04-05T22:49:03.7133257Z Running 'docker cp "/tmp/tmpKqIJbt.tmp" 9598b7:"python_docker_build.sh"'..done
2019-04-05T22:49:04.7180455Z Running 'docker exec -t 9598b7 chmod +x /python_docker_build.sh'..done
2019-04-05T22:49:27.2338804Z Running 'docker exec -t 9598b7 /python_docker_build.sh'.......................done
2019-04-05T22:49:28.2396599Z Running 'docker cp 9598b7:"/app.zip" "/tmp/pvdnch5w.xfu"'..done
2019-04-05T22:49:35.2509442Z Running 'docker kill 9598b7'........done
2019-04-05T22:49:35.2551024Z Preparing archive...
2019-04-05T22:49:36.4092051Z Uploading 39.21 MB []Upload completed successfully.
2019-04-05T22:49:37.6406070Z Deployment completed successfully.
2019-04-05T22:49:42.6485705Z Syncing triggers...
2019-04-05T22:49:49.3202598Z Syncing triggers...
2019-04-05T22:49:55.0168452Z Syncing triggers...
2019-04-05T22:50:01.7338683Z Syncing triggers...
2019-04-05T22:50:07.9957965Z Syncing triggers...
2019-04-05T22:50:18.1231080Z Syncing triggers...
2019-04-05T22:50:23.4637505Z Error calling sync triggers (BadRequest).
2019-04-05T22:50:27.0974438Z Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
2019-04-05T22:50:27.0975765Z Copyright (C) Microsoft Corporation. All rights reserved.
2019-04-05T22:50:27.0975996Z 
2019-04-05T22:50:27.7541993Z   Restore completed in 32.21 ms for /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/extensions.csproj.
2019-04-05T22:50:28.0853403Z   extensions -> /home/vsts/work/r1/a/Global Tax Platform SRC/TowerWrapAppProj/bin/extensions.dll
2019-04-05T22:50:28.1780279Z 
2019-04-05T22:50:28.1781297Z Build succeeded.
2019-04-05T22:50:28.1782230Z     0 Warning(s)
2019-04-05T22:50:28.1783016Z     0 Error(s)
2019-04-05T22:50:28.1783625Z 
2019-04-05T22:50:28.1784247Z Time Elapsed 00:00:01.04
2019-04-05T22:50:28.1922874Z 
2019-04-05T22:50:28.1937111Z 
2019-04-05T22:50:28.2030675Z Getting site publishing info...
2019-04-05T22:50:29.2752248Z Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12309'..done
2019-04-05T22:50:30.2841043Z Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12309'..done
2019-04-05T22:50:31.2890306Z Running 'docker exec -t 032bc9 mkdir -p /home/site/wwwroot/'..done
2019-04-05T22:50:32.2931676Z Running 'docker cp "/tmp/auo1e2er.plf/." 032bc9:"/home/site/wwwroot"'..done
2019-04-05T22:50:33.3401330Z Running 'docker cp "/tmp/tmpLZiZUC.tmp" 032bc9:"python_docker_build.sh"'..done
2019-04-05T22:50:34.3397701Z Running 'docker exec -t 032bc9 chmod +x /python_docker_build.sh'..done
2019-04-05T22:50:56.6580264Z Running 'docker exec -t 032bc9 /python_docker_build.sh'.......................done
2019-04-05T22:50:57.6415416Z Running 'docker cp 032bc9:"/app.zip" "/tmp/oe20bzwt.i5n"'..done
2019-04-05T22:51:04.6478360Z Running 'docker kill 032bc9'........done
2019-04-05T22:51:04.6520308Z Preparing archive...
2019-04-05T22:51:07.5593859Z Uploading 39.21 MB []Upload completed successfully.
2019-04-05T22:51:08.7140918Z Deployment completed successfully.
2019-04-05T22:51:13.7223252Z Syncing triggers...
2019-04-05T22:51:22.4010608Z Functions in USEDGTP001FAP01:
2019-04-05T22:51:22.4027817Z     Tower - [httpTrigger]
2019-04-05T22:51:23.8176769Z         Invoke url: https://usedgtp001fap01.azurewebsites.net/api/tower?code=N7Z6DPfxl6pZOt8RyTjSdQHuiYq7xRWIYAepJm5GaqmMj//BoLDLbg==
2019-04-05T22:51:23.8177748Z 
2019-04-05T22:51:23.8181767Z     DatabaseUserCreation - [httpTrigger]
2019-04-05T22:51:24.7063031Z         Invoke url: https://usedgtp001fap01.azurewebsites.net/api/databaseusercreation?code=hoS8mfY9fnRdmTD3Ub/v52aAYg7aHaz/HsQHHzQKPhWDGIMQtEx4Jw==
2019-04-05T22:51:24.7063558Z 
2019-04-05T22:51:24.7275990Z ##[section]Finishing: Bash Script

```

**Comment by balag0** [comment]
I see the sitename in the invoke url is from East US. Can you share the sitename from West Europe where this is not working.

**Comment by wasuaje** [comment]
https://uw2dgtp001fap01.azurewebsites.net

**Comment by balag0** [comment]
Thanks. This is the exception I see in the app. Since the same works in East US likely not a appcontent , tools issue.
I am investigating this more but adding the stack trace here in case you have any ideas what might be going on. 
Just to rule out transient issues, could you try publish again to this app and use the East US app as mitigation.

System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message,AsyncProtocolRequest asyncRequest,ExceptionDispatchInfo exception)
    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming,Int32 count,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer,Int32 count,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer,Int32 readBytes,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming,Int32 count,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer,Int32 count,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer,Int32 readBytes,AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Net.Security.SslState.ThrowIfExceptional()
    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
    at System.Net.Security.SslStream.\u003c\u003ec.\u003cAuthenticateAsClientAsync\u003eb__47_1(IAsyncResult iar)
    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,Func`2 endFunction,Action`1 endAction,Task`1 promise,Boolean requiresSynchronization)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream,SslClientAuthenticationOptions sslOptions,CancellationToken cancellationToken)

**Comment by zacktayl** [comment]
Having this issue on EastUS as well - https://github.com/Azure/azure-functions-core-tools/issues/1457

**Comment by michalzaptk** [comment]
Having this issue on East US for the past 3 days

**Comment by balag0** [comment]
@michalzaptk  Please share the sitename if possible.

**Comment by ahmedelnably** [comment]
Closing this as stale, please open a new issue if this is still persistent with the new version of the core tools
