### ISSUE TITLE
Command func new fails with Value cannot be null. Parameter name: path1 error message

### ISSUE THREAD

**Issue by vajkayrene** [Azure/azure-functions-core-tools#1231]
### Problem

Hi, after running `func new` or `func templates list` I get the following error mesage:
```
Value cannot be null.
Parameter name: path1
```
I enabled CLI_DEBUG and received the strack trace below. 

### Versions
Azure Functions Core Tools 2.6.1048
macOS Mojave 10.14.4 (18E226)

### Stack Trace from CLI console
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleContentProvider.GetFileContent(String path) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\ExtensionBundle\ExtensionBundleContentProvider.cs:line 38
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleContentProvider.GetTemplates() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\ExtensionBundle\ExtensionBundleContentProvider.cs:line 23
   at Azure.Functions.Cli.Common.TemplatesManager.GetTemplates() in C:\azure-functions-cli\src\Azure.Functions.Cli\Common\TemplatesManager.cs:line 40
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 76
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
```
### Update 1
I investigated the issue and the problem disappears, when I remove the following lines from host.json:
```
"extensionBundle": {
  "id": "Microsoft.Azure.Functions.ExtensionBundle",
  "version": "[1.*, 2.0.0)"
}
```
### Update 2
I investigated further the issue and I see that the extension bundle isn't downloaded to my machine. The reason seems to be that `ExtensionBundleManager.GetBundle` requires one of the following environment variables WEBSITE_INSTANCE_ID or FUNCTIONS_CORETOOLS_ENVIRONMENT to be set to download. None of the them were set on my machine.

My assumption is that FUNCTIONS_CORETOOLS_ENVIRONMENT should have been set. Although I cannot explain why it wasn't. I suggest to explicitly check for this error condition either in azure-functions-host or in azure-functions-core-tools and show a meaningful error message. 

I executed the following script and it removed the problem: 
```
export FUNCTIONS_CORETOOLS_ENVIRONMENT=1
```

**Comment by soninaren** [comment]
@vajkayrene thanks for a detailed issue and the posted workarounds. Core tools should have set those environment variables for you. I will look into it and fix the issue.

**Comment by soninaren** [comment]
fixed in here  https://github.com/Azure/azure-functions-core-tools/pull/1254
