### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-core-tools#1239]

**Comment by janmechtel** [comment]
I'm really eager to get this. It's so nice to be able to test Functions super fast in the Azure Portal, we need that locally as well!

**Comment by galgrunfeld-madtrix** [comment]
So still no news on this?

**Comment by janmechtel** [comment]
Everyone interested in this should consider switching the language to c# script for development purposes, works like a charm: https://stackoverflow.com/questions/59783914/how-to-speed-up-debugging-c-sharp-azure-function-locally-is

**Comment by galvesribeiro** [comment]
@janmechtel even though it works well on C# scripts, its far from ideal because it goes against other features that we've asking so much for Az Func like pre-compiled projects, ReadyToRun (not available yet) and most importance, Dependency Injection support.

Its almost one year old issue. @ahmedelnably do you have any news on whether this would be supported or not? This would REALLY streamline the support. Right now we have Collectible Assemblies support in .Net Core, so we are able to load and unload assemblies at runtime so that could be supported even if you are not using the regular `watch` feature from `dotnet` CLI.

**Comment by marcin-dardzinski** [comment]
In case anyone is interested, I've found a workaround. You have to create an MSBuild target which runs the functions host and watch against this target:
In the csproj add
```
  <Target Name="RunFunctions">
    <Exec Command="func start" />
  </Target>
```
and later run it with `dotnet watch msbuild /t:RunFunctions`. 
So far works well for me.

**Comment by seed-of-apricot** [comment]
Would some workaround be on JavaScript/TypeScript environment?

**Comment by hlz** [comment]
I would also like to know how a hot reloaded or watched development environment can be setup in node. Any clues or leads?

**Comment by MattL-NZ** [comment]
> Would some workaround be on JavaScript/TypeScript environment?

I would also like to know this for Typescript...

**Comment by hlz** [comment]
Fwiw I have found out that it is possible running `func start`and `tsc -w` in parallel. Changes made to function code are picked up directly by the local function host so there is no need for restarting. Except for changes in `function.json` files. Could elaborate more if someone finds that interesting.

**Comment by grbspltt** [comment]
> Fwiw I have found out that it is possible running `func start`and `tsc -w` in parallel under JS/TS. Changes made to function code are picked up directly by the local function host so there is no need for restarting. Except for changes in `function.json` files. Could elaborate more if someone finds that interesting.

the big issue I have with this is the horrendous errors.  Since its trying to run compiled JS, you're left with trying to figure out where it went wrong in TS.  Would be nice to use `ts-node` for development

**Comment by hlz** [comment]
> the big issue I have with this is the horrendous errors. Since its trying to run compiled JS, you're left with trying to figure out where it went wrong in TS. Would be nice to use `ts-node` for development

Yeah this is far from ideal. Same problem arises when debugging code.

> edit: Created an issue for this #2302

Hope this will make it's way into the extension.

**Comment by ryan-theta** [comment]
Would this include live reload in Ubuntu WSL2 for the Python runtime?

**Comment by KevinFerm** [comment]
Hi! What's the status on this? Dotnet has this for years through dotnet watch run. Should be easy to add especially for azure functions in C#, no?

**Comment by chuanqisun** [comment]
Curious if this is being triaged at all. It is an obvious productivity killer. I'm using the out-of-the-box TypeScript Azure Function debug task from vscode. For every single change, I have to kill the entire running function, reinstalling npm package (why do we need this?), recompile typescript. That's 10-20 seconds gone. Please consider improving the default debug tasks
- Install npm only when necessary
- Fix the "restart" behavior. Currently, it just kills the function without restarting.
- Give us a well documented CLI that integrates with npm scripts, instead of relying on VSCode launch tasks. This opens up the tool for interoperability with other change detection/recompiling tools such as `ts-node` and `ts-node-dev`.

**Comment by panmau** [comment]
@chuanqisun If you use the start script provided with `func init` this works out of the box with Typescript.

**Comment by chenxizhang** [comment]
same issue here, let's make it fix on typescript azure function

**Comment by chenxizhang** [comment]
I saw that "tsc -w" is working fine, but the "func start" maybe have some problem, it just not able to detect the changes on the dist folder

**Comment by Yvand** [comment]
I have exactly the same behavior is @chenxizhang: "tsc -w" does update the files in dist folder, but func is not actually using those changes.

**Comment by nerblock** [comment]
I'm developing a ts api and this is driving me crazy. Please, implement this for god's sake. 🤦‍♂️

**Comment by Yvand** [comment]
I found how to make it work in my project:
I removed variables `WEBSITE_MOUNT_ENABLED` and `WEBSITE_RUN_FROM_PACKAGE` from my `local.settings.json`.
Now, `npm run start` immediately serves the changes when I save the .ts file.
Those variables were added when I executed `func azure functionapp fetch-app-settings`.

**Comment by chenxizhang** [comment]
wow, thanks to @Yvand, it works for me now. You save many time for me, man

**Comment by iSeiryu** [comment]
The workaround from @marcin-dardzinski is great, but is there a more native way to do it with dotnet 6? Something like `dotnet watch run` or `func watch start`?

**Comment by mdddev** [comment]
I second what @iSeiryu said. Afterall, hot reload was successfully kept in NET6 also vor non Visual Studio users. How can this be integrated into the function core tools?

**Comment by a3y3** [comment]
Agreed, this should absolutely be added as a feature (especially with Functions - 4 and/or .NET 6 projects)

**Comment by CharlieDigital** [comment]
@a3y3 agreed; since it works, it seems like the team should just formalize it.

**Comment by mdddev** [comment]
@CharlieDigital how did you get it to work with vs code? Sorry if I misunderstood.

**Comment by CharlieDigital** [comment]
@mdddev I used @marcin-dardzinski 's workaround as described above in this discussion.

**Comment by CharlieDigital** [comment]
@mdddev one can dream!

**Comment by a3y3** [comment]
Seems like this works already out of the box on Visual Studio? Not sure how the IDE does it under the hood but it has a hot reload button that applies the changes in less than a second.

**Comment by bmind7** [comment]
For JS `restart: true` added to **launch.json** saved my day 
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited

**Comment by safwanmasarik** [comment]
Eureka. I solved it in an elegant way. Here code ref: https://github.com/safwanmasarik/Azure-Function-Typescript-Hot-Reload .
Video evidence:
https://user-images.githubusercontent.com/35250295/201973704-b11eeb4a-8d41-4e0b-9f9b-385fdcf10846.mp4

**Comment by iljaiwjew** [comment]
Any progress on this for TypeScript? It's very annoying that such basic feature doesn't work

**Comment by allprogrammers** [comment]
This feature is really needed

**Comment by Trubador** [comment]
Any update on this? 
Development speed is very important.

**Comment by Trubador** [comment]
Any update on this? 
Development speed is very important.

**Comment by mdddev** [comment]
I second this. Out-of-the-box hot reload functionality is needed. Since this by the OP is a generic Hot Reload request generic with respect to the programming language used, there seem to be mainly two sides to this converstation. The ones using Javascript/Typescript and the ones using NET/C#. While there appear to be some workarounds for Typescript, none so far have presented themselves for NET.

I this something on the roadmap of the Azure Function Core Tools? Modern Azure Functions in the isolated worker are basically a console application, for which hot reload is supported, right? Therefore I assume it is in the way the Azure Function Core Tools choose to interact with the ability (or not).

**Comment by jaemsnrg** [comment]
If anyone was like me and ran into the looping nodemon issue, here is a fix:

package.json:
...
"start": "nodemon"
...

nodemon.json:
{
    "watch": ["your_function_folder/"],
    "ext": "js,json",
    "ignore": ["node_modules/"],
    "exec": "func start --verbose --javascript -p 3030 --watch"
}

**Comment by rafaelgrilli92** [comment]
Still not working for TypeScript. I can't believe a simple thing like this that speeds up the development process so much is still an issue.

**Comment by Crisfole** [comment]
If this isn't working for you in TS you should check your RUN_FROM_PACKAGE setting. It *must* be falsey (0 or unset) for picking up changes to your code as they come in.

**Comment by mdddev** [comment]
Raising the flag for .NET here again, as most of the posts here are for Typescript. allthough the thread started with C# 😊

As far as I can tell, all IDEs except (full blown) Visual Studio rely on the Function Core Tools to manage an Azure Functions project. I have had the same Hot Reload trauma with Jetbrains Rider as I had it with VS Code. It's just not working. 

I don't know how VS does it, but it seems like it does not rely on the Function Core Tools. 

Is it even considere to be on the roadmap anytime soon?

Another LTS version of NET has jsut dropped, and I am always super excited about the great tooling integration of NET. Everything is faster and better than ever before. Only working with Functions feels like a road bump without a Hot Reload functionality. I'm using it (hot reload) elsewhere and it is really hard to go back, once you realise how much more productive you are with it.

**Comment by subesokun** [comment]
I got this working with TS and the latest Azure Function Core Tools:

- Initialize the VSCode project via `> Azure Functions: Initialize Project for Use with VS Code...`
- Make sure that you've set `sourceMap: true` in your `tsconfig.json` compiler options (otherwise the breakpoints won't work)
- Launch the debugger task `Attach to Node Functions`
- Open a second terminal an run `npm run watch` (for hot reload)

With that you should be able to set breakpoints in your TS code can hot reload the function host on code changes.

**Comment by mdddev** [comment]
I'm glad you got this working. Although I do not understand why a .NET's hot reload feature is not working with one of the supported .NET languages. I guess it might be time to abandon .NET and go with TS, since there is clearly no indication that there will be any improvements soon. Sad.

**Comment by danielniccoli** [comment]
Hot reloading works for me. I develop in Python with the V2 model. Have not tried any other language. When I change code, the running app takes a moment to reload and the next time I trigger a function, the updated code is used.

I noticed one thing, though. I develop in VS Code with the `ms-azuretools.vscode-azurefunctions` extension. It comes with some a pre-configured `launch.json` and `tasks.json`, so I just have to press <kbd>F5</kbd> to start debugging. When debugging that way, hot reload *does not work**.

Instead, I start the host normally with `func host start --language-worker -- "-m debugpy --listen 127.0.0.1:9091"` and then use a custom debug config that attaches to the debugger without the shipped pre-launch tasks. Now when I change code, the function host does hot reload and I only have to re-attach the debugger.

I opened a ticket about this here: https://github.com/microsoft/vscode-azurefunctions/issues/3936

**Comment by fernandorovai** [comment]
Any way to ignore files on th same project to avoid hot reloading in Python?

**Comment by LevYas** [comment]
> In case anyone is interested, I've found a workaround. 
> ```
>   <Target Name="RunFunctions">
>     <Exec Command="func start" />
>   </Target>
> ```
> 
> and later run it with `dotnet watch msbuild /t:RunFunctions`. So far works well for me.

Does this workaround still work on .NET 8 and in-process functions? I've just migrated to .NET 8, and `func start` works fine, but if I run `dotnet watch -v msbuild /t:RunFunctions` it fails to start:

```
dotnet watch ⌚ Running  with the following arguments: 'msbuild /t:RunFunctions'
dotnet watch ⌚ Error while killing process ' ': No process is associated with this object.
dotnet watch 🚀 Started
dotnet watch ❌ Application failed to start: Cannot start process because a file name has not been provided.
dotnet watch ⌚ Caught top-level exception from hot reload: System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Watcher.Internal.ProcessRunner.RunAsync(ProcessSpec processSpec, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
```

I tried to understand what is the process `dotnet watch` complains about, but no luck.

**Comment by SwenRanj** [comment]
We are also facing problems with our containerized Azure Functions app in TypeScript. Any ideas on how to enable auto reloading in Docker scenario?

Our scenario is based of the [hello-world-tab-docker](https://github.com/OfficeDev/teams-toolkit-samples/tree/v2.5.0/hello-world-tab-docker) MS teams sample. The 'api' directory contains the actual Azure Functions app.

**Comment by MonkeyNinja** [comment]
> We are also facing problems with our containerized Azure Functions app in TypeScript. Any ideas on how to enable auto reloading in Docker scenario?
> 
> Our scenario is based of the [hello-world-tab-docker](https://github.com/OfficeDev/teams-toolkit-samples/tree/v2.5.0/hello-world-tab-docker) MS teams sample. The 'api' directory contains the actual Azure Functions app.

If you need to use Docker, then you have to copy the project files to the container, and not access it through the share. Shares do not propagate the file change notifications that hot reload requires to 'watch' sources and deps.

**Comment by SwenRanj** [comment]
> > We are also facing problems with our containerized Azure Functions app in TypeScript. Any ideas on how to enable auto reloading in Docker scenario?
> > Our scenario is based of the [hello-world-tab-docker](https://github.com/OfficeDev/teams-toolkit-samples/tree/v2.5.0/hello-world-tab-docker) MS teams sample. The 'api' directory contains the actual Azure Functions app.
> 
> If you need to use Docker, then you have to copy the project files to the container, and not access it through the share. Shares do not propagate the file change notifications that hot reload requires to 'watch' sources and deps.

We use volumes to 'share' code file with the image. The issue for us was more in the command baked into the `mcr.microsoft.com/azure-functions/node` image. In the end, and this is probably not ideal, we solved it by watching the files and running the command baked in the image:

Node Script (package.json):
`"dev:docker": "npx tsc-watch --onSuccess \"/opt/startup/start_nonappservice.sh\""`

**Comment by mdddev** [comment]
Hello, I recently upgraded my Azure Functions project to NET 9. Then I noticed that I could not `func start` the project anymore, I wsa always given the error `Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2` (note: there is only one csproj). I then tried `dotnet watch run` to run the project which worked, and futhermore, as I just found out by accident, hot reload seems to be working? Can someone please confirm? I was not able to attach Jetbrains Rider's in debugging mode to that process, it complained about binaries/assemblies being changed, but damn, even without debugging this is a welcome addition. Can someone confirm?

**Comment by adityamatt** [comment]
Bumping this up in 2025, Much needed for Typescript

**Comment by azerum** [comment]
For TypeScript, it seems like particular `host.json` settings matter for hot reloading. Ensure you have this part:

```
// host.json
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
     "version": "[4.*, 5.0.0)"
}
```

This part is included when generating project using Azure Functions VSCode extension, which explains why some report it to work

With that config, I got hot reloading to work on:
- macOS
- @azure/functions: 4.10.0
- typescript: 5.9.3
- `func --version`: 4.5.0
