### ISSUE TITLE
Unable to publish Facebook Prophet despite publishing all dependencies. 

### ISSUE THREAD

**Issue by wpmichel** [Azure/azure-functions-core-tools#1285]
I am using Facebook's prophet module to do some predicting using a Function app. When I attempt to publish my app, i get the following error: 

```
Installing collected packages: asn1crypto, azure-common, azure-nspkg, azure-cosmosdb-nspkg, idna, certifi, chardet, urllib3, requests, six, python-dateutil, pycparser, cffi, cryptography, azure-storage-common, azure-cosmosdb-table, ephem, pytz, convertdate, cycler, Cython, redis, holidays, setuptools, kiwisolver, lunardate, pyparsing, numpy, matplotlib, pandas, pip, azure-storage-queue, pystan, setuptools-git, fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hjtmj53k/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kq9a4bm4/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-w6b7hjux:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hjtmj53k/fbprophet/setup.py", line 120, in <module>
        """
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-hjtmj53k/fbprophet/setup.py", line 44, in run
        build_stan_model(target_dir)
      File "/tmp/pip-install-hjtmj53k/fbprophet/setup.py", line 27, in build_stan_model
        from pystan import StanModel
    ModuleNotFoundError: No module named 'pystan'
```

when using func pack --build-native-deps. However, commenting out the fbprophet requirement, I am able to publish even though pystan is still on my requirements.txt.

My requirements file: 
[requirements.txt](https://github.com/Azure/azure-functions-core-tools/files/3145049/requirements.txt)

My thought may be that prophet is searching in wrong directories when the publishing process calls on its setup.py, however, installing using pip works fine on my local machine. Thanks!

**Comment by ahmelsayed** [comment]
seems like a known issue for fbprophet package here https://github.com/facebook/prophet/issues/401 

From that issue, the workaround seems to either run the install command twice, or to install pystan before restoring your requirement.txt. 

Here is an ugly workaround you can do:

```bash
# Create a docker volume
docker volume create --name py-cache

# set this env var 
FUNCTIONS_PYTHON_DOCKER_RUN_COMMAND="run -d -v py-cache:/usr/local/lib/python3.6 mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv sleep infinity"

# Run the func pack command twice
func pack --build-native-deps
func pack --build-native-deps
```

**Comment by ahmelsayed** [comment]
actually hold on. I think something is missing there.

**Comment by ahmelsayed** [comment]
The workaround above should work. It's pretty hacky but should get you unblocked. I'll think of a better solution for these type of issues.

**Comment by ankitkumarr** [comment]
BTW, the above workaround will only work on core-tools version `>= 2.7.1149`.

**Comment by wpmichel** [comment]
Your solution worked! Thank you for your help.

**Comment by bsnithin44** [comment]
Hi @ahmelsayed,
 
I followed the steps you had mentioned, But I get the below error on running 

`func pack --build-native-deps`

Error
`Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xevk0i9j/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wogheg8z/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-0imihjnz" failed with error code 1 in /tmp/pip-install-xevk0i9j/fbprophet/`

core-tools version :2.7.1158

**Comment by ahmelsayed** [comment]
can you share your `requirements.txt`?

**Comment by bsnithin44** [comment]
Requirements file

[requirements.txt](https://github.com/Azure/azure-functions-core-tools/files/3176279/requirements.txt)

**Comment by ahmelsayed** [comment]
Your file worked for me. If you're using bash, make sure to export `FUNCTIONS_PYTHON_DOCKER_RUN_COMMAND`.

 I didn't have it above, this line should be 

```bash
export FUNCTIONS_PYTHON_DOCKER_RUN_COMMAND="run --rm -d -v py-cache:/usr/local/lib/python3.6 mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv sleep infinity"
```

**Comment by bsnithin44** [comment]
Hi @ahmelsayed 

I did export the `FUNCTIONS_PYTHON_DOCKER_RUN_COMMAND`

But still run into the same error. I think when I run `func pack --build-native-deps` it is still pulling from the docker image from `mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv` and not usuing the local image which was built.

Can you help me with what could be going wrong? I am not familiar with docker much and i couldnt find docs for `func pack`

**Comment by ahmelsayed** [comment]
Can you set `CLI_DEBUG=1` and run the same pack command again and share the output.

**Comment by bsnithin44** [comment]
Here is the output

```
Building wheels for collected packages: ephem, fbprophet, holidays
  Building wheel for ephem (setup.py) ... done
  Stored in directory: /home/.cache/pip/wheels/c2/19/af/23739730a62bb43acb1ff256c9234b0f1a94c4666c140a3c1d  Building wheel for fbprophet (setup.py) ... error
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kfrhqhrs/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7j21yxv8 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-kfrhqhrs/fbprophet/setup.py", line 120, in <module>
      """
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-kfrhqhrs/fbprophet/setup.py", line 44, in run
      build_stan_model(target_dir)
    File "/tmp/pip-install-kfrhqhrs/fbprophet/setup.py", line 27, in build_stan_model
      from pystan import StanModel
  ModuleNotFoundError: No module named 'pystan'

  ----------------------------------------
  Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
  Building wheel for holidays (setup.py) ... done
  Stored in directory: /home/.cache/pip/wheels/2d/cc/52/784fca01997448402695e3d0356d2f9c814d545bbcdef45d26Successfully built ephem holidays
Failed to build fbprophet
Installing collected packages: ephem, pytz, convertdate, six, cycler, Cython, numpy, pystan, python-dateutil, pandas, pyparsing, setuptools, kiwisolver, matplotlib, lunardate, holidays, setuptools-git, fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kfrhqhrs/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lai0bkqq/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-o85ot091:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kfrhqhrs/fbprophet/setup.py", line 120, in <module>
        """
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-kfrhqhrs/fbprophet/setup.py", line 44, in run
        build_stan_model(target_dir)
      File "/tmp/pip-install-kfrhqhrs/fbprophet/setup.py", line 27, in build_stan_model
        from pystan import StanModel
    ModuleNotFoundError: No module named 'pystan'

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kfrhqhrs/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lai0bkqq/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-o85ot091" failed with error code 1 in /tmp/pip-install-kfrhqhrs/fbprophet/
```

**Comment by bsnithin44** [comment]
My venv was deactivated while I was trying to publish the app. Hence I believe I was getting the above error.

However. Even after I publish the app. The imports of the same library are failing in .py file. Have you guys checked if the imports are working fine?

**Comment by priyaananthasankar** [comment]
Since you are using docker anyway, can you use conda to install pystan? Conda takes care of pystan installation pretty well by using the right architecture flags.

**Comment by bsnithin44** [comment]
Hi @ahmelsayed 

Please find the output with CLI_DEBUG=1

[output.txt](https://github.com/Azure/azure-functions-core-tools/files/3212056/output.with.clidebug.txt)

**Comment by ahmelsayed** [comment]
If the `./func` process can see the environment variables, it should print additional output like this. Try on a different machine and see why your environment variables are not taking effect. 

```
> dotnet build "/tmp/scratch/test/extensions.csproj" -o "/tmp/scratch/test/bin"                                                                                                               Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 262.07 ms for /tmp/scratch/test/extensions.csproj.
  extensions -> /tmp/scratch/test/bin/extensions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.87


> docker ps
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv'.> docker pull mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv
.done
Output: 2.0.12410-python3.6-buildenv: Pulling from azure-functions/python
Digest: sha256:a39e02ac12b297df0745728df37c9961563874b1295c423c60af12e7314feb77
Status: Image is up to date for mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv
Error:
Running 'docker run --rm -d -it  mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv sleep infinity'.> docker run --rm -d -it  mcr.microsoft.com/azure-functions/python:2.0.12410-python3.6-buildenv sleep infinity
.done
Output: eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6
Error:
Running 'docker cp "requirements.txt" eb7ceb:"/requirements.txt"'.> docker cp "requirements.txt" eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6:"/requirements.txt"
.done
Output:
Error:
Running 'docker cp "/tmp/tmpKggyBD.tmp" eb7ceb:"python_docker_build.sh"'.> docker cp "/tmp/tmpKggyBD.tmp" eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6:"python_docker_build.sh"
.done
Output:
Error:
Running 'docker exec -t eb7ceb chmod +x /python_docker_build.sh'.> docker exec -t eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6 chmod +x /python_docker_build.sh
.done
Output:
Error:
Running 'docker exec -t eb7ceb /python_docker_build.sh'.> docker exec -t eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6 /python_docker_build.sh
.done
Output: You are using pip version 19.0.3, however version 19.1.1 is available.                                                                                                                You should consider upgrading via the 'pip install --upgrade pip' command.
Error:
Running 'docker cp eb7ceb:"/.python_packages/." "/tmp/scratch/test/.python_packages"'.> docker cp eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6:"/.python_packages/." "/tmp/scratch/test/.python_packages"
.done
Output:
Error:
Running 'docker kill eb7ceb'.> docker kill eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6
.done
Output: eb7ceb828b6545c762e216d166bc4a5a4c7628ba321fb3876bff39a26b0871c6
Error:
Creating a new package /tmp/scratch/test/test.zip
```

**Comment by bsnithin44** [comment]
The issue got solved.

I had the problem because i was using `sudo` to run docker commands. But while setting the environment variable i was using `export` as `sudo export` will give error. And hence `./func` couldn't see the variables.

Thanks for the help

**Comment by rogeralsing** [comment]
This works for me to, the trick with `exports` on the env var was key.
