### ISSUE TITLE
python3 doesn't load correct worker

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-core-tools#1338]
Have the core-tools to use `python3` instead of `python`

```
 Starting language worker process:python3  "/usr/lib/azure-functions-core-tools/workers/python/worker.py" --host 127.0.0.1 --port 42165 --workerId ce2fd5ae-e971-44d1-a8dc-abfead036f4d --requestId f56d2a51-5123-4c68-9a2e-5f882223add0 --grpcMaxMessageLength 134217728
 python3 process with Id=13657 started                                                                                                                                     Adding dependency download request to python language worker
 Traceback (most recent call last):
   File "/usr/lib/azure-functions-core-tools/workers/python/worker.py", line 46, in <module>                                                                                   main()                                                                                                                                                                  File "/usr/lib/azure-functions-core-tools/workers/python/worker.py", line 32, in main                                                                                       import azure.functions  # NoQA                                                                                                                                        ModuleNotFoundError: No module named 'azure.functions'                                                                                                                    Language Worker Process exited.
 python3 exited with code 1                                                                                                                                                 ModuleNotFoundError: No module named 'azure.functions'.
```

**Comment by ahmedelnably** [comment]
I think this is a dupe of https://github.com/Azure/azure-functions-core-tools/issues/1327

**Comment by ahmelsayed** [comment]
no, #1327 is about supporting multiple versions of python other than 3.6. This is about working correctly if `python3` is an alias for 3.6.

**Comment by ankitkumarr** [comment]
@ahmelsayed, looks like core-tools did start `python3` `worker.py` correctly, but the import to `azure.functions` had issues? Are you able to reproduce this, if so, could you share the `PYTHONPATH` that is printed when in debug mode? I want to see if the `deps` directory is correctly added or not.

**Comment by liliankasem** [comment]
python3 is supported today:

```log
> which python
python not found
> which python3
/opt/homebrew/bin/python3
> func start
Found Python version 3.13.5 (python3).
```
