### ISSUE TITLE
Node runtime errors shown in console logs are missing important information

### ISSUE THREAD

**Issue by AE-MS** [Azure/azure-functions-core-tools#1438]
I recently had an issue where I was trying to develop my Azure Function and consume an npm package which was an ES6 module instead of a CommonJS module (node doesn't yet natively support ES6 modules without experimental flags, is my understanding).  However, I didn't know this was the problem because when trying to run my Azure function using "func", this is the output I got on the console:

    [7/12/2019 10:23:20 PM] Worker e35bb1db-2a05-4659-9027-3bd6d2674a8e connecting on 127.0.0.1:54872
    [7/12/2019 10:23:20 PM] [error] Worker was unable to load function <redacted>: 'SyntaxError: Unexpected token export'
    [7/12/2019 10:23:25 PM] Host lock lease acquired by instance ID '000000000000000000000000F4387C95'.

Note that middle error message and how it is seemingly unhelpful.  I didn't know how to trace down the problem based on that info, so on a whim I tried creating a simpler NodeJS-only application (i.e. NOT an Azure Function) that essentially did the same thing my Azure Function was doing and got a **much** more helpful error message that pointed me at the problem. I am (perhaps incorrectly) assuming that the full error is available when running as an Azure Function but it's just not being shown in the console log.  Would it be possible to show full NodeJS errors in the func console logs?

This was the full error message I got when running the same code directly in Node:

    d:\Users\<name>\Source\Repos\Scratch\NodeNoAzure\node_modules\ts-describe-action\index.js:10
    export const describeAction = describeA;
    ^^^^^^

 

    SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\Users\<name>\Source\Repos\Scratch\NodeNoAzure\node_modules\@<redacted>\<redacted>\build\activequery\actions.js:12:30)

**Comment by ahmedelnably** [comment]
cc/ @ColbyTresness and @mhoeger
