### ISSUE TITLE
App crashed and not starting, Exceeded language worker restart retry count for runtime:python.

### ISSUE THREAD

**Issue by dmitrysmirnovfinnair** [Azure/azure-functions-core-tools#1453]
I had an app which was running fine. Then after 11th July 2019 it stopped, and didn't start since then.
As I already got used to, the Azure portal UI is barely working, but once I managed to reach the part of UI where I could run the function manually, when I did so, logs had following errors:
```
2019-07-23T11:56:33.038361742Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Startup[413]
2019-07-23T11:56:33.038376242Z: [INFO]        Host started (2716ms)
2019-07-23T11:56:33.040931915Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Startup[0]
2019-07-23T11:56:33.040945015Z: [INFO]        Job host started
2019-07-23T11:56:33.057034147Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.057049447Z: [INFO]        python == /usr/local/bin/python
2019-07-23T11:56:33.058203535Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.058217035Z: [INFO]        PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
2019-07-23T11:56:33.059383423Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.059396423Z: [INFO]        starting the python worker
2019-07-23T11:56:33.062643989Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.062658588Z: [INFO]        Traceback (most recent call last):
2019-07-23T11:56:33.072469286Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.072484186Z: [INFO]          File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
2019-07-23T11:56:33.073664073Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.073677473Z: [INFO]            from azure.functions_worker import main
2019-07-23T11:56:33.074860461Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.074891261Z: [INFO]        ImportError: cannot import name 'main'
2019-07-23T11:56:33.076043149Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.076055749Z: [INFO]        python == /usr/local/bin/python
2019-07-23T11:56:33.077432934Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.077446134Z: [INFO]        PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
2019-07-23T11:56:33.078619922Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.078632922Z: [INFO]        starting the python worker
2019-07-23T11:56:33.190065658Z: [INFO]  Hosting environment: Production
2019-07-23T11:56:33.190613252Z: [INFO]  Content root path: /
2019-07-23T11:56:33.191291045Z: [INFO]  Now listening on: http://[::]:80
2019-07-23T11:56:33.191828939Z: [INFO]  Application started. Press Ctrl+C to shut down.
2019-07-23T11:56:34.556553086Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.556575286Z: [INFO]        Traceback (most recent call last):
2019-07-23T11:56:34.557325078Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.557337178Z: [INFO]          File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
2019-07-23T11:56:34.557350178Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.557354478Z: [INFO]            from azure.functions_worker import main
2019-07-23T11:56:34.558521065Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.558550265Z: [INFO]        ImportError: cannot import name 'main'
2019-07-23T11:56:34.632708391Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.632732990Z: [INFO]        python == /usr/local/bin/python
2019-07-23T11:56:34.633083087Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.633094387Z: [INFO]        PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
2019-07-23T11:56:34.633099287Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.633103486Z: [INFO]        starting the python worker
2019-07-23T11:56:33.721066212Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2019-07-23T11:56:33.721103912Z: [INFO]        Request starting HTTP/1.1 GET http://127.0.0.1:55715/robots933456.txt  
2019-07-23T11:56:33.968921523Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2019-07-23T11:56:33.968971323Z: [INFO]        Request finished in 249.9744ms 404 
2019-07-23T11:56:33.995906941Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2019-07-23T11:56:33.995921641Z: [INFO]        Request starting HTTP/1.1 GET http://marimekkodataloaders.azurewebsites.net/admin/host/ping  
2019-07-23T11:56:34.342217025Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2019-07-23T11:56:34.342252224Z: [INFO]        Request finished in 346.2976ms 200 
2019-07-23T11:56:35.947894755Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.947932054Z: [INFO]        Traceback (most recent call last):
2019-07-23T11:56:35.952448807Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.952462607Z: [INFO]          File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
2019-07-23T11:56:35.953008401Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.953020001Z: [INFO]            from azure.functions_worker import main
2019-07-23T11:56:35.954113790Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.954126990Z: [INFO]        ImportError: cannot import name 'main'
2019-07-23T11:56:36.014461759Z: [INFO]  [41m[30mfail[39m[22m[49m: Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher[0]
2019-07-23T11:56:36.014484059Z: [INFO]        Exceeded language worker restart retry count for runtime:python. Shutting down Functions Host
2019-07-23T11:56:36.260561789Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
2019-07-23T11:56:36.260616789Z: [INFO]        Stopping JobHost
2019-07-23T11:56:36.292887452Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Startup[0]
2019-07-23T11:56:36.292905051Z: [INFO]        Job host stopped
2019-07-23T11:56:36.326499100Z: [INFO]  Application is shutting down...
```

Now I decided to try to redeploy, so I did, and after a few building steps I get error, and the last thing in the log is:
```
Running 'docker exec -t 222984 /python_docker_build.sh'.> docker exec -t 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b /python_docker_build.sh
.....................done
Running 'docker kill 222984'.> docker kill 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b
.done
Output:

Error: Error response from daemon: Cannot kill container: 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b: Container 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b is not running
```
Any ideas for debugging or fixing it are welcome!

**Comment by dmitrysmirnovfinnair** [comment]
I tried deleting app, service plan, and creating them again, but I still can't deploy, still same cannot kill container issue.

**Comment by dmitrysmirnovfinnair** [comment]
the deployment issue seems to be gone after i updated the tools to the latest version, however I'm still wondering why did the app just stop working, and refuse to work again even though I have not touched it.

**Comment by ahmedelnably** [comment]
@maiqbal11 & @Hazhzeng can you please take a look
