### ISSUE TITLE
[BUG] when trying to run function QueueTrigger based

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-functions-core-tools#1524]
I am trying to run my Azure Function project using Storage Emulator, but I'm getting the following error:

System.MethodAccessException: 'Attempt by method 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener+<ExecuteAsync>d__27.MoveNext()' to access method 'Microsoft.Azure.WebJobs.Host.Protocols.FunctionDescriptor.get_LogName()' failed.'

It's a queue trigger, pointing to storage emulator.

**Comment by thdotnet** [comment]
Here's the stack trace:

   at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Listeners\QueueListener.cs:line 181
   at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147
   at Microsoft.Azure.WebJobs.Host.Timers.WebJobsExceptionHandler.<>c__DisplayClass3_0.<OnUnhandledExceptionAsync>b__0() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\WebJobsExceptionHandler.cs:line 54
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by Spharah** [comment]
i had the same issue, i downgraded Microsoft.Azure.WebJobs.Extensions.Storage  to 3.0.2 and the issue was fixed.

**Comment by thdotnet** [comment]
Microsoft.Azure.WebJobs.Extensions.Storage 3.0.6 works fine.

**Comment by Spharah** [comment]
Clearly there is something wrong with version 3.0.7
