### ISSUE TITLE
[linux consumption] [python] [westeurope] [ubuntu18] [core tools] System.ArgumentException: Only 'http' and 'https' schemes are allowed

### ISSUE THREAD

**Issue by ferantivero** [Azure/azure-functions-core-tools#1530]
just tried to follow the hello world sample from https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python
 
when trying to publish a new Azure Function  `CLI_DEBUG=1 func azure functionapp publish <funcappname> --access-token <token>`

## Err stack
```
System.ArgumentException: Only 'http' and 'https' schemes are allowed.
Parameter name: requestUri
   at System.Net.Http.HttpRequestMessage.InitializeValues(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Azure.Functions.Cli.Arm.ArmClient.HttpInvoke(Uri uri, String verb, String accessToken, Object objectPayload) in D:\a\1\s\src\Azure.Functions.Cli\Arm\ArmClient.cs:line 91
   at Azure.Functions.Cli.Arm.ArmClient.HttpInvoke(String method, Uri uri, String accessToken, Object objectPayload, Int32 retryCount) in D:\a\1\s\src\Azure.Functions.Cli\Arm\ArmClient.cs:line 36
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 295
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken, String managementURL, String slot, String defaultSubscription, ArmSubscriptionsArray allSubs) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 31
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 120
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 55
```

## Other details

```
# os
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
# azure
os-type: Linux
runtime: python
consumption-plan-location: westeurope
azure-cli  2.0.72  - Python (Linux) 3.6.8
Azure Function Core Tools version 2.7.1575  (hash: b7750e771a4e56352c767dfa16413ec9c79b72ba)
```

----------------------------------------

EDIT: possible workaround https://github.com/Azure/azure-functions-core-tools/issues/1530#issuecomment-526728337

**Comment by ferantivero** [comment]
just for other other people facing the same issue I was able to get it uploaded the very same function to the very same function app by using Azure Function Extensions for VS Code.

**Comment by ferantivero** [comment]
and here a workaround for those like me that need to get this uploaded from terminal:

1. zip the function folder content
2. exec the following az-CLI command: `az functionapp deployment source config-zip --src <zipfilename> -g <resroucegroup>  -n <functionappname>` 

which what I presume Azure Function Extensions for VS Code is doing behind the scenes.

**Comment by ankitkumarr** [comment]
@ferantivero would you mind sharing the output of this command --
`az cloud list --query "[?isActive].endpoints.resourceManager | [0]" --output json`

**Comment by ferantivero** [comment]
@ankitkumarr this is the output of executing `az cloud list --query "[?isActive].endpoints.resourceManager | [0]" --output json`

```
"https://management.azure.com/"
```

**Comment by ferantivero** [comment]
ping @ankitkumarr
