### ISSUE TITLE
azure function publish is failing with the following error: There was an error restoring dependencies.

### ISSUE THREAD

**Issue by zQmerit** [Azure/azure-functions-core-tools#1538]
I am trying to publish a python function to a linux machine in azure and am getting the following error:

There was an error restoring dependencies. You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\metadata.py", line 730, in __init__
    self._data = json.loads(data)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\__main__.py", line 234, in <module>
    main()
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\__main__.py", line 60, in main
    find_and_build_deps(args)
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\__main__.py", line 142, in find_and_build_deps
    wheel.install(paths, maker)
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\wheel.py", line 642, in install
    dist = InstalledDistribution(p)
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\database.py", line 558, in __init__
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\metadata.py", line 741, in __init__
    self.validate()
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\metadata.py", line 958, in validate
    missing, warnings = self._legacy.check(True)
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\metadata.py", line 522, in check
    self.set_metadata_version()
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\metadata.py", line 289, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "C:\Users\Zach\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\tools\python\packapp\distlib\metadata.py", line 167, in _best_version
    raise MetadataConflictError('Unknown metadata set')
distlib.metadata.MetadataConflictError: Unknown metadata set

It seems to fail when I include the following library in my requirements.txt:  spacy==2.1.8

**Comment by ahmedelnably** [comment]
Can you please try an use the remote build feature
func azure functionapp publish <appname> --build remote

**Comment by zQmerit** [comment]
I ended up fixing this issue. The problem was that I was building locally on a windows machine, but trying to publish to a linux machine. So all the python packages that were being installed were for windows and not linux. I fixed by using Azure devops and building a build pipeline that build the azure function app on a linux vm.
