### ISSUE TITLE
Unable to debug any functions, task fails always - message not useful for addressing the issue

### ISSUE THREAD

**Issue by kurx78** [Azure/azure-functions-core-tools#1580]
I'm unable to debug any function, it seems that threre is an issue Grpc.Core.RpcException and it seems to be specific when you create the first function in the project.
If you try to debug the project with func start without creating any functions it works well, but when you create the first it starts failing

Tried:
Switching to a different version of Azure Functions Core Tools
Switching to a different version of .NET Core SDK 
Rebooting
Running the command as an administrator

Not sure how to address the issue, the message is not very clear about what exactly is failing and what can be done to address the problem. Might be a bug or error

**Full transcript:**

$ func start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1633 Commit hash: 45c7d86a3bbc9ed0a80a8f4199aa7ea80ccfb24e)
Function Runtime Version: 2.0.12673.0
[10/4/2019 5:59:20 PM] Building host: startup suppressed:False, configuration suppressed: False
[10/4/2019 5:59:21 PM] Initializing Host.
[10/4/2019 5:59:21 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[10/4/2019 5:59:21 PM] LoggerFilterOptions
[10/4/2019 5:59:21 PM] {
[10/4/2019 5:59:21 PM]   "MinLevel": "None",
[10/4/2019 5:59:21 PM]   "Rules": [
[10/4/2019 5:59:21 PM]     {
[10/4/2019 5:59:21 PM]       "ProviderName": null,
[10/4/2019 5:59:21 PM]       "CategoryName": null,
[10/4/2019 5:59:21 PM]       "LogLevel": null,
[10/4/2019 5:59:21 PM]       "Filter": "<AddFilter>b__0"
[10/4/2019 5:59:21 PM]     },
[10/4/2019 5:59:21 PM]     {
[10/4/2019 5:59:21 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[10/4/2019 5:59:21 PM]       "CategoryName": null,
[10/4/2019 5:59:21 PM]       "LogLevel": "None",
[10/4/2019 5:59:21 PM]       "Filter": null
[10/4/2019 5:59:21 PM]     },
[10/4/2019 5:59:21 PM]     {
[10/4/2019 5:59:21 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[10/4/2019 5:59:21 PM]       "CategoryName": null,
[10/4/2019 5:59:21 PM]       "LogLevel": null,
[10/4/2019 5:59:21 PM]       "Filter": "<AddFilter>b__0"
[10/4/2019 5:59:21 PM]     }
[10/4/2019 5:59:21 PM]   ]
[10/4/2019 5:59:21 PM] }
[10/4/2019 5:59:21 PM] FunctionResultAggregatorOptions
[10/4/2019 5:59:21 PM] {
[10/4/2019 5:59:21 PM]   "BatchSize": 1000,
[10/4/2019 5:59:21 PM]   "FlushTimeout": "00:00:30",
[10/4/2019 5:59:21 PM]   "IsEnabled": true
[10/4/2019 5:59:21 PM] }
[10/4/2019 5:59:21 PM] SingletonOptions
[10/4/2019 5:59:21 PM] {
[10/4/2019 5:59:21 PM]   "LockPeriod": "00:00:15",
[10/4/2019 5:59:21 PM]   "ListenerLockPeriod": "00:00:15",
[10/4/2019 5:59:21 PM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[10/4/2019 5:59:21 PM]   "LockAcquisitionPollingInterval": "00:00:05",
[10/4/2019 5:59:21 PM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[10/4/2019 5:59:21 PM] }
[10/4/2019 5:59:21 PM] HttpOptions
[10/4/2019 5:59:21 PM] {
[10/4/2019 5:59:21 PM]   "DynamicThrottlesEnabled": false,
[10/4/2019 5:59:21 PM]   "MaxConcurrentRequests": -1,
[10/4/2019 5:59:21 PM]   "MaxOutstandingRequests": -1,
[10/4/2019 5:59:21 PM]   "RoutePrefix": "api"
[10/4/2019 5:59:21 PM] }
[10/4/2019 5:59:21 PM] Starting JobHost
[10/4/2019 5:59:21 PM] Starting Host (HostId=gomezj5mobl-1541114137, InstanceId=3da521f4-9d3c-4b0f-b2f6-77ddf22ba09a, Version=2.0.12673.0, ProcessId=14916, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[10/4/2019 5:59:21 PM] Loading functions metadata
[10/4/2019 5:59:21 PM] 1 functions loaded
[10/4/2019 5:59:21 PM] Starting language worker process:dotnet  "C:\Users\gomezj5\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Microsoft.Azure.Functions.PowerShellWorker.dll" --host 127.0.0.1 --port 57001 --workerId e55af008-534e-4f51-a23f-fe6b7e55b7fb --requestId 97e040f5-f545-4b1d-a606-2e603baa2945 --grpcMaxMessageLength 134217728
[10/4/2019 5:59:21 PM] dotnet process with Id=6120 started
[10/4/2019 5:59:21 PM] Generating 1 job function(s)
[10/4/2019 5:59:21 PM] Found the following functions:
[10/4/2019 5:59:21 PM] Host.Functions.MyHttpTrigger
[10/4/2019 5:59:21 PM]
[10/4/2019 5:59:21 PM] Host initialized (314ms)
[10/4/2019 5:59:21 PM] Host started (341ms)
[10/4/2019 5:59:21 PM] Job host started
Hosting environment: Production
Content root path: C:\Users\gomezj5\Documents\repos\azure-app-functions-lab
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        MyHttpTrigger: [GET,POST] http://localhost:7071/api/MyHttpTrigger

[10/4/2019 5:59:22 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[10/4/2019 5:59:23 PM] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
[10/4/2019 5:59:23 PM]    at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
[10/4/2019 5:59:23 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Messaging.MessagingStream.MoveNext() in C:\projects\azure-functions-powershell-worker\src\Messaging\MessagingStream.cs:line 34
[10/4/2019 5:59:23 PM]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessRequestLoop() in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 71
[10/4/2019 5:59:23 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.Main(String[] args) in C:\projects\azure-functions-powershell-worker\src\Worker.cs:line 42
[10/4/2019 5:59:23 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.<Main>(String[] args)
[10/4/2019 5:59:23 PM] Starting language worker process:dotnet  "C:\Users\gomezj5\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Microsoft.Azure.Functions.PowerShellWorker.dll" --host 127.0.0.1 --port 57001 --workerId 57cb95f2-8ce8-4c46-a3b5-0a468dd58e3e --requestId 972b8561-2290-45c6-aac1-02d04340448b --grpcMaxMessageLength 134217728
[10/4/2019 5:59:23 PM] dotnet process with Id=4428 started
[10/4/2019 5:59:24 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[10/4/2019 5:59:24 PM] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
[10/4/2019 5:59:24 PM]    at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
[10/4/2019 5:59:24 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Messaging.MessagingStream.MoveNext() in C:\projects\azure-functions-powershell-worker\src\Messaging\MessagingStream.cs:line 34
[10/4/2019 5:59:24 PM]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessRequestLoop() in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 71
[10/4/2019 5:59:24 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.Main(String[] args) in C:\projects\azure-functions-powershell-worker\src\Worker.cs:line 42
[10/4/2019 5:59:24 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.<Main>(String[] args)
[10/4/2019 5:59:24 PM] Starting language worker process:dotnet  "C:\Users\gomezj5\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Microsoft.Azure.Functions.PowerShellWorker.dll" --host 127.0.0.1 --port 57001 --workerId 5b78bbdc-22d0-4444-914d-31f89a2845d2 --requestId 98eeec7f-4378-40db-ab15-210d6c2bc0af --grpcMaxMessageLength 134217728
[10/4/2019 5:59:24 PM] dotnet process with Id=8852 started
[10/4/2019 5:59:25 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[10/4/2019 5:59:25 PM] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
[10/4/2019 5:59:25 PM]    at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
[10/4/2019 5:59:25 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Messaging.MessagingStream.MoveNext() in C:\projects\azure-functions-powershell-worker\src\Messaging\MessagingStream.cs:line 34
[10/4/2019 5:59:25 PM]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessRequestLoop() in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 71
[10/4/2019 5:59:25 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.Main(String[] args) in C:\projects\azure-functions-powershell-worker\src\Worker.cs:line 42
[10/4/2019 5:59:25 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.<Main>(String[] args)
[10/4/2019 5:59:25 PM] Exceeded language worker restart retry count for runtime:powershell. Shutting down Functions Host
[10/4/2019 5:59:25 PM] Stopping host...
[10/4/2019 5:59:25 PM] Stopping JobHost
[10/4/2019 5:59:25 PM] Job host stopped
[10/4/2019 5:59:25 PM] Host shutdown completed.
Application is shutting down...

**Comment by kurx78** [comment]
Update:
Maybe this is a network or firewall related issue?
I've tried this same example in my personal PC (where things like network and firewall are not company managed) and it worked without any issue

![image](https://user-images.githubusercontent.com/6843314/66236719-7bf81800-e6b0-11e9-894f-0fee5d65a34a.png)


Anyway, the message is still very criptic and gives you no idea of what is going wrong.

**Comment by kurx78** [comment]
Update: Probably not firewall related

1- Disabled my firewall
2- Made sure that the ports were open and not being used by another application
3- Same result

**Comment by kurx78** [comment]
Update: Not port related

Tried on different free ports, but still the same result

Also, it seems to be node and powershell related because dotnet projects are working without issues.

![image](https://user-images.githubusercontent.com/6843314/66243424-d9489500-e6c1-11e9-9fe6-e23dea8b6f74.png)

**Comment by ahmedelnably** [comment]
cc/ @pragnagopa any insights about this issue?

**Comment by pragnagopa** [comment]
@Francisco-Gamino  / @AnatoliB - can you please take a look?

**Comment by AnatoliB** [comment]
@kurx78 Could you please set the following environment variables, try to run again, and collect the logs from the standard output:
- GRPC_TRACE = all
- GRPC_VERBOSITY = DEBUG

I have got gRPC logs from (apparently) another user with similar symptoms, most likely referring to the same issue. This is what's happening a few times just before the failure:

> [10/7/2019 7:05:24 AM] I1007 09:05:24.303236 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:130: handshake_manager 000002536CF95230: error={"created":"@1570431924.303000000","description":"HTTP proxy returned response code 403","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\http_connect_handshaker.cc","file_line":220} shutdown=0 index=1, args={endpoint=0000000000000000, args=0000000000000000 {size=0: (null)}, read_buffer=0000000000000000 (length=0), exit_early=0}
[10/7/2019 7:05:24 AM] I1007 09:05:24.303265 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\channel\handshaker.cc:163: handshake_manager 000002536CF95230: handshaking complete -- scheduling on_handshake_done with error={"created":"@1570431924.303000000","description":"**HTTP proxy returned response code 403**","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\http_connect_handshaker.cc","file_line":220}
[10/7/2019 7:05:24 AM] I1007 09:05:24.303277 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\timer_generic.cc:467: TIMER 000002536CF952D8: CANCEL pending=true
[10/7/2019 7:05:24 AM] I1007 09:05:24.303295 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:960: **Connect failed**: {"created":"@1570431924.303000000","description":"**HTTP proxy returned response code 403**","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\http_connect_handshaker.cc","file_line":220}

Could you please check if your log contains "**HTTP proxy returned response code 403**" as well? If it does, please check if you also have HTTP_PROXY and/or NO_PROXY environment variables present?

May be related:

- https://stackoverflow.com/questions/45183076/grpc-c-client-14-connect-failed
- https://github.com/grpc/grpc/issues/9989

**Comment by AnatoliB** [comment]
I'm getting exactly the same symptoms when running on a machine with the HTTP_PROXY environment variable set to a fake URL. Setting NO_PROXY to `localhost,127.0.0.1` mitigates the issue for me. @kurx78 could you please try and let me know if this helps?

**Comment by AnatoliB** [comment]
@amamounelsayed FYI

**Comment by ahmedelnably** [comment]
@AnatoliB and @amamounelsayed any update on this issue?

**Comment by AnatoliB** [comment]
@kurx78, could you please confirm that setting the `NO_PROXY` environment variable to `localhost,127.0.0.1` resolved the issue for you. I know this definitely helped another user.

If confirmed, I think we just need to document this.

**Comment by predatorian3** [comment]
I am using MSYS2 on Windows 10 with my company security software blocking the use of `0.0.0.0:7071` instead of actually using `localhost:7071` or `127.0.0.1:7071`. This has been confirmed by using things like Jupyter Notebook and such where they can listen locally, but not on `0.0.0.0` connections, those get blocked. 

I set

```bash
export NO_PROXY=localhost,127.0.0.1
```
on my MSYS2 terminal and it did not work. If these tools allowed for the use of an overriding flag for `--host` to listen on any of those options, then that'd solve some flexibility issues for me. 


```
Hosting environment: Production
Content root path: C:\Users\predatorian3\Documents\Development\Python\Azure.Functions.pred_test
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        HttpTrigger: [GET,POST] http://localhost:7071/api/HttpTrigger
```

Notice how `http://0.0.0.0:7071` is not the same as `http://localhost:7071`.  `0.0.0.0` allows for global connections outside the localhost to connect. Binding to localhost or `127.0.0.1` accepts only connections from the localhost, not externally.

**Comment by predatorian3** [comment]
I tried this using CMD.exe outside of GitBash or MSYS2, and it seemed to work now. I'm not sure why its working this time.

**Comment by anthonychu** [comment]
@kurx78 Can you confirm if this is fixed for you as well? Thanks. /cc @AnatoliB
