### ISSUE TITLE
Improve timer trigger error message if storage emulator is not running

### ISSUE THREAD

**Issue by gpcastro** [Azure/azure-functions-core-tools#1592]
**Steps**
1. Create a new functions project: `func init test --docker` and select `dotnet` as the platform; I used Docker to make sure it wasn't something specific to my environment
2. Add a function, `func new --name timerFuncTest` with the `TimerTrigger` template
3. Run the app using `func start --build`

**Result**
I never see the function running, and this message is in the output:
```
The listener for function 'timerFuncTest' was unable to start.
[10/11/2019 11:57:58 PM] The listener for function 'timerFuncTest' was unable to start. Microsoft.WindowsAzure.Storage: No connection could be made because the target machine actively refused it. System.Net.Http: No connection could be made because the target machine actively refused it. System.Private.CoreLib: No connection could be made because the target machine actively refused it.
```

I also tried it building a docker image using the generated dockerfile and then running it with `docker run -it`. When running through Docker, I see the following exception in the output:

```
The listener for function 'timerFuncTest' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'timerFuncTest' was unable to start. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.get_TimerStatusDirectory() in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions\Extensions\Timers\Scheduling\StorageScheduleMonitor.cs:line 86
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.GetStatusBlobReference(String timerName) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions\Extensions\Timers\Scheduling\StorageScheduleMonitor.cs:line 144
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.GetStatusAsync(String timerName)
   at Microsoft.Azure.WebJobs.Extensions.Timers.Listeners.TimerListener.StartAsync(CancellationToken cancellationToken) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions\Extensions\Timers\Listener\TimerListener.cs:line 99
   at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonListener.cs:line 72
   at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 69
```
In neither case I see the code in the function actually running. 

**Tools**
Azure Functions Core Tools (2.7.1704 Commit hash: fbab3b9c1de5ab95e3b4b6a471ead62c4f37e89c)

**Comment by ahmelsayed** [comment]
It's not discoverable from the cli interface, but you'll have to start an azure storage emulator (https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator) on the machine, or replace the storage connection in local.settings.json with an actual azure storage connection string. 

We can improve the error message if the connection string is for the storage emulator. 

Some background on the requirement; a storage account is required for timer trigger to ensure expected singleton behavior when you run multiple instances

**Comment by gpcastro** [comment]
When I'm running locally, isn't the singleton behavior guaranteed by the fact that I'm only running one instance? If not, a local file should be enough since it's all local.

Another option is that if the storage account connection string is not present, core tools doesn't try to connect to it and shows a warning saying that singleton behavior will not be guaranteed.

There's a few options instead of not running the function at all. It is very frustrating for the user not to see anything happening, particularly since this is a typical first-usage scenario.

**Comment by ahmelsayed** [comment]
This would be a runtime feature ask. The runtime doesn't behave any differently in this regard whether you're running locally or in Azure. You can open an issue for that here: https://github.com/Azure/azure-functions-host

The only thing the core-tools can do is improve the error message. Will use this issue to track that.

**Comment by gpcastro** [comment]
Thanks. I've open an issue on azure-functions-host as well.

**Comment by anthonychu** [comment]
Closing in favor of https://github.com/Azure/azure-functions-host/issues/5087
