### ISSUE TITLE
Error: Cannot access a disposed object.

### ISSUE THREAD

**Issue by mohsinonxrm** [Azure/azure-functions-core-tools#1605]
I'm getting the following error when trying to run a simple QueueTrigger or an HttpTrigger Azure Function on Raspberry Pi 4B:
I have dotnet 2.2.402
I have func 2.7.1

`
                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1 Commit hash: N/A)
Function Runtime Version: 2.0.12763.0
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\azure-functions-core-tools-master\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 247
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\azure-functions-core-tools-master\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
Application is shutting down...
`

**Comment by ahmelsayed** [comment]
We don't have arm builds of the core tools.
