### ISSUE TITLE
InternalServerError on Syncing Triggers

### ISSUE THREAD

**Issue by keith-hinde** [Azure/azure-functions-core-tools#1629]
Consistently getting failures when trying to deploy a Python function to UK-South. 

Function is a simply blob file trigger, works fine on local testing.

Same symptoms as others have reported:

11:40:30 perdix: Syncing triggers...
11:40:39 perdix: Syncing triggers (Attempt 2/6)...
11:40:50 perdix: Syncing triggers (Attempt 3/6)...
11:41:12 perdix: Syncing triggers (Attempt 4/6)...
11:42:13 perdix: Syncing triggers (Attempt 5/6)...
11:43:38 perdix: Syncing triggers (Attempt 6/6)...
11:43:41: Error: Encountered an error (InternalServerError) from host runtime.

Are there any workarounds for this as yet?

Thanks in advance!

**Comment by balag0** [comment]
Looks like some problem with the storage account configured with the app. Can you check if the storage connection strings for the app look good in the application settings section?

Also if you have application insights enabled for the app, it might have some of this information. Let us know if you are able to resolve this.

Microsoft.WindowsAzure.Storage.StorageException : This request is not authorized to perform this operation.
    at async Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd,IRetryPolicy policy,OperationContext operationContext,CancellationToken token)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExistsAsync(??)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository.CreateBlobContainer(String connectionString) at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs : 73
    at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository..ctor(String secretSentinelDirectoryPath,String accountConnectionString,String siteSlotName,ILogger logger) at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs : 55
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.CreateSecretsRepository() at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 82
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.Create() at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 53
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Lazy`1.CreateValue()
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.get_Current() at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 49
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.FunctionsSyncManager.GetSyncTriggersPayload() at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs : 284
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.FunctionsSyncManager.TrySyncTriggersAsync(Boolean checkHash) at /azure-functions-host-36aed9bea21d846a4b4986612ca499ed3a045d31/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs : 100

**Comment by ahmelsayed** [comment]
@ankitkumarr  we could validate the storage connection string defined in the app on publish.
