### ISSUE TITLE
I tried Entity Framework Core 3 (netstandard2.1) with Azure Functions v3 (netcoreapp3.0), an error occurred in Metadata Generator.

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-core-tools#1642]
I tried Entity Framework Core 3 (netstandard2.1) with Azure Functions v3 (netcoreapp3.0), an error occurred in Metadata Generator.

```
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 指定されたファイルが見つかりません。
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :    at MakeFunctionJson.FunctionJsonConverter.TryRun()
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : 
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Error generating functions metadata
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error :
Microsoft.NET.Sdk.Functions.Build.targets(41,5): error : Metadata generation failed.
```

#### Repro

1. Create new function v3 project and change TFM to `netcoreapp3.0`
2. Install Entity Framework Core 3 (`Microsoft.EntityFrameworkCore.SqlServer`)
3. Add `DbContext` implementation
4. Build

_Originally posted by @shibayan in https://github.com/Azure/app-service-announcements-discussions/issues/115#issuecomment-543479631_

**Comment by fabiocav** [comment]
@a-vishar this is being tracked with other tooling updates. Apologies it hadn’t been updated to reflect that.

**Comment by SimonOrdo** [comment]
So, is there any workaround to using `Microsoft.EntityFrameworkCore.SqlServer` with V3?  Or is the gist of this that right now you can't and it'll get looked at with a later release?

**Comment by a-vishar** [comment]
You can use the last EF version that targeted netstandard 2.0.  The previous version is still compatible with core 3.x.

The tricky thing here is that you cannot publicly expose anything from a netstandard 2.1 library.  So you may have other libraries which may also be causing you issues.

**Comment by bobbytreed** [comment]
Having the same issue.  It's weird that it is intermittent for me and there doesn't seem to be a trigger.  2 builds ago it successfully built and I enabled migrations.  I changed one thing (not significant), rebuilt and got the error.  Cleaned the solution and it went a way, rebuilt and it came back.

**Comment by bobbytreed** [comment]
Here is a fun one.  When I remove this folder I get a bunch of access denied messages,  but I am able to build for a while until the message comes back.

.nuget\packages\microsoft.net.sdk.functions> rm -Recurse .\1.0.30-beta2\
rm : Cannot remove item
C:\Users\robreed\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\tools\net46\Microsoft.NET.Sdk.Functions.MSBuild.dll: Access to the path
'Microsoft.NET.Sdk.Functions.MSBuild.dll' is denied.
At line:1 char:1
+ rm -Recurse .\1.0.30-beta2\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.NET.Sdk.Functions.MSBuild.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
rm : Directory C:\Users\robreed\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\tools\net46 cannot be removed because it is not empty.
At line:1 char:1
+ rm -Recurse .\1.0.30-beta2\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (net46:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand

rm : Directory C:\Users\robreed\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\tools cannot be removed because it is not empty.
At line:1 char:1
+ rm -Recurse .\1.0.30-beta2\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (tools:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand

rm : Directory C:\Users\robreed\.nuget\packages\microsoft.net.sdk.functions\1.0.30-beta2\ cannot be removed because it is not empty.
At line:1 char:1
+ rm -Recurse .\1.0.30-beta2\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\robree...s\1.0.30-beta2\:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by brettsam** [comment]
We're working on a fix for this and other build-related issues. I have a preliminary fix ready now and hopefully we can get it out early next week for everyone to use.

**Comment by oising** [comment]
I'm getting this on core 2.2 project where it complains about newtonsoft.json 12.0.0.0

**Comment by DrBarnabus** [comment]
@brettsam Great to hear about the fix, I will definitely test it out when its released.

@oising That sounds like a different error, is it complaining that the required version is different from the resolved version? 
If it is, just add `<NoWarn>NU1608</NoWarn>` into your project and then manually install Newtonsoft.Json v12. I had the same issue before when using V2 but it isn't related to this issue.

**Comment by aherrick** [comment]
I'm also seeing this? how best to obtain the fix?

**Comment by brettsam** [comment]
When it's on nuget, I'll update it here with the details.
