### ISSUE TITLE
func new not working for JavaScript app

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1700]
did `func init` on a container and set JavaScript.  When I say `func new` I get this error. I tried passing in flags for language, template, etc. and nothings eems to work

Mac

> ➜  jehollan-perf-javascript func new
Value cannot be null. (Parameter 'value')

> ➜  jehollan-perf-java func --version
3.0.1975

/cc @ahmedelnably

**Comment by ahmelsayed** [comment]
can you try `CLI_DEBUG=1 func new` and share the output? I can't repro this on linux

**Comment by jeffhollan** [comment]
> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Azure.Functions.Cli.Common.TemplatesManager.GetTemplates() in D:\a\1\s\src\Azure.Functions.Cli\Common\TemplatesManager.cs:line 47
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 78
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66

**Comment by olillevik** [comment]
I see the same error. The error disappears after removing these lines from host.json
`    
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
`

**Comment by daxay** [comment]
any updates on this issue,
because i am facing that too.

**Comment by Hazhzeng** [comment]
Hi @soninaren ,

I'm also facing this issue now `Value cannot be null. (Parameter 'value')`.
Using CoreTools 3.0.2534

**Comment by soninaren** [comment]
@Hazhzeng. This is very likely caused by incomplete download of extension bundle

For Windows:
- Delete the contents of this folder `C:\Users\{user}\AppData\Local\Temp\Functions\ExtensionBundles` 

For Linux:
- Find the extension bundles folder and delete it  `find /private/var -name "ExtensionBundles" -print 2>/dev/null` (from https://github.com/Azure/azure-functions-core-tools/issues/1924#issuecomment-609582338)

**Comment by anthonychu** [comment]
This happens frequently enough and it's not clear how to resolve it. I'd love to see if we can automatically detect this and fix it. #1999

**Comment by soninaren** [comment]
@anthonychu you are correct about the frequency of the issue. The root cause has been very difficult to detect. That being said we can definitely add some defensive measures to make sure the bundle is fully downloaded before we move ahead.

**Comment by soninaren** [comment]
@daxay, Core tools is only supposed to download a bundle if a newer version of extension bundle is available. Otherwise it is supposed to use the bundle that is already downloaded to the temp folder. Checking for a newer version of bundle should only need to download a few bytes. 

I suspect the combination of the following 2 issues are causing this.
1. When the core tools tries to download the extension bundle for the first time, the download is only partially successful. Putting the core tools in bad state where it thinks the bundle is downloaded but it isn't.
2. The core tools could be downloading the bundle every time, even though one is present in the temp folder. So even a single instance of slow connection could put you in a bad state.

I am going to try and optimize bundle download process to do the following:
1. Perform sha verification to the downloaded bits so we can have a reliable download process. 
2. Use older version of bundle from tmp dirctory in case download fails.

**Comment by daxay** [comment]
@soninaren , I agreed with you about the Core tools behaviour on partially successful.

**Comment by anthonychu** [comment]
@sethjuarez Is running into this as well. On Windows.

```
❯ func new
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Azure.Functions.Cli.Common.TemplatesManager.GetTemplates() in D:\a\1\s\src\Azure.Functions.Cli\Common\TemplatesManager.cs:line 48
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 78
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

**Comment by anthonychu** [comment]
Got a copy of @sethjuarez's `C:\Users\{user}\AppData\Local\Temp\Functions\ExtensionBundles` folder (thanks!), it's missing files in the `bin` folder. It only has the first 5 files alphabetically, which indeed is consistent with an interrupted unzip.

@soninaren Is it possible to write a file at the end of extraction to signal that everything unzipped properly, and use it to decided whether to re-download?

**Comment by soninaren** [comment]
Writing file at the end of extraction would be tricky. It would be hard to make the operation atomic and we might end up seeing that file anyway. We can introduce a manifest file that lists all the files and  their relative paths in the bundle and verify that all files in the bundle are present including the manifest file. 
We can explicitly trigger bundle download and verification before host start in core tools.

**Comment by richardweaver** [comment]
I am having this issue in production on Azure. My functions work fine run locally but on Azure I get:
```
2020-08-10T12:31:41.081 [Error] Executed 'Functions.ImportProduct' (Failed, Id=52d40125-f29c-42af-aceb-c5aa4d0d93b5, Duration=1949ms)
Value cannot be null. (Parameter 'key')
```

How can I remove the ExtensionsBundle cache on live? Do I need to just do a new build/release and hope for the best?

**Comment by anthonychu** [comment]
@richardweaver Took a look at the logs on our side. Seeing errors about `durableClient` is invalid. Can you try it with `orchestrationClient` instead? `durableClient` is specific to Durable Functions v2, which will be available in extension bundles v2. It'll be available soon and we'll update our documentation on how to upgrade your app to take advantage of it.

/cc @davidmrdavid

**Comment by richardweaver** [comment]
@anthonychu Thanks for the pointer. I thought it might be related to the extension bundle issue after some googling around.

However, I removed all the durable functions pieces completely and after deployment it worked fine for a few minutes and then the same error started appearing. `Value cannot be null. (Parameter 'key')`

/cc @dhardie

**Comment by anthonychu** [comment]
@richardweaver Can you share the function.json from your functions having the issue?

@mathewc Looks like you might have recently added a null check to address this (https://github.com/Azure/azure-functions-host/pull/6478). Can you share what can cause this problem and any workarounds?

**Comment by richardweaver** [comment]
@anthonychu Sure:
```
{
  "bindings": [
    {
      "name": "product",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "importproduct",
      "connection": "AzureWebJobsStorage"
    },
    {
      "name": "existing",
      "type": "cosmosDB",
      "direction": "in",
      "databaseName": "%DatabaseName%",
      "collectionName": "%ProductsContainer%",
      "connectionStringSetting": "CosmosDBConnectionString",
      "id": "{No}",
      "partitionKey": "product"
    },
    {
      "name": "$return",
      "type": "cosmosDB",
      "direction": "out",
      "databaseName": "%DatabaseName%",
      "collectionName": "%ProductsContainer%",
      "connectionStringSetting": "CosmosDBConnectionString"
    }
  ]
}

```

**Comment by richardweaver** [comment]
Just to follow up on this, I can't even create a new function in a fresh, empty project:

```
C:\Users\weaverr\Projects>func init func-skeleton-3
Use the up/down arrow keys to select a worker runtime:node
Use the up/down arrow keys to select a language:javascript
Writing package.json
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing C:\Users\weaverr\Projects\func-skeleton-3\.vscode\extensions.json

C:\Users\weaverr\Projects>cd func-skeleton-3

C:\Users\weaverr\Projects\func-skeleton-3>func new
Value cannot be null. (Parameter 'value')
```

**Comment by Hazhzeng** [comment]
Hi @richardweaver, as Anthony mentioned, to mitigate this issue, you may want to remove the folders in `%appdata%/../Local/Temp/Functions`. The core tools cache a copy of ExtensionBundles in there. Clearing out the cache will initialize a redownload on the next **func** command.
