### ISSUE TITLE
Error uploading archive (BadRequest)

### ISSUE THREAD

**Issue by danielcrisp** [Azure/azure-functions-core-tools#1710]
I'm no longer able to deploy my Azure Functions. I'm able to deploy to my `staging` slot but when I deploy to the main _slot_ I get the following error:

```
Creating archive for current directory...
Directory .python_packages already in sync with requirements.txt. Skipping restoring dependencies...
Uploading 9.67 MB [###############################################################################]
Creating archive for current directory...
Directory .python_packages already in sync with requirements.txt. Skipping restoring dependencies...
Uploading 9.67 MB [###############################################################################]
Creating archive for current directory...
Directory .python_packages already in sync with requirements.txt. Skipping restoring dependencies...
Uploading 9.67 MB [###############################################################################]
Azure.Functions.Cli.Common.CliException: Error uploading archive (BadRequest).
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 29
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishZipDeploy(Site functionApp, Func`1 zipFileFactory) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 682
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishRunFromPackageLocal(Site functionApp, Func`1 zipFileFactory) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 500
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.HandleLinuxDedicatedPublish(Site functionApp, Func`1 zipStreamFactory) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 407
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 315
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 173
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

I've tried with the CLI and the VSCode extension.

`func` version: 2.7.1948. Running on OSX 10.14.6

**Comment by danielcrisp** [comment]
If I use this command:

    az functionapp deployment source config-zip  -g myResourceGroup -n \
<app_name> --src <zip_file_path>

I get this error:

```
Unable to load extension 'webapp'. Use --debug for more information.
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
The command failed with an unexpected error. Here is the traceback:

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 327, in enable_zip_deploy_functionapp
    return enable_zip_deploy(cmd, resource_group_name, name, src, timeout, slot)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 353, in enable_zip_deploy
    authorization, timeout)
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 2356, in _check_zip_deployment_status
    res_dict = response.json()
  File "/usr/local/Cellar/azure-cli/2.0.74/libexec/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

To open an issue, please run: 'az feedback'
```

**Comment by ankitkumarr** [comment]
A few questions that would help us debug --
1. What plan are you on? (App Service, Elastic Premium, Consumption)
2. What command are you running for publishing with any flags?
3. Would you be able to share your function app name and a time period for when you saw this issue?

**Comment by danielcrisp** [comment]
Hiya,

1. Function App - App Service - Standard. Is that enough?
2. Command is shown above, but here it is with the exact values:

```
az functionapp deployment source config-zip  -g blockdoxoccupancy -n bdx-functions --src __app__/__app__.zip
```
3. App name is `bdx-functions` and it was happening this morning between 10am-12pm UTC

**Comment by ankitkumarr** [comment]
Would you mind sharing the `func azure functionapp publish` command that you used above?

**Comment by danielcrisp** [comment]
It was this:

```
$ func azure functionapp publish bdx-functions --script-root ../__app__ --build-native-deps
```

By the way this command works fine:

```
$ func azure functionapp publish bdx-functions --slot staging --script-root ../__app__ --build-native-deps
```

Deploying to staging isn't a problem.

**Comment by danielcrisp** [comment]
I think there was some kind of temporary problem on Azure as this has now resolved itself. I opened a ticket within the Portal, so I'll close this.
