### ISSUE TITLE
Installing core tools reports back error

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-functions-core-tools#1838]
Download the core tools using the following command:

`npm i -g azure-functions-core-tools@3 --unsafe-perm true`

...keeps giving me the following error:

``` ps
PS C:\git\capuk\premgate\src\FunctionApi> npm i -g azure-functions-core-tools@3 --unsafe-perm true
npm ERR! code EEXIST
npm ERR! path C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
npm ERR! dest C:\Users\tda\AppData\Roaming\npm\func
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js' -> 'C:\Users\tda\AppData\Roaming\npm\func'
npm ERR! File exists: C:\Users\tda\AppData\Roaming\npm\func
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tda\AppData\Roaming\npm-cache\_logs\2020-02-20T12_43_34_356Z-debug.log
```

and the workaround at the moment is to run the following:

``` ps
PS C:\git\capuk\premgate\src\FunctionApi> npm i -g azure-functions-core-tools@3 --unsafe-perm true --force
npm WARN using --force I sure hope you know what you are doing.
C:\Users\tda\AppData\Roaming\npm\func -> C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\tda\AppData\Roaming\npm\azurefunctions -> C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\tda\AppData\Roaming\npm\azfun -> C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@3.0.2106 postinstall C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/3.0.2106/Azure.Functions.Cli.win-x64.3.0.2106.zip"
[==================] Downloading Azure Functions Core Tools

Telemetry
---------
The Azure Functions Core tools collect usage data in order to help us improve your experience.
The data is anonymous and doesn't include any user specific or personal information. The data is collected by Microsoft.

You can opt-out of telemetry by setting the FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

+ azure-functions-core-tools@3.0.2106
added 53 packages from 33 contributors in 30.246s
PS C:\git\capuk\premgate\src\FunctionApi>
```

**Comment by anthonychu** [comment]
@jsacapdev Can you share your npm version so we can try to reproduce this? Thanks.

**Comment by jsacapdev** [comment]
@anthonychu 

``` ps
PS C:\> npm version
{
  npm: '6.13.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '2.0.1',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.14.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}
```

If it helps, it looks like this happens when a new release is available. so i tried to run the command this morning, which attempted to pull down version `3.0.2106` and that worked without any problems. But I have been seeing this problem more than once so I can only assume it is when a new release is published?

**Comment by jsacapdev** [comment]
this happened again this morning:

``` ps
PS C:\> npm i -g azure-functions-core-tools@3 --unsafe-perm true
C:\Users\tda\AppData\Roaming\npm\func -> C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\tda\AppData\Roaming\npm\azurefunctions -> C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\tda\AppData\Roaming\npm\azfun -> C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@3.0.2106 postinstall C:\Users\tda\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/3.0.2106/Azure.Functions.Cli.win-x64.3.0.2106.zip"
[==================] Downloading Azure Functions Core ToolsError: read ECONNRESET
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@3.0.2106 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@3.0.2106 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tda\AppData\Roaming\npm-cache\_logs\2020-02-24T09_01_57_943Z-debug.log
```

**Comment by tkawchak** [comment]
Seeing this same issue with npm version 6.14.4

**Comment by katlimruiz** [comment]
I have node v12.16.1 and npm 6.13 and I also see the same issue when trying to install core tools 3.

workaround `npm i -g azure-functions-core-tools@3 --unsafe-perm true --force` works

**Comment by TroyWitthoeft** [comment]
Just ran into this as well.  It's getting to the point were I am hesitant to update the azure functions core tools.  :(

I had a working system. Launched VS Code.  VS Code Azure functions extension detected older version of azure functions core tools.  It prompted me to update core tools.  I obliged with a click.  That broke my core tools install.  Func.exe not working.  Error = 

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\TWitthoeft\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}

```

Attempted Reinstall of core tools from command line  with 
`npm i -g azure-functions-core-tools@3 --unsafe-perm true`

That resulted in error

```
npm ERR! code EEXIST
npm ERR! path C:\Users\TWitthoeft\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
npm ERR! dest C:\Users\TWitthoeft\AppData\Roaming\npm\func.cmd
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\TWitthoeft\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js' -> 'C:\Users\TWitthoeft\ApppData\Roaming\npm\func.cmd'
npm ERR! File exists: C:\Users\TWitthoeft\AppData\Roaming\npm\func.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TWitthoeft\AppData\Roaming\npm-cache\_logs\2020-09-30T18_07_50_390Z-debug.log
```
Forced it with command
`npm i -g azure-functions-core-tools@3 --unsafe-perm true --force`

Ran func.exe.  All good!

**Comment by apawast** [comment]
@jsacapdev are you still experiencing this issue?
