### ISSUE TITLE
Error calling sync triggers (BadRequest). Python runtime on Linux. 

### ISSUE THREAD

**Issue by groovy-sky** [Azure/azure-functions-core-tools#1885]
Hello.
I'm trying to get a simple function working, using python on Consumption Plan(region - West Europe).
Environment:
* func ver. - 2.7.2184
* Azure Functions extenstion ver. - 0.21.0

Here is the approach using Core tools :

```
Deployment successful.
Remote build succeeded!
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = 'ea1b1f84-d09c-42d9-8485-62acffa8e906'.
```
Here is the approach using Visual Studio Code:
```
2:33:47 PM python-test-project: Deployment successful.
2:34:03 PM python-test-project: Syncing triggers...
2:34:35 PM python-test-project: Syncing triggers (Attempt 2/6)...
2:34:46 PM python-test-project: Syncing triggers (Attempt 3/6)...
2:35:07 PM python-test-project: Syncing triggers (Attempt 4/6)...
2:35:48 PM python-test-project: Syncing triggers (Attempt 5/6)...
2:37:09 PM python-test-project: Syncing triggers (Attempt 6/6)...
2:37:10 PM: Error: Encountered an error (InternalServerError) from host runtime.
```

**Comment by anthonychu** [comment]
@balag0 Can you please take a look?

**Comment by balag0** [comment]
I see the following exception from our logs. This most likely means the value for appsetting **AzureWebjobsStorage** is empty or invalid. Can you check?

System.FormatException : Settings must be of the form 'name=value'.
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.<>c.<Parse>b__97_0(String err)
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseStringIntoSettings(String connectionString,Action`1 error)
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseImpl(String connectionString,CloudStorageAccount& accountInformation,Action`1 error)
    at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
    at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository.CreateBlobContainer(String connectionString) at /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs : 68
    at Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository..ctor(String secretSentinelDirectoryPath,String accountConnectionString,String siteSlotName,ILogger logger) at /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs : 55
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.CreateSecretsRepository() at /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 82
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.Create() at /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 53
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Lazy`1.CreateValue()
    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultSecretManagerProvider.get_Current() at /src/azure-functions-host/src/WebJobs.Script.WebHost/Security/KeyManagement/DefaultSecretManagerProvider.cs : 49
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.FunctionsSyncManager.GetSyncTriggersPayload() at /src/azure-functions-host/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs : 308
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.FunctionsSyncManager.TrySyncTriggersAsync(Boolean isBackgroundSync) at /src/azure-functions-host/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs : 110

**Comment by groovy-sky** [comment]
Hi @balag0 
Below you can see my config:
![image](https://user-images.githubusercontent.com/40501227/76454035-94e1c380-63dc-11ea-95c0-a59c447bdfca.png)

**Comment by balag0** [comment]
Since the error is from the remote instance, Can you check the config using the Azure portal as well. Updating the appsetting in the portal with the same connection string as the screenshot should fix the issue. Let me know if the app setting looks correct there as well.

**Comment by groovy-sky** [comment]
Config is not available in portal. As function creation was unsuccessful:
![image](https://user-images.githubusercontent.com/40501227/76501733-7666e100-644b-11ea-9ba5-89b6534625d4.png)

**Comment by groovy-sky** [comment]
Hello.
Any news?

**Comment by balag0** [comment]
@groovy-sky 
Click on the Configuration link under Configured features in the screen shot

Make sure the app setting AzureWebjobsStorage is present and the value is set to a valid storage connection string.
