### ISSUE TITLE
Can't run function app locally

### ISSUE THREAD

**Issue by vimanmg** [Azure/azure-functions-core-tools#1888]
I am trying to run a function app locally. For that I have installed azure function latest version, however I am getting the following exception.

I have read some other posts where users refer to proxy issues - That is why I defined it even though is a local connection. No luck with that.

Any help is appreciated.
Thanks and Cheers
Vi

```
PS C:\Users\myuser\myapp> npm i -g azure-functions-core-tools@3 --unsafe-perm true
++ azure-functions-core-tools@3.0.2245
updated 3 packages in 255.029s
PS C:\Users\myuser\myapp> npm config set proxy http://mycorporateproxy.com:mycorporateport
PS C:\Users\myuser\myapp> npm config set https-proxy http://mycorporateproxy.com:mycorporateport
PS C:\Users\myuser\myapp>
PS C:\Users\myuser\myapp> func start
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
Function Runtime Version: 3.0.13139.0
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
[3/11/2020 7:51:10 AM] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '7c49c45d-f734-4104-8bb9-408cdd894330'[3/11/2020 7:51:10 AM] Reading host configuration file 'C:\Users\myuser\myapp\host.json'
[3/11/2020 7:51:10 AM] Host configuration file read:
[3/11/2020 7:51:10 AM] {
[3/11/2020 7:51:10 AM]   "version": "2.0"
[3/11/2020 7:51:10 AM] }
[3/11/2020 7:51:10 AM] Reading functions metadata
[3/11/2020 7:51:10 AM] 12 functions found
[3/11/2020 7:51:10 AM] Initializing Warmup Extension.
[3/11/2020 7:51:10 AM] Initializing Host. OperationId: '7c49c45d-f734-4104-8bb9-408cdd894330'.
[3/11/2020 7:51:10 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=7c49c45d-f734-4104-8bb9-408cdd894330
[3/11/2020 7:51:10 AM] LoggerFilterOptions
[3/11/2020 7:51:10 AM] {
[3/11/2020 7:51:10 AM]   "MinLevel": "None",
[3/11/2020 7:51:10 AM]   "Rules": [
[3/11/2020 7:51:10 AM]     {
[3/11/2020 7:51:10 AM]       "ProviderName": null,
[3/11/2020 7:51:10 AM]       "CategoryName": null,
[3/11/2020 7:51:10 AM]       "LogLevel": null,
[3/11/2020 7:51:10 AM]       "Filter": "<AddFilter>b__0"
[3/11/2020 7:51:10 AM]     },
[3/11/2020 7:51:10 AM]     {
[3/11/2020 7:51:10 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[3/11/2020 7:51:10 AM]       "CategoryName": null,
[3/11/2020 7:51:10 AM]       "LogLevel": "None",
[3/11/2020 7:51:10 AM]       "Filter": null
[3/11/2020 7:51:10 AM]     },
[3/11/2020 7:51:10 AM]     {
[3/11/2020 7:51:10 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[3/11/2020 7:51:10 AM]       "CategoryName": null,
[3/11/2020 7:51:10 AM]       "LogLevel": null,
[3/11/2020 7:51:10 AM]       "Filter": "<AddFilter>b__0"
[3/11/2020 7:51:10 AM]     }
[3/11/2020 7:51:10 AM]   ]
[3/11/2020 7:51:10 AM] }
[3/11/2020 7:51:10 AM] FunctionResultAggregatorOptions
[3/11/2020 7:51:10 AM] {
[3/11/2020 7:51:10 AM]   "BatchSize": 1000,
[3/11/2020 7:51:10 AM]   "FlushTimeout": "00:00:30",
[3/11/2020 7:51:10 AM]   "IsEnabled": true
[3/11/2020 7:51:10 AM] }
[3/11/2020 7:51:10 AM] SingletonOptions
[3/11/2020 7:51:10 AM] {
[3/11/2020 7:51:10 AM]   "LockPeriod": "00:00:15",
[3/11/2020 7:51:10 AM]   "ListenerLockPeriod": "00:00:15",
[3/11/2020 7:51:10 AM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[3/11/2020 7:51:10 AM]   "LockAcquisitionPollingInterval": "00:00:05",
[3/11/2020 7:51:10 AM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[3/11/2020 7:51:10 AM] }
[3/11/2020 7:51:10 AM] HttpOptions
[3/11/2020 7:51:10 AM] {
[3/11/2020 7:51:10 AM]   "DynamicThrottlesEnabled": false,
[3/11/2020 7:51:10 AM]   "MaxConcurrentRequests": -1,
[3/11/2020 7:51:10 AM]   "MaxOutstandingRequests": -1,
[3/11/2020 7:51:10 AM]   "RoutePrefix": "api"
[3/11/2020 7:51:10 AM] }
[3/11/2020 7:51:10 AM] Starting JobHost
[3/11/2020 7:51:10 AM] Starting Host (HostId=bdp6m86g1sjr2-1108731522, InstanceId=835bc3ca-b1c8-436a-8db1-acfdab2d4073, Version=3.0.13139.0, ProcessId=25280, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[3/11/2020 7:51:10 AM] Loading functions metadata
[3/11/2020 7:51:10 AM] 12 functions loaded
[3/11/2020 7:51:10 AM] Loading proxies metadata
[3/11/2020 7:51:10 AM] Initializing Azure Function proxies
[3/11/2020 7:51:11 AM] 0 proxies loaded
[3/11/2020 7:51:11 AM] Starting worker process:node  "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 54956 --workerId cd66c210-5bd5-4368-8e48-fea58e83c1b3 --requestId b67ac414-b3e7-4c39-bdb1-307f9fb896a7 --grpcMaxMessageLength
134217728
[3/11/2020 7:51:11 AM] node process with Id=25512 started
[3/11/2020 7:51:11 AM] Generating 12 job function(s)
[3/11/2020 7:51:11 AM] Found the following functions:
[3/11/2020 7:51:11 AM] Host.Functions.apimanager
[3/11/2020 7:51:11 AM] Host.Functions.apimanagerversion
[3/11/2020 7:51:11 AM] Host.Functions.apimanagerversioncontract
[3/11/2020 7:51:11 AM] Host.Functions.apimanagerversionpolicy
[3/11/2020 7:51:11 AM] Host.Functions.apipolicy
[3/11/2020 7:51:11 AM] Host.Functions.businessgroup
[3/11/2020 7:51:11 AM] Host.Functions.clientapplication
[3/11/2020 7:51:11 AM] Host.Functions.clientapplicationowner
[3/11/2020 7:51:11 AM] Host.Functions.cloudhubapplication
[3/11/2020 7:51:11 AM] Host.Functions.environment
[3/11/2020 7:51:11 AM] Host.Functions.hybridapplication
[3/11/2020 7:51:11 AM] Host.Functions.rolemapping
[3/11/2020 7:51:11 AM]
[3/11/2020 7:51:11 AM] Initializing function HTTP routes
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/apimanager' [get] to 'apimanager'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/apimanagerversion' [get] to 'apimanagerversion'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/apimanagerversioncontract' [get] to 'apimanagerversioncontract'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/apimanagerversionpolicy' [get] to 'apimanagerversionpolicy'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/apipolicy' [get] to 'apipolicy'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/businessgroup' [get] to 'businessgroup'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/clientapplication' [get] to 'clientapplication'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/clientapplicationowner' [get] to 'clientapplicationowner'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/cloudhubapplication' [get] to 'cloudhubapplication'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/environment' [get] to 'environment'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/hybridapplication' [get] to 'hybridapplication'
[3/11/2020 7:51:11 AM] Mapped function route 'api/v1.0/rolemapping' [get] to 'rolemapping'
[3/11/2020 7:51:11 AM]
[3/11/2020 7:51:11 AM] Host initialized (656ms)
[3/11/2020 7:51:11 AM] Host started (668ms)
[3/11/2020 7:51:11 AM] Job host started
Hosting environment: Production
Content root path: C:\Users\myuser\myapp
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        example: [GET] http://localhost:7071/api/v1.0/example

[3/11/2020 7:51:11 AM] Worker cd66c210-5bd5-4368-8e48-fea58e83c1b3 connecting on 127.0.0.1:54956
[3/11/2020 7:51:12 AM] [error] Worker cd66c210-5bd5-4368-8e48-fea58e83c1b3 encountered event stream error:  { Error: 14 UNAVAILABLE: failed to connect to all addresses
[3/11/2020 7:51:12 AM] Worker cd66c210-5bd5-4368-8e48-fea58e83c1b3 exited with code 1
[3/11/2020 7:51:12 AM]     at Object.module.exports.exports.createStatusError (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[3/11/2020 7:51:12 AM] Starting worker process:node  "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 54956 --workerId b394146e-c09f-4867-9fce-ab544468e7d1 --requestId a84559a9-5929-4608-99fd-eadae583e78c --grpcMaxMessageLength
134217728
[3/11/2020 7:51:12 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7500:26)
[3/11/2020 7:51:12 AM] [error] Worker cd66c210-5bd5-4368-8e48-fea58e83c1b3 uncaught exception: Error: Error: 14 UNAVAILABLE: failed to connect to all addresses
  at ClientDuplexStream.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:17750:19)
at ClientDuplexStream.emit (events.js:182:13)     at ClientDuplexStream._emitStatusIfDone (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7501:12)     at ClientDuplexStream._receiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7478:8)     at Object.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21923:15)     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21185:42)     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21235:8)     at C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21740:18
[3/11/2020 7:51:12 AM] node process with Id=21920 started
[3/11/2020 7:51:12 AM]     at ClientDuplexStream._receiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7478:8)
[3/11/2020 7:51:12 AM]     at Object.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21923:15)
[3/11/2020 7:51:12 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21185:42)
[3/11/2020 7:51:12 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21235:8)
[3/11/2020 7:51:12 AM]     at C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21740:18
[3/11/2020 7:51:12 AM]   code: 14,
[3/11/2020 7:51:12 AM]   metadata: Metadata { _internal_repr: {}, flags: 0 },
[3/11/2020 7:51:12 AM]   details: 'failed to connect to all addresses' }
[3/11/2020 7:51:12 AM] Worker b394146e-c09f-4867-9fce-ab544468e7d1 connecting on 127.0.0.1:54956
[3/11/2020 7:51:13 AM] [error] Worker b394146e-c09f-4867-9fce-ab544468e7d1 encountered event stream error:  { Error: 14 UNAVAILABLE: failed to connect to all addresses
[3/11/2020 7:51:13 AM] Worker b394146e-c09f-4867-9fce-ab544468e7d1 exited with code 1
[3/11/2020 7:51:13 AM]     at Object.module.exports.exports.createStatusError (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[3/11/2020 7:51:13 AM] [error] Worker b394146e-c09f-4867-9fce-ab544468e7d1 uncaught exception: Error: Error: 14 UNAVAILABLE: failed to connect to all addresses
  at ClientDuplexStream.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:17750:19)
at ClientDuplexStream.emit (events.js:182:13)     at ClientDuplexStream._emitStatusIfDone (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7501:12)     at ClientDuplexStream._receiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7478:8)     at Object.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21923:15)     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21185:42)     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21235:8)     at C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21740:18
[3/11/2020 7:51:13 AM] Starting worker process:node  "C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 54956 --workerId 8259af5d-5a67-4f97-9f88-f568b4fd2a8a --requestId 1d23b8ca-8db2-4712-9c41-85b8805449c8 --grpcMaxMessageLength
134217728
[3/11/2020 7:51:13 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7500:26)
[3/11/2020 7:51:13 AM]     at ClientDuplexStream._receiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7478:8)
[3/11/2020 7:51:13 AM]     at Object.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21923:15)
[3/11/2020 7:51:13 AM] node process with Id=23656 started
[3/11/2020 7:51:13 AM]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21185:42)
[3/11/2020 7:51:13 AM]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21235:8)
[3/11/2020 7:51:13 AM]     at C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21740:18
[3/11/2020 7:51:13 AM]   code: 14,
[3/11/2020 7:51:13 AM]   metadata: Metadata { _internal_repr: {}, flags: 0 },
[3/11/2020 7:51:13 AM]   details: 'failed to connect to all addresses' }
[3/11/2020 7:51:13 AM] Worker 8259af5d-5a67-4f97-9f88-f568b4fd2a8a connecting on 127.0.0.1:54956
[3/11/2020 7:51:14 AM] [error] Worker 8259af5d-5a67-4f97-9f88-f568b4fd2a8a encountered event stream error:  { Error: 14 UNAVAILABLE: failed to connect to all addresses
[3/11/2020 7:51:14 AM] Worker 8259af5d-5a67-4f97-9f88-f568b4fd2a8a exited with code 1
[3/11/2020 7:51:14 AM] [error] Worker 8259af5d-5a67-4f97-9f88-f568b4fd2a8a uncaught exception: Error: Error: 14 UNAVAILABLE: failed to connect to all addresses
  at ClientDuplexStream.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:17750:19)
at ClientDuplexStream.emit (events.js:182:13)     at ClientDuplexStream._emitStatusIfDone (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7501:12)     at ClientDuplexStream._receiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7478:8)     at Object.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21923:15)     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21185:42)     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21235:8)     at C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21740:18
[3/11/2020 7:51:14 AM] Exceeded language worker restart retry count for runtime:node. Shutting down Functions Host
[3/11/2020 7:51:14 AM]     at Object.module.exports.exports.createStatusError (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:1358:15)
[3/11/2020 7:51:14 AM]     at ClientDuplexStream._emitStatusIfDone (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7500:26)
[3/11/2020 7:51:14 AM]     at ClientDuplexStream._receiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7478:8)
[3/11/2020 7:51:14 AM] Stopping host...
[3/11/2020 7:51:14 AM]     at Object.onReceiveStatus (C:\Users\myuser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21923:15)
[3/11/2020 7:51:14 AM] Stopping JobHost
[3/11/2020 7:51:14 AM] Job host stopped
[3/11/2020 7:51:14 AM] Host shutdown completed.
PS C:\Users\myuser\myapp>
```

**Comment by anthonychu** [comment]
@pragnagopa @mhoeger Could you please take a look at this? Thanks.

**Comment by vimanmg** [comment]
Is there any update on this one?

**Comment by mhoeger** [comment]
Hi @vimanmg - sorry for the delay. I'm investigating and I believe that the underlying component that is failing (gRPC) will honor the following environment variables based off of what i've seen from posts on issues like [this](https://github.com/grpc/grpc/issues/9989)...

Can you try adding the following to local.settings.json?
```
    "http_proxy": "http://mycorporateproxy.com:mycorporateport",
    "https_proxy": "http://mycorporateproxy.com:mycorporateport",
    "no_proxy": "localhost,127.0.0.1",
    "HTTP_PROXY": "http://mycorporateproxy.com:mycorporateport",
    "HTTPS_PROXY": "http://mycorporateproxy.com:mycorporateport",
    "NO_PROXY": "localhost,127.0.0.1"
```

**Comment by anderseide** [comment]
Hi! I have the same issue!

Added the config you listed @mhoeger, but still hitting the firewall instead of corp proxy.
Seems like the settings does get picked up though, as I get an error message in the console when I had a typo the URL and used https instead of http

E0421 09:46:17.436000000 11992 http_proxy.cc:62] 'https' scheme not supported in proxy URI

**Comment by skergetd** [comment]
I had same issue. What I added was `0.0.0.0,127.0.0.1` to my ENV VAR of NO_PROXY, restarted VS Code and it worked.

**Comment by vimanmg** [comment]
It was resolved by applying @mhoeger 's recommendations. Thank you!
