### ISSUE TITLE
Error installing azure-functions-core-tools@3 on Fedora 31

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-functions-core-tools#1930]
When running `npm install -g azure-functions-core-tools@3`:

```
# npm install -g azure-functions-core-tools@3
/usr/bin/func -> /usr/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/bin/azfun -> /usr/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/bin/azurefunctions -> /usr/lib/node_modules/azure-functions-core-tools/lib/main.js

> azure-functions-core-tools@3.0.2245 postinstall /usr/lib/node_modules/azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/3.0.2245/Azure.Functions.Cli.linux-x64.3.0.2245.zip"
[------------------] Downloading Azure Functions Core Toolsevents.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/azure-functions-core-tools/bin'
Emitted 'error' event on DuplexWrapper instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at DuplexWrapper.onerror (_stream_readable.js:745:9)
    at DuplexWrapper.emit (events.js:315:20)
    at Readable.<anonymous> (/usr/lib/node_modules/azure-functions-core-tools/node_modules/duplexer2/index.js:49:12)
    at Readable.emit (events.js:315:20)
    at Writable.emit (events.js:327:22)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:406:3)
    at onwrite (_stream_writable.js:427:7)
    at ProxyWriter.emit (events.js:327:22)
    at FileWriter.emit (events.js:315:20)
    at FileWriter.Abstract.error (/usr/lib/node_modules/azure-functions-core-tools/node_modules/fstream/lib/abstract.js:63:13)
    at /usr/lib/node_modules/azure-functions-core-tools/node_modules/fstream/lib/writer.js:171:25
    at /usr/lib/node_modules/azure-functions-core-tools/node_modules/mkdirp/index.js:47:53
    at FSReqCallback.oncomplete (fs.js:171:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/azure-functions-core-tools/bin',
  fstream_type: 'File',
  fstream_path: '/usr/lib/node_modules/azure-functions-core-tools/bin/AccentedCommandLineParser.dll',
  fstream_class: 'FileWriter',
  fstream_stack: [
    '/usr/lib/node_modules/azure-functions-core-tools/node_modules/fstream/lib/writer.js:171:25',
    '/usr/lib/node_modules/azure-functions-core-tools/node_modules/mkdirp/index.js:47:53',
    'FSReqCallback.oncomplete (fs.js:171:21)'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@3.0.2245 postinstall: `node lib/install.js`
```

OS: Fedora 31
uname: `Linux localhost.localdomain 5.5.15-200.fc31.x86_64 #1 SMP Thu Apr 2 19:16:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

The directory `/usr/lib/node_modules` exists, and I (as root) have access to it.

**Comment by anthonychu** [comment]
Our recommended approach for installing on distros other than Debian and Ubuntu is to download and unzip the binaries themselves. Can you give that a try? https://github.com/Azure/azure-functions-core-tools#other-linux-distributions Thanks.
