### ISSUE TITLE
Unable to install azure-functions-core-tools

### ISSUE THREAD

**Issue by francischeung** [Azure/azure-functions-core-tools#1933]
I'm trying to install azure-functions-core-tools in vs code with the following configuration:

Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

I run the following command:
npm install -g azure-functions-core-tools

I then get the follow error message:
> node lib/install.js

C:\Users\...\AppData\Roaming\npm\node_modules\azure-functions-core-tools\node_modules\chalk\source\index.js:103
        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\fcheung\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:8:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by anthonychu** [comment]
Can you please check the version of npm and node you're running from the command line? Thanks.

```
node --version
npm --version
```

**Comment by francischeung** [comment]
PS C:\> node --version
v6.10.1
PS C:\> npm --version
6.14.4

**Comment by anthonychu** [comment]
Can you please update your Node version and try again? Looks like the `chalk` library that the Core Tools npm installer has a dependency on is using syntax that requires Node 8.3.0 and above.

On Windows, you can also use [Chocolatey](https://github.com/Azure/azure-functions-core-tools#windows), or download and run the new MSI installer [here](https://github.com/Azure/azure-functions-core-tools/releases).

**Comment by francischeung** [comment]
That fixed my issue. Thanks @anthonychu!
