### ISSUE TITLE
Can't create new function

### ISSUE THREAD

**Issue by lucasalexander** [Azure/azure-functions-core-tools#198]
I'm running Node 6.11.2 on Windows 10, and I've installed the azure-functions-core-tools@1.0.0-beta.100 package with _npm i -g azure-functions-core-tools._

I run _func init -n_ and get this output:
```
Writing .gitignore
Writing host.json
Writing local.settings.json
Created launch.json
```
When I run _func new_ I get this output:
```
Select a language: Object reference not set to an instance of an object.
```

If I pass more parameters to _func new_, I still get an object reference error at the end. Also, I'm not sure if this is related, but if I try to run _func azure account list_, after I login, I get this output in the CLI:
```
Value cannot be null.
Parameter name: source
```

**Comment by ahmelsayed** [comment]
can you set environment variable `CLI_DEBUG = 1` and then run again? You should get a full stack exception, it'll be helpful if you can share that.

**Comment by lucasalexander** [comment]
Here is the output when I execute _func new_:
```
Select a language: System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.<>c.<RunAsync>b__15_0(Template t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.DisplaySelectionWizard[T](IEnumerable`1 options)
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.<RunAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Functions.Cli.ConsoleApp.<RunAsync>d__5`1.MoveNext()
```

Here is the output I get after I authenticate when I execute _func azure login_:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at ARMClient.Authentication.AADAuthentication.BaseAuthHelper.<GetTenantIds>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ARMClient.Authentication.AADAuthentication.BaseAuthHelper.<GetTokenForTenants>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARMClient.Authentication.AADAuthentication.BaseAuthHelper.<AcquireTokens>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Functions.Cli.Actions.AzureActions.LoginAction.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Functions.Cli.ConsoleApp.<RunAsync>d__5`1.MoveNext()
```

**Comment by ahmelsayed** [comment]
regarding the first exception

I'm a bit puzzled by it. All the code is doing there is a simple GET to `https://functions.azure.com/api/templates?runtime=latest` and then groups them by language. I have no idea why it would work on one machine and not the other, unless you're unable to hit that endpoint for some reason. What do you get if you go to `https://functions.azure.com/api/templates?runtime=latest` in the browser from your machine? (WARNING: it's a pretty large JSON doc if it works correctly)

things to try to isolate the issue, can you run `func templates list`? or something more specific like `func template list --language C#`? You should get something like this 

```
C# Templates:
  $AppInsightsHttpAvailability_name
  $AppInsightsRealtimePowerBI_name
  $AppInsightsScheduledAnalytics_name
  $AppInsightsScheduledDigest_name
  BlobTrigger
  Cds WebHook
  CosmosDBTrigger
  EventGridTrigger
  EventHubTrigger
  ExternalFileTrigger
  ExternalTable
  FaceLocator
  Generic Webhook
  GitHub Commenter
  GitHub Webhook
  HttpGET(CRUD)
  HttpPOST(CRUD)
  HttpPUT(CRUD)
  HttpTrigger
  HttpTriggerWithParameters
  Image resize
  ManualTrigger
  MS Graph Email Webhook
  QueueTrigger
  SAS Token Generator
  ScheduledMail
  SendGrid
  ServiceBusQueueTrigger
  ServiceBusTopicTrigger
  TimerTrigger
  Refresh MS Graph Subscriptions
  Read, update Excel table & send O365 emails
```

**Comment by lucasalexander** [comment]
Thanks for the response. I can get to the JSON doc in my browser, but _func templates list_ still returns an error. Interestingly enough, trying to access that URL (or any other URL) with curl doesn't seem to be working for me either. It looks like this is a problem just on my end, so I'll close this issue now.

**Comment by ahmelsayed** [comment]
actually that might be my fault, can you try `curl -XGET https://functions.azure.com/api/templates?runtime=latest -I -H "User-Agent: Mozilla/"`? there is an artificial check for a user agent on the backend that I've been meaning to remove

**Comment by lucasalexander** [comment]
Thanks for following up. I tried with the updated request, but I'm still having issues getting curl to work on my machine for some reason.

**Comment by lucasalexander** [comment]
Once I downloaded a new version of curl, I was able to try the query you provided. It works, but trying to list the function templates with _func templates list_ still fails. I've attached a screenshot from the command line that shows both commands.

![cmd_2017-08-23_08-23-24](https://user-images.githubusercontent.com/95673/29618014-5cfb1ff4-87dc-11e7-9a3f-5930e3859d69.png)

**Comment by ahmedelnably** [comment]
Closing this, please reopen if it still the case in the latest version
