### ISSUE TITLE
permission denied when trying to install

### ISSUE THREAD

**Issue by KevinBuchs** [Azure/azure-functions-core-tools#2001]
Ubuntu 18.04. Running as root: 
```
$ sudo -Hi
# npm install -g azure-functions-core-tools
/usr/local/bin/func -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azfun -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azurefunctions -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js

> azure-functions-core-tools@2.7.2508 postinstall /usr/local/lib/node_modules/azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.2508/Azure.Functions.Cli.linux-x64.2.7.2508.zip"
[------------------] Downloading Azure Functions Core Toolsevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/azure-functions-core-tools/bin'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at DuplexWrapper.onerror (_stream_readable.js:734:7)
    at DuplexWrapper.emit (events.js:198:13)
    at Readable.<anonymous> (/usr/local/lib/node_modules/azure-functions-core-tools/node_modules/duplexer2/index.js:49:12)
    at Writable.emit (events.js:203:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at ProxyWriter.emit (events.js:203:15)
    at FileWriter.emit (events.js:198:13)
    at FileWriter.Abstract.error (/usr/local/lib/node_modules/azure-functions-core-tools/node_modules/fstream/lib/abstract.js:63:13)
    at /usr/local/lib/node_modules/azure-functions-core-tools/node_modules/fstream/lib/writer.js:171:25
    at /usr/local/lib/node_modules/azure-functions-core-tools/node_modules/mkdirp/index.js:48:53
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@2.7.2508 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@2.7.2508 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-21T14_26_41_113Z-debug.log
# mkdir -p /usr/local/lib/node_modules/azure-functions-core-tools/bin
# ls /usr/local/lib/node_modules/azure-functions-core-tools/
bin
# npm install -g azure-functions-core-tools
/usr/local/bin/func -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azfun -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js
/usr/local/bin/azurefunctions -> /usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js

> azure-functions-core-tools@2.7.2508 postinstall /usr/local/lib/node_modules/azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.2508/Azure.Functions.Cli.linux-x64.2.7.2508.zip"
[------------------] Downloading Azure Functions Core Toolsevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/azure-functions-core-tools/bin'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
...
```
Attaching log file from npm:

[2020-05-21T14_27_44_280Z-debug.log](https://github.com/Azure/azure-functions-core-tools/files/4663013/2020-05-21T14_27_44_280Z-debug.log)

**Comment by KevinBuchs** [comment]
And, of course it works to install locally, without the "-g".

**Comment by anthonychu** [comment]
As a workaround, can you please try creating the folder first at `/usr/local/lib/node_modules/azure-functions-core-tools/bin` and then run the npm install command again with `sudo`? Thanks.

**Comment by KevinBuchs** [comment]
Hi @anthonychu - if you read through my transcript carefully you will note that I already tried that. I was able to create the folder and yet the installer still failed. I was running this as root, so I have to believe the error message is bogus and it is really not a permissions issue.

**Comment by ankitkumarr** [comment]
@KevinBuchs,  can you try with `--unsafe-perm true` as our project readme suggests --
`npm i -g azure-functions-core-tools@2 --unsafe-perm true`?

**Comment by KevinBuchs** [comment]
Yes, that works. I didn't do that because the instructions displayed didn't say to, in the attached screen shot. 

It seems odd that a local install worked nestling everything under the node_modules/azure-functions-core-tools, but the global install has to do something more. Also, I would have to say requiring an option with the word "unsafe" is not very appealing. In fact, the option is not even documented here: https://docs.npmjs.com/cli/install . 

![Screenshot from 2020-05-26 16-58-07](https://user-images.githubusercontent.com/53194155/82956017-88015480-9f75-11ea-84c0-ae98d15ee5ce.png)
