### ISSUE TITLE
Gozip failed with Permission denied in DevContainer

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-core-tools#2048]
### Found in Python Durable Bug Bash

When developing Azure Functions in .devcontainer, runnning `func azure functionapp publish <appname>` results in
```
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
> /azure-functions-core-tools/gozip -base-dir "/workspaces/PythonDurableDev" -input-file "/tmp/tmpRNgB0W.tmp" -output "/tmp/tmpSGgRBE.tmp"
System.ComponentModel.Win32Exception (13): Permission denied
   at Azure.Functions.Cli.Common.Executable.RunAsync(Action`1 outputCallback, Action`1 errorCallback, Nullable`1 timeout, String stdIn) in D:\a\1\s\src\Azure.Functions.Cli\Common\Executable.cs:line 99
   at Azure.Functions.Cli.Helpers.ZipHelper.CreateGoZip(IEnumerable`1 files, String rootPath, String zipFilePath, String goZipLocation) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\ZipHelper.cs:line 107
   at Azure.Functions.Cli.Helpers.ZipHelper.CreateZip(IEnumerable`1 files, String rootPath) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\ZipHelper.cs:line 59
   at Azure.Functions.Cli.Helpers.PythonHelpers.GetPythonDeploymentPackage(IEnumerable`1 files, String functionAppRoot, Boolean buildNativeDeps, BuildOption buildOption, String additionalPackages) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\PythonHelpers.cs:line 343
   at Azure.Functions.Cli.Helpers.ZipHelper.GetAppZipFile(String functionAppRoot, Boolean buildNativeDeps, BuildOption buildOption, Boolean noBuild, GitIgnoreParser ignoreParser, String additionalPackages, Boolean ignoreDotNetCheck) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\ZipHelper.cs:line 37
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PerformServerSideBuild(Site functionApp, Func`1 zipFileFactory, Func`2 deploymentStatusPollTask) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 712
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.HandleLinuxConsumptionPublish(Site functionApp, Func`1 zipFileFactory) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 460
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 302
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 173
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

Maybe the gozip executable flag is not set? Or the container does not have dependencies that GoZip uses.

### /etc/os-release
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by ankitkumarr** [comment]
@Hazhzeng, do you have the Dockerfile for this image? How is core tools being installed there?

**Comment by anthonychu** [comment]
@ankitkumarr Could it be because func was installed as root but devcontainer runs as a different user? @Hazhzeng which devcontainer are you using?

**Comment by anthonychu** [comment]
Looks like this was using a devcontainer that I built and core tools was installed by unzipping so it was my bad. The shouldn't be a real problem that folks run into.
