### ISSUE TITLE
 Exception has occurred: ImportError: cannot import name 'cygrpc' from 'grpc.cython' 

### ISSUE THREAD

**Issue by gwsampso** [Azure/azure-functions-core-tools#2103]
New python azure function using this guide https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-01

Azure Functions Core Tools: (v3.0.2630 Commit hash: beec61496e1c5de8aa4ba38d1884f7b48233a7ab)
Function Runtime : v3.0.13901.0
VSCode: v1.47.2
NPM: v6.4.1
Node: v10.15.0

(.venv) > pip freeze
azure-functions==1.3.0

When I hit debug i'm faced with this error?

Exception has occurred: ImportError
cannot import name 'cygrpc' from 'grpc._cython' (C:\Users\user\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.7/WINDOWS/X64\grpc\_cython\__init__.py)
  File "c:\users\user\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.7\windows\x64\grpc\__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
  File "c:\users\user\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.7\windows\x64\azure_functions_worker\dispatcher.py", line 16, in <module>
    import grpc
  File "c:\users\user\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.7\windows\x64\azure_functions_worker\main.py", line 7, in <module>
    from . import dispatcher
  File "c:\users\user\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.7\windows\x64\worker.py", line 59, in <module>
    from azure_functions_worker import main

any thoughts please

**Comment by gwsampso** [comment]
using 32 bit version of python on widows

**Comment by AmberWilkie** [comment]
Also seeing this error and I'm on OSX. As far as I can tell, everything is doing 64bit.

```
[7/28/2020 6:46:22 PM] Traceback (most recent call last):
[7/28/2020 6:46:22 PM]   File "/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/python/3.6/OSX/X64/worker.py", line 59, in <module>
[7/28/2020 6:46:22 PM]     from azure_functions_worker import main
[7/28/2020 6:46:22 PM]   File "/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/python/3.6/OSX/X64/azure_functions_worker/main.py", line 7, in <module>
[7/28/2020 6:46:22 PM]     from . import dispatcher
[7/28/2020 6:46:22 PM]   File "/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/python/3.6/OSX/X64/azure_functions_worker/dispatcher.py", line 16, in <module>
[7/28/2020 6:46:22 PM]     import grpc
[7/28/2020 6:46:22 PM]   File "/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/python/3.6/OSX/X64/grpc/__init__.py", line 23, in <module>
[7/28/2020 6:46:22 PM]     from grpc._cython import cygrpc as _cygrpc
[7/28/2020 6:46:22 PM] ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/python/3.6/OSX/X64/grpc/_cython/__init__.py)
```

Running in python virtual env 3.7.3.

**Comment by anthonychu** [comment]
@Hazhzeng has been working on some troubleshooting guidance that will be available soon. Here's an excerpt:

> This is most likely caused by a 32-bit Python interpreter is installed on your 64-bit operating system.
>
> If you're running on an x64 operating system, please ensure your Python 3.6, 3.7, or 3.8 interpreter is also on 64-bit version.
> 
> You can check your Python interpreter bitness by the following commands:
> 
> On Windows in PowerShell: `py -c 'import platform; print(platform.architecture()[0])'`
> 
> On Unix-like shell: `python3 -c 'import platform; print(platform.architecture()[0])'`
> 
 > If there's a mismatch between Python interpreter bitness and operating system architecture, please download a proper Python interpreter from [Python Software Foundation](https://python.org/downloads/release).
