### ISSUE TITLE
Breakpoint debugging doesn't seem to work

### ISSUE THREAD

**Issue by aronchick** [Azure/azure-functions-core-tools#2126]
I just rebooted, so there shouldn't be any port conflict, but when I start a function in VS Code, I get the following error:
```
Http Functions:

        func-writer: [GET,POST] http://localhost:7071/api/func-writer

[07/31/2020 03:12:17] Traceback (most recent call last):
[07/31/2020 03:12:17]   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[07/31/2020 03:12:17]     return _run_code(code, main_globals, None,
[07/31/2020 03:12:17]   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[07/31/2020 03:12:17]     exec(code, run_globals)
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
[07/31/2020 03:12:17]     cli.main()
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
[07/31/2020 03:12:17]     run()
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 252, in run_file
[07/31/2020 03:12:17]     start_debugging(options.target)
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 241, in start_debugging
[07/31/2020 03:12:17]     debugpy.listen(options.address)
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/__init__.py", line 113, in listen
[07/31/2020 03:12:17]     return api.listen(address)
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 141, in debug
[07/31/2020 03:12:17]     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 139, in debug
[07/31/2020 03:12:17]     return func(address, settrace_kwargs, **kwargs)
[07/31/2020 03:12:17]   File "/home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 232, in listen
[07/31/2020 03:12:17]     raise RuntimeError(str(endpoints["error"]))
[07/31/2020 03:12:17] RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
[07/31/2020 03:12:17] Starting worker process:python3  /home/dave/.vscode-server/extensions/ms-python.python-2020.7.96456/pythonFiles/lib/python/debugpy --listen 127.0.0.1:9091 --wait-for-client "/usr/lib/azure-functions-core-tools-3/workers/python/3.8/LINUX/X64/worker.py" --host 127.0.0.1 --port 43035 --workerId 2c0b7c7a-d1f7-4351-8ad4-b1d052fdcfd9 --requestId 5b164889-c1c1-48a3-8ecb-ec5dd1de4e6c --grpcMaxMessageLength 2147483647
[07/31/2020 03:12:17] python3 process with Id=26583 started
[07/31/2020 03:12:18] Traceback (most recent call last):
```

I can't figure it out. Here's my launch.json

```
        {
            "name": "Attach to Python Functions",
            "type": "python",
            "request": "attach",
            "port": 9091,
            "preLaunchTask": "func: host start"
        }

```

and my host.json
```
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "pipInstall",
      "options": {
        "cwd": "${workspaceFolder}/func-writer-app"
      }
    },

```

Every thing else is default, other than this is a function running in a pipenv (so the function has fewer python package requirements than the environment has installed, but i can't figure out how that'd be a problem).

Oh, if i run on a non-standard debug port (e.g. 9092) it works, but breakpoints don't attach.

**Comment by aronchick** [comment]
Ok, this KIND of looks like these from Azure functions - https://github.com/microsoft/vscode-azurefunctions/issues/892 - I followed the advice and ran the below:
```
lsof -nP -i4TCP:9091 | grep LISTEN
```

I detected python3 was still listening on that port.

Now I've killed it and it at least lets me run debugging, BUT VSCode doesn't seem to attach breakpoints. What happens now is I start the "Attach to Process" in one VSCode terminal, and then in a second VSCode terminal I curl the endpoint with the appropriate data.

It stops where I'd expect the breakpoint to be, but VSCode doesn't highlight the breakpoint. Next thoughts?

**Comment by aronchick** [comment]
This may be something for @EricJizbaMSFT

**Comment by aronchick** [comment]
Changing the title - the system APPEARS to breakpoint, but VSCode does not appear to be listening to it.

doing 
```
 lsof -nP -i4TCP:9091 | grep LISTEN    
```

And then `kill -1` the process ID allowed me to find the orphaned process that prevented the original startup, but the system still isn't working properly.

**Comment by aronchick** [comment]
K, solved this problem.

Turns out in `.vscode/settings.json`, `"azureFunctions.deploySubpath"` was pointing at the wrong location.

**Comment by EricJizbaMSFT** [comment]
If you're still having problems, I'd suggest filing an issue here with consistent repro steps: https://github.com/microsoft/vscode-azurefunctions/issues/new

It's a bit hard to tell what the exact repro steps are when it seems like you're trying a bunch of different stuff haha. Also, the "deploySubpath" should have no affect on debugging...

**Comment by aronchick** [comment]
Yeah, closing. It still doesn't work (loses connection after a while), but not sure how to repro.
