### ISSUE TITLE
error deploying python function for the first time

### ISSUE THREAD

**Issue by szaher** [Azure/azure-functions-core-tools#2205]
Publishing azure function failed to sync triggers. not sure what is the error exactly but have seen this multiple times when trying to push the python function for the first time.

/bin/func-v3 azure functionapp publish PYTHONFNT --build-native-deps --python
{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}
Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest). Request ID = '29d69a64-6593-4e4d-af17-87cdc973d812'.
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 29
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 358
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 349
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 173
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66

**Comment by szaher** [comment]
Syncing triggers...
Request:
Method: POST, RequestUri: 'https://management.azure.com/subscriptions/4dcf7d10-ddbe-xxxx-xyxyx-db3ee483920wx/resourceGroups/python-RGP/providers/Microsoft.Web/sites/pythonfnt/host/default/sync?api-version=2015-08-01', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJ....Kr_oQKn8aNrUCCg
  User-Agent: functions-core-tools/3.0.2630
  Accept: application/json
  x-ms-request-id: 317a6f14-xyxy-yyy-xxxx-adbb85f45cdf
  Content-Type: application/json; charset=utf-8
}
null
Response:
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Server: Microsoft-IIS/10.0
  X-AspNet-Version: 4.0.30319
  X-Powered-By: ASP.NET
  x-ms-ratelimit-remaining-subscription-writes: 1191
  x-ms-request-id: 4241xxb724cd03xxx6fa
  x-ms-correlation-request-id: 4241f1xxe-96e9-b72xx03d6fa
  x-ms-routing-request-id: WESTEUROPE:202xxx0ee-96e9-xx24cdxxd6fa
  X-Content-Type-Options: nosniff
  Date: Sun, 06 Sep 2020 03:34:49 GMT
  Content-Length: 346
  Content-Type: application/json; charset=utf-8
  Expires: -1
}
{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}

**Comment by apawast** [comment]
@Hazhzeng could you please take a look at this?

**Comment by apawast** [comment]
@Hazhzeng @vrdmr can one of you please take a look at this?

**Comment by Hazhzeng** [comment]
This looks like an issue where the app settings are not properly set when starting the function app. I checked our frontend on the date 09/06/2020 and I don't see any request going to the site pythonfnt.
Could you check if the pythonfnt site is up and running when you deploy your function app?
