### ISSUE TITLE
azure-functions-core-tools @v3 broken on Mac - Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by vikramkamath** [Azure/azure-functions-core-tools#2267]
Environment:
Mac OS Catalina 10.15.7
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
JDK 11 and 8 installed

Consistently happens when running with IntelliJ, VSCode or terminal

```
INFO] --- azure-functions-maven-plugin:1.4.1:run (default-cli) @ tda-api ---
[WARNING] Azure Functions only support JDK 8, which is lower than local JDK version 11.0.8.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields (file:/Users/kamatv/.m2/repository/com/microsoft/azure/applicationinsights-core/2.5.1/applicationinsights-core-2.5.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Azure Function App's staging directory found at: /Users/kamatv/azure-apps/test-data-automation/tda-api/target/azure-functions/tda
[INFO] Azure Functions Core Tools found.
System.Exception: Cannot find the Local Application Data.
   at Azure.Functions.Cli.Utilities.EnsureCoreToolsLocalData() in D:\a\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 177
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.VerifyOrSetDefaultStorageDirectoryPath(String desireStorageDirectoryPath) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 96
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.Init(String storageDirectoryPath) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 78
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.PersistenceChannel..ctor(String storageDirectoryPath, Int32 sendersCount) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\PersistenceChannel.cs:line 42
   at Azure.Functions.Cli.Telemetry.Telemetry.InitializeTelemetry() in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\Telemetry.cs:line 93
Azure Functions Core Tools (3.0.2931 Commit hash: d552c6741a37422684f0efab41d541ebad2b2bd2)
Function Runtime Version: 3.0.14492.0
Setting unsupported .NET environemt variables (empty string) is not implemented for this platform.
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 275
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
Application is shutting down...
```
This keeps happening intermittently.
Could be related to https://github.com/Azure/azure-functions-core-tools/issues/1447

**Comment by anthonychu** [comment]
@vikramkamath Can you please confirm if intermittently means that when you run it once it's fine, but the next time it's run without making any changes, it fails? Could you also share your local.settings.json file (minus secrets)? Thanks.
