### ISSUE TITLE
Value cannot be null. Parameter 'connectionString' (though we set AzureWebJobsStorage) 

### ISSUE THREAD

**Issue by mygithubkas** [Azure/azure-functions-core-tools#2421]
We have a DevOps pipeline to deploy an Azure Function in a container.
The build is successful but the container reports the error shown above.

The container is actually located under Home/Container Instances.
Should Function App containers be at this location ?
If not, this might explain why the container failed to see the AzureWebJobsStorage setting in the Function App.

Perhaps the 'name' should be 'connectionString' instead of AzureWebJobsStorage ? 

Cheers

**Comment by apawast** [comment]
@mygithubkas could you please share your stack and repro steps with us?

**Comment by mygithubkas** [comment]
> @mygithubkas could you please share your stack and repro steps with us?

sure:

```
[40m[32minfo[39m[22m[49m: Host.Triggers.Warmup[0]
      Initializing Warmup Extension.
[40m[32minfo[39m[22m[49m: Host.Startup[503]
      Initializing Host. OperationId: 'f38f8167-3aa1-47e2-a33b-8a6dbeb80ec9'.
[40m[32minfo[39m[22m[49m: Host.Startup[504]
      Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=f38f8167-3aa1-47e2-a33b-8a6dbeb80ec9
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      LoggerFilterOptions
      {
        "MinLevel": "None",
        "Rules": [
          {
            "ProviderName": null,
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": "None",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          }
        ]
      }
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      FunctionResultAggregatorOptions
      {
        "BatchSize": 1000,
        "FlushTimeout": "00:00:30",
        "IsEnabled": true
      }
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      SingletonOptions
      {
        "LockPeriod": "00:00:15",
        "ListenerLockPeriod": "00:01:00",
        "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
        "LockAcquisitionPollingInterval": "00:00:05",
        "ListenerLockRecoveryPollingInterval": "00:01:00"
      }
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      HttpOptions
      {
        "DynamicThrottlesEnabled": false,
        "MaxConcurrentRequests": -1,
        "MaxOutstandingRequests": -1,
        "RoutePrefix": "api"
      }
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
[40m[32minfo[39m[22m[49m: Host.Startup[401]
      Starting Host (HostId=wkcaas914c35346614487d96427f5d0d, InstanceId=d12fbef9-30d8-4ad4-a351-66b6a3992926, Version=3.0.15277.0, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[40m[32minfo[39m[22m[49m: Host.Startup[314]
      Loading functions metadata
[40m[32minfo[39m[22m[49m: Host.Startup[315]
      1 functions loaded
[40m[32minfo[39m[22m[49m: Host.Startup[0]
      Generating 1 job function(s)
[40m[32minfo[39m[22m[49m: Host.Startup[0]
      Found the following functions:
      Host.Functions.mytrigger
      
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]
      Initializing function HTTP routes
      No HTTP routes mapped
      
[40m[32minfo[39m[22m[49m: Host.Startup[412]
      Host initialized (183ms)
[41m[30mfail[39m[22m[49m: Host.Startup[0]
      The listener for function 'Functions.mytrigger' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'Functions.mytrigger' was unable to start.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.Azure.Storage.CloudStorageAccount.Parse(String connectionString)
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.get_TimerStatusDirectory() in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions\Extensions\Timers\Scheduling\StorageScheduleMonitor.cs:line 77
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.GetStatusBlobReference(String timerName) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions\Extensions\Timers\Scheduling\StorageScheduleMonitor.cs:line 144
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.GetStatusAsync(String timerName)
   at Microsoft.Azure.WebJobs.Extensions.Timers.Listeners.TimerListener.StartAsync(CancellationToken cancellationToken) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions\Extensions\Timers\Listener\TimerListener.cs:line 99
   at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Singleton\SingletonListener.cs:line 72
   at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 69
   --- End of inner exception stack trace ---
[40m[32minfo[39m[22m[49m: Host.Startup[413]
      Host started (283ms)
[40m[32minfo[39m[22m[49m: Host.Startup[0]
      Job host started
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Worker process started and initialized.
[40m[32minfo[39m[22m[49m: Host.Startup[0]
      Retrying to start listener for function 'Functions.mytrigger' (Attempt 1)
[40m[32minfo[39m[22m[49m: Host.Startup[0]
      Listener successfully started for function 'Functions.mytrigger' after 1 retries.
[40m[32minfo[39m[22m[49m: Host.General[316]
      Host lock lease acquired by instance ID '00000000000000000000000021C41FE8'.
```

**Comment by sunit82** [comment]
I too have the same issue. though i'm not deploying using a build, but doing it manually using VS2019.
The timer trigger AzFunction works well locally and is triggered as per CRON expression. but on deployed version i get the error as mentioned in the title of this issue.
"The listener for function 'xyz' was unable to start. Value cannot be null. (Parameter 'connectionString')"
any solution for this?

**Comment by apawast** [comment]
@mygithubkas apologies for the late response. Are you still experiencing this issue?

**Comment by michaelpeng36** [comment]
@MBKraus could you clarify whether using Core Tools or the Az CLI works fine? Also, @mygithubkas, could you verify if you have an app setting called `connectionString`?
