### ISSUE TITLE
Can't run nodejs Azure Functions on MacOs with M1

### ISSUE THREAD

**Issue by joelvarty** [Azure/azure-functions-core-tools#2431]
Trying to get an azure function project running on an M1 Macbook Pro.

I think the main issue is this - any ideas for a workaround?

```
Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:29.923Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:29.923Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:29.923Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
```

Full command output below:

```
func start --verbose

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       3.0.3233 Commit hash: d1772f733802122a326fa696dd4c086292ec0171 
Function Runtime Version: 3.0.15193.0

[2021-02-07T18:11:27.961Z] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '8dd16de4-64f9-408e-9363-ff1fda06bb23'
[2021-02-07T18:11:28.010Z] Reading host configuration file '/Users/joelvarty/Documents/Dev/microsoft/azurefunctiontests/host.json'
[2021-02-07T18:11:28.013Z] Host configuration file read:
[2021-02-07T18:11:28.013Z] {
[2021-02-07T18:11:28.013Z]   "version": "2.0",
[2021-02-07T18:11:28.013Z]   "logging": {
[2021-02-07T18:11:28.013Z]     "applicationInsights": {
[2021-02-07T18:11:28.013Z]       "samplingSettings": {
[2021-02-07T18:11:28.013Z]         "isEnabled": true,
[2021-02-07T18:11:28.013Z]         "excludedTypes": "Request"
[2021-02-07T18:11:28.013Z]       }
[2021-02-07T18:11:28.013Z]     }
[2021-02-07T18:11:28.013Z]   },
[2021-02-07T18:11:28.013Z]   "extensionBundle": {
[2021-02-07T18:11:28.013Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-02-07T18:11:28.013Z]     "version": "[1.*, 2.0.0)"
[2021-02-07T18:11:28.013Z]   }
[2021-02-07T18:11:28.013Z] }
[2021-02-07T18:11:28.049Z] Loading functions metadata
[2021-02-07T18:11:28.085Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2021-02-07T18:11:28.092Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2021-02-07T18:11:28.094Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2021-02-07T18:11:28.113Z] Reading functions metadata
[2021-02-07T18:11:28.135Z] 1 functions found
[2021-02-07T18:11:28.149Z] 1 functions loaded
[2021-02-07T18:11:28.158Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2021-02-07T18:11:28.163Z] Found a matching extension bundle at /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.5.1
[2021-02-07T18:11:28.165Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2021-02-07T18:11:28.368Z] Skipping bundle download since it already exists at path /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.5.1
[2021-02-07T18:11:28.382Z] Loading extension bundle from /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.5.1/bin
[2021-02-07T18:11:28.397Z] Reading host configuration file '/Users/joelvarty/Documents/Dev/microsoft/azurefunctiontests/host.json'
[2021-02-07T18:11:28.397Z] Host configuration file read:
[2021-02-07T18:11:28.397Z] {
[2021-02-07T18:11:28.397Z]   "version": "2.0",
[2021-02-07T18:11:28.397Z]   "logging": {
[2021-02-07T18:11:28.397Z]     "applicationInsights": {
[2021-02-07T18:11:28.397Z]       "samplingSettings": {
[2021-02-07T18:11:28.403Z]         "isEnabled": true,
[2021-02-07T18:11:28.403Z]         "excludedTypes": "Request"
[2021-02-07T18:11:28.403Z]       }
[2021-02-07T18:11:28.403Z]     }
[2021-02-07T18:11:28.403Z]   },
[2021-02-07T18:11:28.403Z]   "extensionBundle": {
[2021-02-07T18:11:28.403Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-02-07T18:11:28.403Z]     "version": "[1.*, 2.0.0)"
[2021-02-07T18:11:28.403Z]   }
[2021-02-07T18:11:28.403Z] }
[2021-02-07T18:11:28.782Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2021-02-07T18:11:28.784Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2021-02-07T18:11:28.784Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2021-02-07T18:11:28.909Z] Initializing Warmup Extension.
[2021-02-07T18:11:28.987Z] Initializing Host. OperationId: '8dd16de4-64f9-408e-9363-ff1fda06bb23'.
[2021-02-07T18:11:28.995Z] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=8dd16de4-64f9-408e-9363-ff1fda06bb23
[2021-02-07T18:11:29.020Z] LoggerFilterOptions
[2021-02-07T18:11:29.020Z] {
[2021-02-07T18:11:29.020Z]   "MinLevel": "None",
[2021-02-07T18:11:29.020Z]   "Rules": [
[2021-02-07T18:11:29.020Z]     {
[2021-02-07T18:11:29.020Z]       "ProviderName": null,
[2021-02-07T18:11:29.020Z]       "CategoryName": null,
[2021-02-07T18:11:29.020Z]       "LogLevel": null,
[2021-02-07T18:11:29.020Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.021Z]     },
[2021-02-07T18:11:29.021Z]     {
[2021-02-07T18:11:29.021Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.021Z]       "CategoryName": null,
[2021-02-07T18:11:29.021Z]       "LogLevel": "None",
[2021-02-07T18:11:29.021Z]       "Filter": null
[2021-02-07T18:11:29.021Z]     },
[2021-02-07T18:11:29.021Z]     {
[2021-02-07T18:11:29.021Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.021Z]       "CategoryName": null,
[2021-02-07T18:11:29.021Z]       "LogLevel": null,
[2021-02-07T18:11:29.021Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.021Z]     },
[2021-02-07T18:11:29.021Z]     {
[2021-02-07T18:11:29.021Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2021-02-07T18:11:29.021Z]       "CategoryName": null,
[2021-02-07T18:11:29.021Z]       "LogLevel": null,
[2021-02-07T18:11:29.021Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.021Z]     }
[2021-02-07T18:11:29.021Z]   ]
[2021-02-07T18:11:29.021Z] }
[2021-02-07T18:11:29.022Z] LoggerFilterOptions
[2021-02-07T18:11:29.022Z] {
[2021-02-07T18:11:29.022Z]   "MinLevel": "None",
[2021-02-07T18:11:29.022Z]   "Rules": [
[2021-02-07T18:11:29.022Z]     {
[2021-02-07T18:11:29.022Z]       "ProviderName": null,
[2021-02-07T18:11:29.022Z]       "CategoryName": null,
[2021-02-07T18:11:29.022Z]       "LogLevel": null,
[2021-02-07T18:11:29.025Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.025Z]     },
[2021-02-07T18:11:29.025Z]     {
[2021-02-07T18:11:29.025Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.025Z]       "CategoryName": null,
[2021-02-07T18:11:29.025Z]       "LogLevel": "None",
[2021-02-07T18:11:29.025Z]       "Filter": null
[2021-02-07T18:11:29.025Z]     },
[2021-02-07T18:11:29.025Z]     {
[2021-02-07T18:11:29.025Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.025Z]       "CategoryName": null,
[2021-02-07T18:11:29.025Z]       "LogLevel": null,
[2021-02-07T18:11:29.025Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.025Z]     },
[2021-02-07T18:11:29.025Z]     {
[2021-02-07T18:11:29.025Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2021-02-07T18:11:29.025Z]       "CategoryName": null,
[2021-02-07T18:11:29.026Z]       "LogLevel": null,
[2021-02-07T18:11:29.026Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.026Z]     }
[2021-02-07T18:11:29.026Z]   ]
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.026Z] FunctionResultAggregatorOptions
[2021-02-07T18:11:29.026Z] {
[2021-02-07T18:11:29.026Z]   "BatchSize": 1000,
[2021-02-07T18:11:29.026Z]   "FlushTimeout": "00:00:30",
[2021-02-07T18:11:29.026Z]   "IsEnabled": true
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.026Z] SingletonOptions
[2021-02-07T18:11:29.026Z] {
[2021-02-07T18:11:29.026Z]   "LockPeriod": "00:00:15",
[2021-02-07T18:11:29.026Z]   "ListenerLockPeriod": "00:00:15",
[2021-02-07T18:11:29.026Z]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2021-02-07T18:11:29.026Z]   "LockAcquisitionPollingInterval": "00:00:05",
[2021-02-07T18:11:29.026Z]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.026Z] HttpOptions
[2021-02-07T18:11:29.026Z] {
[2021-02-07T18:11:29.026Z]   "DynamicThrottlesEnabled": false,
[2021-02-07T18:11:29.026Z]   "MaxConcurrentRequests": -1,
[2021-02-07T18:11:29.026Z]   "MaxOutstandingRequests": -1,
[2021-02-07T18:11:29.026Z]   "RoutePrefix": "api"
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.028Z] Starting JobHost
[2021-02-07T18:11:29.034Z] Starting Host (HostId=macbookpro-1282054074, InstanceId=e0e35781-d3a1-427c-a726-fc8fa5f37c83, Version=3.0.15193.0, ProcessId=28989, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2021-02-07T18:11:29.054Z] Loading functions metadata
[2021-02-07T18:11:29.060Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2021-02-07T18:11:29.061Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2021-02-07T18:11:29.061Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2021-02-07T18:11:29.074Z] Loading proxies metadata
[2021-02-07T18:11:29.080Z] Initializing Azure Function proxies
[2021-02-07T18:11:29.485Z] 0 proxies loaded
[2021-02-07T18:11:29.508Z] 1 functions loaded
[2021-02-07T18:11:29.669Z] Generating 1 job function(s)
[2021-02-07T18:11:29.764Z] Found the following functions:
[2021-02-07T18:11:29.764Z] Host.Functions.test
[2021-02-07T18:11:29.764Z] 
[2021-02-07T18:11:29.806Z] Initializing function HTTP routes
[2021-02-07T18:11:29.806Z] Mapped function route 'api/test' [get,post] to 'test'
[2021-02-07T18:11:29.806Z] 
[2021-02-07T18:11:29.819Z] Host initialized (770ms)
[2021-02-07T18:11:29.828Z] Host started (791ms)
[2021-02-07T18:11:29.828Z] Job host started
[2021-02-07T18:11:29.860Z] internal/modules/cjs/loader.js:818
[2021-02-07T18:11:29.860Z]   throw err;
[2021-02-07T18:11:29.860Z]   ^
[2021-02-07T18:11:29.862Z] Error: Cannot find module './Worker.js'
[2021-02-07T18:11:29.864Z] Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:29.864Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:29.865Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:29.866Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
[2021-02-07T18:11:29.866Z] Require stack:
[2021-02-07T18:11:29.866Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/worker-bundle.js
[2021-02-07T18:11:29.866Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.866Z] Require stack:
[2021-02-07T18:11:29.866Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.866Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[2021-02-07T18:11:29.866Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2021-02-07T18:11:29.866Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-02-07T18:11:29.866Z]     at require (internal/modules/cjs/helpers.js:74:18)
[2021-02-07T18:11:29.866Z]     at Object.<anonymous> (/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js:45:14)
[2021-02-07T18:11:29.866Z]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-02-07T18:11:29.866Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-02-07T18:11:29.867Z]     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-02-07T18:11:29.867Z]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-02-07T18:11:29.867Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
[2021-02-07T18:11:29.867Z]   code: 'MODULE_NOT_FOUND',
[2021-02-07T18:11:29.867Z]   requireStack: [
[2021-02-07T18:11:29.867Z]     '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js'
[2021-02-07T18:11:29.867Z]   ]
[2021-02-07T18:11:29.867Z] }
[2021-02-07T18:11:29.922Z] Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:29.923Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:29.923Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:29.923Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
[2021-02-07T18:11:29.923Z] Require stack:
[2021-02-07T18:11:29.923Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/worker-bundle.js
[2021-02-07T18:11:29.923Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.923Z] internal/modules/cjs/loader.js:818
[2021-02-07T18:11:29.923Z]   throw err;
[2021-02-07T18:11:29.923Z]   ^
[2021-02-07T18:11:29.923Z] Error: Cannot find module './Worker.js'
[2021-02-07T18:11:29.923Z] Require stack:
[2021-02-07T18:11:29.923Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.924Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[2021-02-07T18:11:29.924Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2021-02-07T18:11:29.925Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-02-07T18:11:29.925Z]     at require (internal/modules/cjs/helpers.js:74:18)
[2021-02-07T18:11:29.925Z]     at Object.<anonymous> (/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js:45:14)
[2021-02-07T18:11:29.964Z]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-02-07T18:11:29.965Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-02-07T18:11:29.965Z]     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-02-07T18:11:29.965Z]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-02-07T18:11:29.965Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
[2021-02-07T18:11:29.965Z]   code: 'MODULE_NOT_FOUND',
[2021-02-07T18:11:29.965Z]   requireStack: [
[2021-02-07T18:11:29.965Z]     '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js'
[2021-02-07T18:11:29.965Z]   ]
[2021-02-07T18:11:29.965Z] }
[2021-02-07T18:11:30.013Z] Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:30.014Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:30.014Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:30.014Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
[2021-02-07T18:11:30.014Z] Require stack:
[2021-02-07T18:11:30.014Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/worker-bundle.js
[2021-02-07T18:11:30.014Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:30.014Z] internal/modules/cjs/loader.js:818
[2021-02-07T18:11:30.014Z]   throw err;
[2021-02-07T18:11:30.014Z]   ^
[2021-02-07T18:11:30.014Z] Error: Cannot find module './Worker.js'
[2021-02-07T18:11:30.014Z] Require stack:
[2021-02-07T18:11:30.014Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:30.014Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[2021-02-07T18:11:30.014Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2021-02-07T18:11:30.014Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-02-07T18:11:30.015Z]     at require (internal/modules/cjs/helpers.js:74:18)
[2021-02-07T18:11:30.015Z]     at Object.<anonymous> (/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js:45:14)
[2021-02-07T18:11:30.015Z]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-02-07T18:11:30.015Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-02-07T18:11:30.015Z]     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-02-07T18:11:30.015Z]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-02-07T18:11:30.015Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
[2021-02-07T18:11:30.015Z]   code: 'MODULE_NOT_FOUND',
[2021-02-07T18:11:30.015Z]   requireStack: [
[2021-02-07T18:11:30.015Z]     '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js'
[2021-02-07T18:11:30.018Z]   ]
[2021-02-07T18:11:30.018Z] }
[2021-02-07T18:11:30.020Z] Exceeded language worker restart retry count for runtime:node. Shutting down and proactively recycling the Functions Host to recover

Functions:

        test: [GET,POST] http://localhost:7071/api/test

[2021-02-07T18:11:30.169Z] Stopping host...
[2021-02-07T18:11:30.186Z] Stopping JobHost
[2021-02-07T18:11:30.205Z] Job host stopped
[2021-02-07T18:11:30.229Z] Host shutdown completed.
```

**Comment by apawast** [comment]
@mhoeger and @alrod it looks like we're missing the grpc binaries for the M1 Macbook Pro. What do you think we should do?

**Comment by mhoeger** [comment]
We currently don't support ARM-based systems regardless of OS. Likely need to target_arch of `arm64` in generating our deployment bundles (I would say for node 10 - 14, no need to support for functions v2 / node 8): https://github.com/Azure/azure-functions-nodejs-worker/blob/aa967888f5d7e983e8aa2889863bf5031975a752/package.ps1#L34

@alrod - should look into how much this would increase our package size as well. Thanks!

**Comment by joelvarty** [comment]
I've worked around this by installing node 10 in a Rosetta 2 Terminal session with nvm.  Interestingly, now as long as I run `nvm use 10` my function app runs perfectly, even in a regular VS Code terminal.

**Comment by kitazaki** [comment]
I've had same situation.
Following workaround works fine for me.

% npm init -y
% npm install grpc
% ln -s `pwd`/node_modules/grpc/src/node/extension_binary/node-v83-darwin-arm64-unknown  /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3284/workers/node/grpc/src/node/extension_binary
