### ISSUE TITLE
`func init` and `func start` are failed in WSL2

### ISSUE THREAD

**Issue by yuyamashiro** [Azure/azure-functions-core-tools#2443]
`func init` failed in WSL2

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/azure-functions-core-tools/bin/func ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/local/lib/node_modules/azure-functions-core-tools/bin/func',
  path: '/usr/local/lib/node_modules/azure-functions-core-tools/bin/func',
  spawnargs: [ 'init' ]
}
```

**Comment by apawast** [comment]
@yuyamashiro what version of node and what distribution of linux are you using?

**Comment by yuyamashiro** [comment]
@apawast 
Sorry for the lack of information.
```
WSL distribution:
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
```

```
> node -v
v14.15.4
```

**Comment by Tohaker** [comment]
I had this problem too, turns out the `install.sh` script wasn't running upon `npm install`. This was in VSCode DevContainer however (but same principle)

**Comment by apawast** [comment]
@yuyamashiro are you still experiencing this issue?
