### ISSUE TITLE
Functions fail on Fedora 33 with system-installed binaries

### ISSUE THREAD

**Issue by GeeWee** [Azure/azure-functions-core-tools#2470]
Hey y'all. I'm getting issues similar to #421 with the latest version of the function core tools on Fedora 33.

Output:
```
CLI_DEBUG=1 func start                                                                                                                                                        dotnet build --output bin/output 
System.ComponentModel.Win32Exception (2): No such file or directory
   at Azure.Functions.Cli.Common.Executable.RunAsync(Action`1 outputCallback, Action`1 errorCallback, Nullable`1 timeout, String stdIn) in D:\a\1\s\src\Azure.Functions.Cli\Common\Executable.cs:line 99
   at Azure.Functions.Cli.Helpers.DotnetHelpers.BuildDotnetProject(String outputPath, String dotnetCliParams, Boolean showOutput) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\DotnetHelpers.cs:line 125
   at Azure.Functions.Cli.Helpers.DotnetHelpers.BuildAndChangeDirectory(String outputPath, String cliParams) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\DotnetHelpers.cs:line 110
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.PreRunConditions() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 336
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 271
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

However if I run the same dotnet command it runs without any issues:
```
dotnet build --output bin/output                                                                                                                                              Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 28.39 ms for /home/geewee/programming/aip/BulkDataSimulator/BulkDataSimulator/BulkDataSimulator.csproj.
  Restore completed in 28.39 ms for /home/geewee/programming/aip/Shared/Shared/Shared.csproj.
  Shared -> /home/geewee/programming/aip/BulkDataSimulator/BulkDataSimulator/bin/output/Shared.dll
  BulkDataSimulator -> /home/geewee/programming/aip/BulkDataSimulator/BulkDataSimulator/bin/output/BulkDataSimulator.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.76
```

I have a sneaking suspicion this is because if you install the repo-distributed packages of dotnet they are installed in `/usr/lib64/dotnet` and then I have them symlinked into `/usr/bin/`

**func version: 3.0.3284**
I have installed them by downloading the binaries, extracting them and adding them to path.

**Comment by apawast** [comment]
@GeeWee for now to mitigate this issue, you could run `dotnet build --output bin/output ` then `cd bin/output` then `func start` because func start will skip the build.

**Comment by GeeWee** [comment]
Thanks! I did manage to get another workaround to work. This issue is quite likely related to https://github.com/dotnet/efcore/issues/16071 as the issue in my case was also fixed by setting dotnet_root and removing a bad symlink.
