### ISSUE TITLE
Cannot Access a Disposed Object: IServiceProvider

### ISSUE THREAD

**Issue by phantomcosmonaut** [Azure/azure-functions-core-tools#2471]
I run an azure function locally using AzureFunctionTools cli_x64 v3.20.0 with dotnet core 3.1 runtime and I noticed that when I modify my local.settings.json file I get the disposed object error.
works:
```
"Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": false
  }
```
fails:
```
"Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": true
  }
```
seems directly related to [this issue](https://github.com/Azure/azure-functions-core-tools/issues/1903)

**Comment by apawast** [comment]
Hi @phantomcosmonaut can you run again by setting the env variable CLI_DEBUG=1 and sharing the output with us?

**Comment by phantomcosmonaut** [comment]
@apawast Here's the debug output
>System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 291
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
Press any to continue....

**Comment by kvinther** [comment]
I just ran into the exact same issue and thus found this issue. My debug output is identical.
