### ISSUE TITLE
Can't update core tools

### ISSUE THREAD

**Issue by MJECloud** [Azure/azure-functions-core-tools#2526]
Hi, 

i can't update the core tools because the module 'unzipper' is not found. 
Got the error when using the VSCode Command or running it in the terminal. 

![image](https://user-images.githubusercontent.com/22131101/112804026-3386a400-9074-11eb-9012-5ea48153486a.png)

```
npm i -g azure-functions-core-tools@3 --unsafe-perm true
npm ERR! code 1
npm ERR! path C:\Users\mje\AppData\Roaming\npm\node_modules\azure-functions-core-tools
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! node:internal/modules/cjs/loader:927
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'unzipper'
npm ERR! Require stack:
npm ERR! - C:\Users\mje\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (C:\Users\mje\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:3:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:972:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\mje\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\lib\\install.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mje\AppData\Local\npm-cache\_logs\2021-03-29T07_41_54_784Z-debug.log
```

**Comment by apawast** [comment]
@MJECloud can you please run `npm i -g azure-functions-core-tools@3 --unsafe-perm true --verbose` and share the output?

**Comment by MJECloud** [comment]
Sure :) 
Here is the output

```
npm i -g azure-functions-core-tools@3 --unsafe-perm true --verbose
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '-g',
npm verb cli   'azure-functions-core-tools@3',
npm verb cli   '--unsafe-perm',
npm verb cli   'true',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.6.3
npm info using node@v15.12.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:C:\Users\mje\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\mje\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 7ms
npm verb npm-session c04da558ac6da591
npm timing npm:load Completed in 18ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 7ms
npm timing idealTree:userRequests Completed in 4ms
npm http fetch GET 304 https://registry.npmjs.org/azure-functions-core-tools 244ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chalk 59ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/command-exists 144ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 149ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tmp 151ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/progress 158ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob 165ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/unzipper 165ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rimraf 173ms (from cache)
npm timing idealTree:#root Completed in 430ms
npm timing idealTree:buildDeps Completed in 432ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 445ms
npm timing reify:loadTrees Completed in 479ms
npm timing reify:diffTrees Completed in 6ms
npm timing reify:retireShallow Completed in 7ms
npm timing reify:createSparse Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/azure-functions-core-tools Completed in 15ms
npm timing reify:unpack Completed in 16ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 2ms
npm timing build:link:node_modules/azure-functions-core-tools Completed in 5ms
npm timing build:link Completed in 6ms
npm info run azure-functions-core-tools@3.0.3388 postinstall node_modules/azure-functions-core-tools node lib/install.js
npm info run azure-functions-core-tools@3.0.3388 postinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 3ms
npm timing reify:rollback:retireShallow Completed in 4ms
npm timing command:i Completed in 588ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:369:20)
npm verb stack     at maybeClose (node:internal/child_process:1067:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid azure-functions-core-tools@3.0.3388
npm verb cwd C:\Users\mje
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "azure-functions-core-tools@3" "--unsafe-perm" "true" "--verbose"
npm verb node v15.12.0
npm verb npm  v7.6.3
npm ERR! code 1
npm ERR! path C:\Users\mje\AppData\Roaming\npm\node_modules\azure-functions-core-tools
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! node:internal/modules/cjs/loader:927
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'unzipper'
npm ERR! Require stack:
npm ERR! - C:\Users\mje\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (C:\Users\mje\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:3:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:972:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\mje\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\lib\\install.js'
npm ERR!   ]
npm ERR! }
npm verb exit 1
npm timing npm Completed in 827ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mje\AppData\Local\npm-cache\_logs\2021-03-30T18_59_57_002Z-debug.log
```

**Comment by CarsonPLS** [comment]
Sounds like the same issue I'm having.

https://github.com/Azure/azure-functions-core-tools/issues/2514

I am usually pretty good at troubleshooting things like this, but this one has me a bit confused. The Issues board not overflowing with comments about this implies that it's constrained to a subset of users.

**Comment by FabioFerrua** [comment]
Hi, same problem here. I was able to update by manually installing the following dependencies:

```
npm i -g unzipper
npm i -g chalk
npm i -g https-proxy-agent
```

then running the update command:

`npm i -g azure-functions-core-tools@3 --unsafe-perm true --legacy-peer-dep`

hope it helps

**Comment by CarsonPLS** [comment]
Thank you @FabioFerrua 

I also installed a number of libraries manually, but this one keeps asking for more. It is now asking for `glob`, after I have installed about 7 of the previous dependencies. 

I suspect that if we manually install every dependency, then yes the update will apply, but then I fear we are enabling the issue.

**Comment by MJECloud** [comment]
Thanks @FabioFerrua 

@CarsonPLS i agree. I think it doesn't solve the real problem. 
When installing the core tools you shouldnt manually install all dependencies globally.

**Comment by CarsonPLS** [comment]
The frustrating part is that this has been ongoing with little response for weeks.

Yet VS Code reminds me of this issue about 4 times a day.... (each time I open a new window)

MS, please just keep us posted... is it us being dumb, or is this something you have identified that you need to fix?

**Comment by stemixreal** [comment]
Same for me #2544 

Dev environment broken after several attempts to fix it. I'm going to start from scratch.

**Comment by stemixreal** [comment]
The fix for me is in my reply to #2544. Perhaps it will help. I was getting the same errors as detailed in the OP when the required modules do exist in the correct location.

**Comment by MJECloud** [comment]
@stemixreal thanks for the update!

I've uninstalled and reinstalled the core tools via vscode and now it works!
![image](https://user-images.githubusercontent.com/22131101/114251420-3c934180-99a1-11eb-8d67-0aef39fb53bf.png)
The first version is before the reinstallation, the second after. 

@CarsonPLS  @FabioFerrua  maybe it works for you too!

**Comment by AnweshGangula** [comment]
I'm facing the same issue.

```cmd
npm ERR! code 1
npm ERR! path C:\Users\AnweshG\AppData\Roaming\npm\node_modules\azure-functions-core-tools
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! node:internal/modules/cjs/loader:927
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'unzipper'
npm ERR! Require stack:
npm ERR! - C:\Users\AnweshG\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (C:\Users\AnweshG\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:3:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:972:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\AnweshG\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\lib\\install.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AnweshG\AppData\Local\npm-cache\_logs\2021-06-03T11_31_13_414Z-debug.log```

**Comment by kathleenwest** [comment]
I'm facing the same issue 
https://github.com/microsoft/vscode-azurefunctions/issues/2832

**Comment by CarsonPLS** [comment]
The workaround that has worked most if not all is to run

`npm uninstall -g azure-functions-core-tools` 
then
`npm i -g azure-functions-core-tools@3`

Not ideal but did resolve the issue for me twice (across 2 updates of the library)

**Comment by kathleenwest** [comment]
> The workaround that has worked most if not all is to run
> 
> `npm uninstall -g azure-functions-core-tools`
> then
> `npm i -g azure-functions-core-tools@3`
> 
> Not ideal but did resolve the issue for me twice (across 2 updates of the library)

Ok, thanks. But this should be put into the update script.

**Comment by CarsonPLS** [comment]
@kathleenwest 

Agreed. Let's hope the team hears our humble prayers. 😁

**Comment by apawast** [comment]
Hi @MJECloud and others, we have assigned this to be better investigated so we can better understand the problem. Thank you for your updates!

**Comment by fabiocav** [comment]
@apawast I'm removing this from the project. Please let me know if you need any help assigning this item.

**Comment by michaelpeng36** [comment]
@MJECloud, are you still facing this issue?

**Comment by MJECloud** [comment]
@michaelpeng36 no i dont run into this issue anymore. This issue can be closed.
