### ISSUE TITLE
func kubernetes deploy completes with "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-core-tools#2572]
### Core tools version
3.0.3442 (latest as of today)

### Repro steps
Deploy Durable Functions app with SQL backend once to an AKS cluster, and then again a second time (the problem happens on the second deployment):

```powershell
func kubernetes deploy --name "durabletask-mssql-app" --image-name "$repo/mssql-durable-functions:latest" --secret-name "mssql-secrets" --max-replicas 10
```

Output:
```
secret/func-keys-kube-secret-durabletask-mssql-app configured
serviceaccount/durabletask-mssql-app-function-keys-identity-svc-act unchanged
role.rbac.authorization.k8s.io/functions-keys-manager-role unchanged
rolebinding.rbac.authorization.k8s.io/durabletask-mssql-app-function-keys-identity-svc-act-functions-keys-manager-rolebinding unchanged
service/durabletask-mssql-app-http unchanged
deployment.apps/durabletask-mssql-app-http configured
deployment.apps/durabletask-mssql-app configured
scaledobject.keda.sh/durabletask-mssql-app configured
Waiting for deployment "durabletask-mssql-app-http" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "durabletask-mssql-app-http" rollout to finish: 1 old replicas are pending termination...
deployment "durabletask-mssql-app-http" successfully rolled out
Object reference not set to an instance of an object.
```

I don't know what the impact of this null-ref is, but regardless it isn't a good look.

I also don't know if this is at all related to Durable Functions. That just happened to be the scenario I was testing.

FYI @ahmelsayed

**Comment by apawast** [comment]
@ahmelsayed can you please take a look at this?

**Comment by ahmelsayed** [comment]
@cgillum can you set `CLI_DEBUG=1` and run the command again and share the exception you're seeing.

**Comment by cgillum** [comment]
(Updated repro steps to be more accurate)

I set `CLI_DEBUG=1` and have a few more details. First, I see a lot of I/O exceptions related to network communications that repeat for a while. Here is the first exception:

```
Waiting for deployment "durabletask-mssql-app-http" rollout to finish: 1 old replicas are pending termination...
deployment "durabletask-mssql-app-http" successfully rolled out
> kubectl port-forward deployment/durabletask-mssql-app-http  1464:80
> kubectl get service durabletask-mssql-app-http -o json
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Azure.Functions.Cli.Kubernetes.KubernetesHelper.GetHttpResponse(HttpRequestMessage httpRequestMessage, Int32 retryCount) in D:\a\1\s\src\Azure.Functions.Cli\Kubernetes\KubernetesHelpers.cs:line 405
```

The above is followed by `SocketExceptions` every few seconds. I'm not copy/pasting them here since they might be somewhat redundant with the above.

Finally, after several iterations, the operation fails with a `NullReferenceException`:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Functions.Cli.Kubernetes.KubernetesHelper.PrintFunctionsInfo(DeploymentV1Apps deployment, ServiceV1 service, IDictionary`2 funcKeys, TriggersPayload triggers, Boolean showServiceFqdn) in D:\a\1\s\src\Azure.Functions.Cli\Kubernetes\KubernetesHelpers.cs:line 335
   at Azure.Functions.Cli.Actions.KubernetesActions.KubernetesDeployAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\KubernetesActions\KubernetesDeployAction.cs:line 206
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

**Comment by ahmelsayed** [comment]
I see. After a deployment is done, it tries to list functions from the runtime by [forwarding a port](https://github.com/Azure/azure-functions-core-tools/blob/735920bfbeac5d79eb3c978047301f1cd9957dcd/src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs#L327-L331) to your local machine and sending the `GET /admin/functions` to it. I have seen sometimes when port forwarding a port quickly after a deployment starts, the kubectl command succeeds, but the port doesn't actually work. I think restarting the proxy on a socket/io exception might be better rather than just retying the request.
