### ISSUE TITLE
No ESM support

### ISSUE THREAD

**Issue by schrotie** [Azure/azure-functions-core-tools#2595]
Summary: ECMAScript modules don't work when running locally on Linux

System: Manjaro (Arch) Linux
Core Tools Version:       3.0.3528

Use-Case: run function locally
Function: default created by "init", renamed index.js to index.mjs, no other changes

Expected result: runs as before with index.js
Observed result: crashes, apparently because node assumes it's CJS not ESM
Note: `context.log('version', process.version)` in index.js yields `version v14.16.1`

Log of failed run:
```
~/bin/azureFunctions/func start

Azure Functions Core Tools
Core Tools Version:       3.0.3528 Commit hash: 6cfbdc9c16e071f2902c63e32bb945c16b7e0feb  (64-bit)
Function Runtime Version: 3.0.15828.0


Functions:

	HttpTrigger: [GET,POST] http://localhost:8080/api/HttpTrigger

For detailed output, run func with --verbose flag.
[2021-05-18T10:06:18.558Z] Worker process started and initialized.
[2021-05-18T10:06:18.570Z] Worker was unable to load function HttpTrigger: 'ReferenceError: module is not defined'
[2021-05-18T10:06:18.573Z] Worker failed to function id 8352be83-ed6a-4b90-92a4-4098e334fc0b.
[2021-05-18T10:06:18.573Z] Result: Failure
[2021-05-18T10:06:18.573Z] Exception: Worker was unable to load function HttpTrigger: 'ReferenceError: module is not defined'
[2021-05-18T10:06:18.573Z] Stack: ReferenceError: module is not defined
[2021-05-18T10:06:18.573Z]     at file:///[fullPath]/HttpTrigger/index.mjs:1:1
[2021-05-18T10:06:18.573Z]     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
[2021-05-18T10:06:18.573Z]     at async Loader.import (internal/modules/esm/loader.js:166:24).
[2021-05-18T10:06:23.461Z] Host lock lease acquired by instance ID '000000000000000000000000412AD94F'.
[2021-05-18T10:06:38.423Z] Executing 'Functions.HttpTrigger' (Reason='This function was programmatically called via the host APIs.', Id=b7d7446e-9318-4d00-b594-4d3daddb4b64)
[2021-05-18T10:06:38.477Z] Executed 'Functions.HttpTrigger' (Failed, Id=b7d7446e-9318-4d00-b594-4d3daddb4b64, Duration=85ms)
[2021-05-18T10:06:38.477Z] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger. System.Private.CoreLib: Result: Failure
[2021-05-18T10:06:38.477Z] Exception: Worker was unable to load function HttpTrigger: 'ReferenceError: module is not defined'
[2021-05-18T10:06:38.477Z] Stack: ReferenceError: module is not defined
[2021-05-18T10:06:38.477Z]     at file:///[fullPath]/HttpTrigger/index.mjs:1:1
[2021-05-18T10:06:38.477Z]     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
[2021-05-18T10:06:38.477Z]     at async Loader.import (internal/modules/esm/loader.js:166:24).
```

**Comment by schrotie** [comment]
My fault, needed to replace `module.exports =` with `export default`. Sorry, was blind ...
