### ISSUE TITLE
MacOsx upgrade from 3.0.3442 to 3.0.3477 introduces /dev/shm/AzureFunctions warning message

### ISSUE THREAD

**Issue by sceniclife** [Azure/azure-functions-core-tools#2600]
Version 3.0.3442 starts without any warning (yellow) messages
```
Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
```

Version 3.0.3477 now starts with Operation not permitted message
```
Azure Functions Core Tools
Core Tools Version:       3.0.3477 Commit hash: 5fbb9a76fc00e4168f2cc90d6ff0afe5373afc6d  (64-bit)
Function Runtime Version: 3.0.15584.0

[2021-05-21T21:42:28.276Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-05-21T21:42:28.276Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
```

**Comment by DaRosenberg** [comment]
Also seeing this.

Since `/dev/shm` does not exist on macOS I think the core tools should either not try to use it on macOS, or fail more gracefully/silently (i.e. not print a warning since this is pretty much to be expected on macOS).

Printing this warning only makes the experience noisier and risks distracting from legitimate warnings IMO.

**Comment by fabiocav** [comment]
@pragnagopa @gohar94 this might be a scenario that wasn't completely covered. Wondering if shared memory should be completely disabled in local run scenarios.

**Comment by gohar94** [comment]
@fabiocav I think the use of this is disabled but the initialization attempt happens anyway. I agree, we should do the initialization only when this is enabled.

**Comment by fabiocav** [comment]
Thanks! Flagging this for consideration in sprint 103

**Comment by fabiocav** [comment]
Moving to 105 as we're still iterating on the PR.

**Comment by vrdmr** [comment]
Full stacktrace form the worker - we'll add a check on the worker as well to prevent this happening if the shared memory directory is not supported on any platform

```python
Job host started
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-functions-core-tools@3/3.0.3477/workers/python/3.9/OSX/X64/azure_functions_worker/bindings/shared_memory_data_transfer/file_accessor_unix.py", line 127, in _get_valid_mem_map_dirs
    os.makedirs(dir_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/dev/shm'
Host lock lease acquired by instance ID '0000000000000000000000001A4849C5'.
```

**Comment by ggaj** [comment]
Some update about this problem... I have same issue...

```cmd
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0

[2021-06-30T00:56:39.800Z] Found /Users/gildo.araujo/Projects/TesteTrigger/TesteTrigger/TesteTrigger.csproj. Using for user secrets file configuration.
[2021-06-30T00:56:40.836Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-06-30T00:56:40.836Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
```

Thanks

**Comment by fabiocav** [comment]
Moving to 106 as we're still iterating on the PR

**Comment by stdtom** [comment]
For those who want to force installation of v3.0.3442, the following might help:

```
cd $(brew --repository)/Library/Taps/azure/homebrew-functions
git checkout Update_3.0.3442
HOMEBREW_NO_AUTO_UPDATE=1  brew install azure-functions-core-tools@3

**Comment by fabiocav** [comment]
Taking ownership of this to complete the associated PR. Keeping in sprint 106 as we should still be able to make that date.

**Comment by janidama** [comment]
Hi Team, I couldn't able to run `func start --build`


Due to issue


[2021-08-31T04:53:35.104Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-08-31T04:53:35.104Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.


Any help?

**Comment by murilobeltrame** [comment]
Hello all, just for information, same problem here even with the newest updates:

```
Extension bundle specified, skip install extension
Using port : ***

Azure Functions Core Tools
Core Tools Version:       3.0.3734 Commit hash: 61192bb28820be76916f85209916152801483456  (64-bit)
Function Runtime Version: 3.1.4.0

[2021-09-21T22:53:42.591Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-09-21T22:53:42.591Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
```

**Comment by mdantuluru** [comment]
Hello All,
I have the same problem with CoreToolsVersion 3.0.3734
`[2021-09-22T18:28:09.069Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-09-22T18:28:09.069Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.`

**Comment by anthonychu** [comment]
@michaelpeng36 can provide an update on when this will be fixed.

**Comment by andresogando** [comment]
Same issue. 

**Mac M1 Pro - Monterrey ** 

`Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0

[2022-02-14T19:30:49.444Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2022-02-14T19:30:49.449Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.`

**Comment by PeteTh** [comment]
Same issue,  has the really been an issue since May 2021, when will it be fixed ? 

**Mac M1 Pro - Monterrey** 

`Azure Functions Core Tools
Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
Function Runtime Version: 3.3.1.0

[2022-02-17T16:24:35.901Z] Found /Users/peteth/javaprojects/Capgemini2016/BST/AZ204-course/AZ204-course.csproj. Using for user secrets file configuration.

[2022-02-17T16:24:36.487Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2022-02-17T16:24:36.488Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
[2022-02-17T16:24:36.489Z] Valid directories for shared memory usage: `

**Comment by andresogando** [comment]
> 

Hi, I fixed it by upgrading to core tools v4. follow these steps.  go and make sure you click the docs for V4
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cmacos%2Ccsharp%2Cportal%2Cbash

**Comment by tomconte** [comment]
I get the same error with v4:

Core Tools Version:       4.0.4426 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473

```
[2022-04-12T08:13:04.117Z] Traceback (most recent call last):
[2022-04-12T08:13:04.118Z]   File "/usr/local/Cellar/azure-functions-core-tools@4/4.0.4426/workers/python/3.9/OSX/X64/azure_functions_worker/bindings/shared_memory_data_transfer/file_accessor_unix.py", line 127, in _get_valid_mem_map_dirs
[2022-04-12T08:13:04.118Z]     os.makedirs(dir_path)
[2022-04-12T08:13:04.118Z]   File "/Users/tconte/.pyenv/versions/3.9.9/lib/python3.9/os.py", line 215, in makedirs
[2022-04-12T08:13:04.118Z]     makedirs(head, exist_ok=exist_ok)
[2022-04-12T08:13:04.118Z]   File "/Users/tconte/.pyenv/versions/3.9.9/lib/python3.9/os.py", line 225, in makedirs
[2022-04-12T08:13:04.118Z]     mkdir(name, mode)
[2022-04-12T08:13:04.118Z] PermissionError: [Errno 1] Operation not permitted: '/dev/shm'
```

**Comment by fmilagres** [comment]
same here...

**Comment by LucasOleksak** [comment]
Hi, I also get this error with v4:

Found Python version 3.9.9 (python3).

Azure Functions Core Tools
Core Tools Version:       4.0.4483 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473

**Comment by RyanSadowski** [comment]
Still getting this error

**Comment by liliankasem** [comment]
Hi, is anyone stil seeing this error with the latest version (v4.1.0?) Please share a call stack for me to investigate - thanks!

**Comment by DaRosenberg** [comment]
@liliankasem I can confirm that this is happening on 4.1:

```
Azure Functions Core Tools
Core Tools Version:       4.1.0+7ff2567e43c1ae7471cea7394452c1447661e175 (64-bit)
Function Runtime Version: 4.1040.300.25317

[2025-08-05T14:21:59.876Z] Found /Users/danielrosenberg/Git/OrgFlow/OrgFlow/components/SvcTenant/src/OrgFlow.Tenants.Functions/OrgFlow.Tenants.Functions.csproj. Using for user secrets file configuration.
[2025-08-05T14:22:00.137Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2025-08-05T14:22:00.137Z] System.Private.CoreLib: Access to the path '/dev/shm' is denied. Operation not permitted.
```

How do I get the call stack you are asking for?

**Comment by liliankasem** [comment]
Is that what you see with --verbose? Can you share info about your environment too (OS etc.). I'm running on OSX (M3) and I don't see it so just any info that might help me find the issue!

**Comment by DaRosenberg** [comment]
@liliankasem with the `--verbose` flag it instead looks like this:

```
Selected out-of-process host.

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.1.0+7ff2567e43c1ae7471cea7394452c1447661e175 (64-bit)
Function Runtime Version: 4.1040.300.25317

[2025-08-05T18:50:47.549Z] Found /Users/danielrosenberg/Git/OrgFlow/OrgFlow/components/SvcTenant/src/OrgFlow.Tenants.Functions/OrgFlow.Tenants.Functions.csproj. Using for user secrets file configuration.
[2025-08-05T18:50:47.750Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2025-08-05T18:50:47.750Z] System.Private.CoreLib: Access to the path '/dev/shm' is denied. Operation not permitted.
[2025-08-05T18:50:47.789Z] Building host: version spec: , startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'c054d0ed-411b-4e0b-b3bf-21fb965e1a88'
[2025-08-05T18:50:47.849Z] Reading host configuration file '/Users/danielrosenberg/Git/OrgFlow/OrgFlow/components/SvcTenant/src/OrgFlow.Tenants.Functions/bin/output/host.json'
[2025-08-05T18:50:47.849Z] Host configuration file read:
[2025-08-05T18:50:47.850Z] {
[2025-08-05T18:50:47.850Z]   "version": "2.0",
[2025-08-05T18:50:47.850Z]   "logging": {
[2025-08-05T18:50:47.850Z]     "logLevel": {},
[2025-08-05T18:50:47.850Z]     "applicationInsights": {
[2025-08-05T18:50:47.850Z]       "samplingSettings": {
[2025-08-05T18:50:47.850Z]         "isEnabled": false
[2025-08-05T18:50:47.850Z]       }
[2025-08-05T18:50:47.850Z]     }
[2025-08-05T18:50:47.850Z]   }
[2025-08-05T18:50:47.850Z] }
[2025-08-05T18:50:47.899Z] Reading host configuration file '/Users/danielrosenberg/Git/OrgFlow/OrgFlow/components/SvcTenant/src/OrgFlow.Tenants.Functions/bin/output/host.json'
[2025-08-05T18:50:47.899Z] Host configuration file read:
[2025-08-05T18:50:47.899Z] {
[2025-08-05T18:50:47.899Z]   "version": "2.0",
[2025-08-05T18:50:47.899Z]   "logging": {
[2025-08-05T18:50:47.899Z]     "logLevel": {},
[2025-08-05T18:50:47.899Z]     "applicationInsights": {
[2025-08-05T18:50:47.899Z]       "samplingSettings": {
[2025-08-05T18:50:47.899Z]         "isEnabled": false
[2025-08-05T18:50:47.899Z]       }
[2025-08-05T18:50:47.899Z]     }
[2025-08-05T18:50:47.899Z]   }
[2025-08-05T18:50:47.899Z] }
[2025-08-05T18:50:47.993Z] Initializing Warmup Extension.
[2025-08-05T18:50:48.013Z] Initializing Host. OperationId: 'c054d0ed-411b-4e0b-b3bf-21fb965e1a88'.
[2025-08-05T18:50:48.016Z] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=c054d0ed-411b-4e0b-b3bf-21fb965e1a88
[2025-08-05T18:50:48.028Z] Loading functions metadata
```

I am on a MacBook Pro 14-inch 2023, M2 Max and 64 GB RAM, running macOS Sequoia 15.5.

I am running it from a VS Code task configured like so:

```json
{
	"label": "func start",
	"type": "func",
	"command": "start --port 7099",
	"options": {
		"cwd": "${workspaceFolder}/src/OrgFlow.Tenants.Functions",
	},
	"isBackground": true,
	"problemMatcher": "$func-dotnet-watch"
}
```

The application being run is a .NET 8.0 app using dotnet-isolated.

**Comment by liliankasem** [comment]
Ah I think maybe you have different config/setup for logging? I don't see the warning when I run the CLI but I _do_ see an exception is throw and that same message logged when I debug the CLI with the Function's Host:

`Logger.LogWarning(exception, "Cannot create directory for shared memory usage: {Directory}", path);`

https://github.com/Azure/azure-functions-host/blob/3a5d1010433d7fbee142b3a13fb43d20874c9b27/src/WebJobs.Script/Workers/SharedMemoryDataTransfer/MemoryMappedFileAccessorUnix.cs#L199

I think we might be able to replace the `MemoryMappedFileAccessorUnix` service in the core tools via DI. Will keep on investigating. Thanks for sharing your details.
