### ISSUE TITLE
func new with javascript returns "the operation was cancelled"

### ISSUE THREAD

**Issue by swayamsidha** [Azure/azure-functions-core-tools#2614]
I did func init, selected Node.js and language Javascript, when I hit func new, it showed me "the operation was canceled"
then I checked with `CLI_DEBUG=1 func new`, i got the following response
System.Exception: Cannot find the Local Application Data.
   at Azure.Functions.Cli.Utilities.EnsureCoreToolsLocalData() in D:\a\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 183
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.VerifyOrSetDefaultStorageDirectoryPath(String desireStorageDirectoryPath) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 94
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.Init(String storageDirectoryPath) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 78
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.PersistenceChannel..ctor(String storageDirectoryPath, Int32 sendersCount) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\PersistenceChannel.cs:line 42
   at Azure.Functions.Cli.Telemetry.Telemetry.InitializeTelemetry() in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\Telemetry.cs:line 93
Please help.

**Comment by apawast** [comment]
@swayamsidha has this issue persisted for you? What channel did you use to install core tools? And have you tried reinstalling it?
