### ISSUE TITLE
Regional bug with , (comma) and . (dot) separators

### ISSUE THREAD

**Issue by zapy33** [Azure/azure-functions-core-tools#2627]
Hi, I recently tried to run a Logic App locally with the new Visual Studio Code extension. I followed all the instructions from Microsoft but always got an error which no one seemed to have had before:

```
Job dispatching error: operationName='JobDispatchingWorker.ExecuteTriggerInnerLoop', jobPartition='D3BF5903B767892F821ACA7840F8D76A:2D08585776957766837955885029264CU00', jobId='08585776957775253155885029264CU00', message='Job dispatching worker unable to execute inner trigger loop.', exception='System.FormatException: Input string was not in a correct format.        
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at System.Convert.ToDouble(String value)
at Microsoft.Azure.Workflows.Common.Logging.FlowEventSource.JobHistory(String jobPartition, String jobId, String callback, String startTime, String endTime, String executionTimeInMilliseconds, String executionDelayInMilliseconds, String executionIntervalInMilliseconds, String executionStatus, String executionMessage, String executionDetails, String nextExecutionTime, String subscriptionId, String correlationId, String principalOid, String principalPuid, String tenantId, String dequeueCount, String advanceVersion, String triggerId, String messageId, String state, String organizationId, String activityVector, String realPuid, String altSecId, String additionalProperties, String jobDurabilityLevel)
at Microsoft.WindowsAzure.ResourceStack.Common.BackgroundJobs.Execution.JobDispatchingWorker.HandleJobExecution(JobTrigger trigger, JobDefinition definition, BackgroundJob backgroundJob, DateTime startTime, DateTime endTime, TimeSpan 
executionTime, TimeSpan executionDelay, TimeSpan executionInterval, JobExecutionResult executionResult, Boolean executeJobInline)   
at Microsoft.WindowsAzure.ResourceStack.Common.BackgroundJobs.Execution.JobDispatchingWorker.ExecuteJobWithCancellation(JobTrigger trigger, JobDefinition definition, CancellationToken cancellationToken)
at Microsoft.WindowsAzure.ResourceStack.Common.BackgroundJobs.Execution.JobDispatchingWorker.ExecuteJobWithWatchdog(JobTrigger trigger, JobDefinition definition)
at Microsoft.WindowsAzure.ResourceStack.Common.BackgroundJobs.Execution.JobDispatchingWorker.ExecuteTriggerInnerLoop(JobTrigger trigger, JobDefinition definition)', correlationId='', organizationId='', activityVector='', additionalProperties='', extensionVersion='1.0.0.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='00000000-0000-0000-0000-000000000000'.
```

I spent a lot of time trying to fix this on my own when really all I had to do was change my regional settings to the United States ( where I am from we use , (comma) as a decimal separator and not . (dot) ). I don't know if this can be "fixed" but you should definitely **HIGHLIGHT** it in the documentation.

**Comment by apawast** [comment]
@zapy33 we are engaging the logic apps team to investigate this.
