### ISSUE TITLE
Javascript Azure functions crash on azure-functions-core-tools@2.0.1-beta.18

### ISSUE THREAD

**Issue by nelak** [Azure/azure-functions-core-tools#280]
**This issue is also reproducible on Azure.**

This seems to fail on Ubuntu and WSL, but works on OSX

```
[10/17/17 3:10:16 PM] A ScriptHost error has occurred
[10/17/17 3:10:16 PM] Exception while executing function: Functions.myTimer. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 6507 exited with code 1) (Worker process with pid 6520 exited with code 1) (Worker process with pid 6529 exited with code 1). Worker process with pid 6507 exited with code 1.
```
Running azure-functions-core-tools@2.0.1-beta.17 still works.

Let me know if you need more information

**Comment by valorekhov** [comment]
Getting the same issue running on Azure right now:

Runtime version: 2.0.11276.0 (beta)

Exception: Worker process with pid 5096 exited with code 1
Unknown location

AggregateException: One or more errors occurred. (Worker process with pid 5096 exited with code 1) (Worker process with pid 4912 exited with code 1) (Worker process with pid 3392 exited with code 1)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

FunctionInvocationException: Exception while executing function: Functions.CreateFormatFile
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


System.AggregateException: One or more errors occurred. (Worker process with pid 5096 exited with code 1) (Worker process with pid 4912 exited with code 1) (Worker process with pid 3392 exited with code 1) ---> System.Exception: Worker process with pid 5096 exited with code 1
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Script.Description.WorkerLanguageInvoker.<InvokeCore>d__6.MoveNext() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\Worker\WorkerLanguageInvoker.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.<Invoke>d__31.MoveNext() in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.<InvokeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__16.MoveNext()
---> (Inner Exception #0) System.Exception: Worker process with pid 5096 exited with code 1<---

---> (Inner Exception #1) System.Exception: Worker process with pid 4912 exited with code 1<---

---> (Inner Exception #2) System.Exception: Worker process with pid 3392 exited with code 1<---

**Comment by naknode** [comment]
Same. I created a new JavaScript `timerTrigger`. Ran it on version `~1~ and it executed fine.

I switched the version to `BETA` and ran it again and got: 

```
2017-10-26T14:17:55  Welcome, you are now connected to log-streaming service.
2017-10-26T14:17:57.938 Function started (Id=b196bcc3-c8ae-493e-84c7-9e037dba7141)
2017-10-26T14:17:58.565 Exception while executing function: Functions.Wrike. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 7820 exited with code 1) (Worker process with pid 6964 exited with code 1) (Worker process with pid 6436 exited with code 1). Worker process with pid 7820 exited with code 1.
2017-10-26T14:17:58.907 Function completed (Failure, Id=b196bcc3-c8ae-493e-84c7-9e037dba7141, Duration=957ms)
```

**Comment by christopheranderson** [comment]
This is likely because you're not using the right Node.js version. I'll be adding some support to help detect this soon. Could you confirm which Node.js version you're using?

**Comment by valorekhov** [comment]
I believe ~1.x runtime has Node.JS version 6.5 as the locked choice?
v

**Comment by christopheranderson** [comment]
It is. For BETA, please make sure it's set to 8.4.0 or above. If you use the toggle in the Function App Settings menu it *should* do this for you, but there could be a bug.

**Comment by nelak** [comment]
@christopheranderson I was using node 8.5.0 at the moment.
Also the issue was reproducible on Azure as well, see issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/2126

**Comment by christopheranderson** [comment]
For your issue, @nelak if you're using 8.5.0, do you get the same exit code error? You should be getting a 500 error because we don't support "raw" in v2 yet. (See this PR: https://github.com/Azure/azure-webjobs-sdk-script/pull/2064)

**Comment by naknode** [comment]
I was able to solve my problem by updating my Node to latest version. All good here. @christopheranderson

**Comment by nelak** [comment]
@christopheranderson It seems some kind of bug made it into `.beta.18` if you go back to that version you can reproduce it really easy things go down by just running `func host start`.

![image](https://user-images.githubusercontent.com/254502/32926619-f193999c-cb26-11e7-8524-2473c4334c58.png)

It's highly likely the bad build made it to Azure causing the issues I was seeing in Azure/azure-webjobs-sdk-script#2126 but completely unrelated to the `raw` pending implementation.
From what I can see it seems that the regression has already been fixed around version `.beta.21` as the issue is no longer reproducible locally. 

![image](https://user-images.githubusercontent.com/254502/32926660-1e98c37c-cb27-11e7-80ce-32e129a5d836.png)

Still it makes me wonder why `.beta.18` worked on OSX but not on WSL. It might be worth looking at that build to understand what caused the breakage.

**Comment by blackcid** [comment]
This bug is still happening. Even blank functions throw that exception. No matter with node version is being used (from 8.4.0 to 8.9.4)

Repair this should have hightest priority.

**Comment by catcher-in-the-try** [comment]
I am using beta.23 and the issue still persists. So it is not possible to run any node.js function whatsoever right now?

**Comment by gregatcssi** [comment]
i'm using 2.0.1-beta.24 , node 9.8.0 & npm 5.7.1 with the same issue. (Javascript HttpTrigger function)
even following the steps in the tutorial will bring 500 error.

**Comment by IamNguele** [comment]
Facing the same issue here.

**Comment by catcher-in-the-try** [comment]
@IamNguele Apparently, deleting your function and copy-pasting the code into an identical new function sometimes helps. It helped me once or twice.

Also, make sure your code is not simply throwing an exception due to missing packages, bug or anything else, because that will also cause an identical error message.

**Comment by Alexander-0x80** [comment]
Seems like it is still not resolved 
Using Runtime version 2.0.1.0 (beta)

**Comment by reggieboyYEAH** [comment]
Issue still persists in using 2.0.1-beta.28. :(

**Comment by ahmedelnably** [comment]
Closing this, please reopen if it still the case in the latest version
