### ISSUE TITLE
Azure Functions Core Tools v3 Randomly Crashing/Stopping

### ISSUE THREAD

**Issue by PCOffline** [Azure/azure-functions-core-tools#2836]
I have this issue on Node 14 with `azure-functions-core-tools@3.0.3904` release on npm. The function-app is launched perfectly fine, however it can just decide to crash in one of the next scenarios:
1. Instantly after starting
2. Up to 5 minutes after starting
3. At least an hour after starting

There is no consistency, though, and sometimes the function-app may not crash at all.

These are the logs I get:
```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 187347.546ms 200 application/grpc
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HMCURUIIU0HN", Request id "0HMCURUIIU0HN:00000001": the application completed without reading the entire request body.
info: Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
System.IO.IOException: The request stream was aborted.
 ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ReadInputAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
[2021-11-03T15:39:11.947Z] Debugger listening on ws://127.0.0.1:9229/ef004a09-836f-43a7-bc36-de8fd71e8115
[2021-11-03T15:39:11.949Z] For help, see: https://nodejs.org/en/docs/inspector
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://127.0.0.1:53044/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2021-11-03T15:39:12.116Z] Worker process started and initialized.
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command func host start" terminated with exit code: 1.
```

**Comment by PCOffline** [comment]
And some details about my system and project:
Running in VS Code Version 1.62.3 (user setup)
Node v14.18.0
npm 6.14.15
PowerShell 7.2.0

**Comment by apawast** [comment]
@PCOffline could you please share repro steps and your app with us? It is hard to determine what is causing the problem.

**Comment by PCOffline** [comment]
1. Launch my app on VSCode
2. Press F5 (that starts a sequence of `npm install`, `tsc` and `func host start`
3. Wait for the functionapp to start

**Comment by michaelpeng36** [comment]
@PCOffline yes, would you be able to share the video?

**Comment by PCOffline** [comment]
Hey, apologies for the delay, I will only be able to get to my pc on Monday, I'll record a video first thing in the morning.

**Comment by Thyholt** [comment]
https://docs.microsoft.com/en-us/answers/questions/598791/azure-function-fails-with-functioninvocationexcept.html
