### ISSUE TITLE
Commands hanging on Arch Linux

### ISSUE THREAD

**Issue by telmotrooper** [Azure/azure-functions-core-tools#2899]
I'm using Azure Functions Core Tools **4.0.3971** (from "https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.3971/Azure.Functions.Cli.linux-x64.4.0.3971.zip") on **Arch Linux** and some basic commands (like `./func new`) keep hanging for about a minute until I eventually receive the error: `One or more errors occurred. (A task was canceled.)`. It doesn't even display the list of templates available.

I'm pretty sure the issue is a timeout, when I tried running the same steps on a Linux Mint VM it worked as expected.

Running the command with `CLI_DEBUG` flag enabled (`CLI_DEBUG=1 ./func new myProject`) I got the following error about a minute after I was prompted to `Select a number for template:` and no options were displayed:

```
Select a number for template:System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.<.ctor>b__24_0() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 44
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 171
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.RunAsync()
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container)
   at Azure.Functions.Cli.ConsoleApp.<>c__DisplayClass6_0`1.<Run>b__0() in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.<.ctor>b__24_0() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 44
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Azure.Functions.Cli.Actions.LocalActions.CreateFunctionAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\CreateFunctionAction.cs:line 171
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
```

Commands that don't seem to rely on remote servers seem to work well, e.g. `./func init myApp`.

Can someone try to help me figure this out? Thank you.

**Comment by telmotrooper** [comment]
I've ran some more tests, on a VM running Arch it worked just fine, so I came to the conclusion that it had to be related to my network interface. I ended up restarting my modem and it began to work.

Very weird, but it's all good now, so I'll be closing the issue.
