### ISSUE TITLE
func command times out on Linux

### ISSUE THREAD

**Issue by ttelik** [Azure/azure-functions-core-tools#2929]
Hi, I'm trying to use the func command to generate a new Azure Function template, and this command fails. Even asking for a list of templates times out. The error trace is below. I am performing these commands from within the venv (as specified in the documentation).

```
$ func templates list -l python --debug
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.TryDownloadZipFileAsync(Uri zipUri, String filePath, HttpClient httpClient) in D:\a\1\s\src\WebJobs.Script\ExtensionBundle\ExtensionBundleManager.cs:line 200
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.DownloadExtensionBundleAsync(String version, HttpClient httpClient) in D:\a\1\s\src\WebJobs.Script\ExtensionBundle\ExtensionBundleManager.cs:line 171
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetBundle(HttpClient httpClient) in D:\a\1\s\src\WebJobs.Script\ExtensionBundle\ExtensionBundleManager.cs:line 110
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetExtensionBundlePath() in D:\a\1\s\src\WebJobs.Script\ExtensionBundle\ExtensionBundleManager.cs:line 79
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleContentProvider.GetFileContent(String path) in D:\a\1\s\src\WebJobs.Script\ExtensionBundle\ExtensionBundleContentProvider.cs:line 38
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleContentProvider.GetTemplates() in D:\a\1\s\src\WebJobs.Script\ExtensionBundle\ExtensionBundleContentProvider.cs:line 24
   at Azure.Functions.Cli.Common.TemplatesManager.GetTemplates() in D:\a\1\s\src\Azure.Functions.Cli\Common\TemplatesManager.cs:line 40
   at Azure.Functions.Cli.Actions.LocalActions.ListTemplatesAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\LocalActions\ListTemplatesAction.cs:line 36
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
```

System info:
```
$ uname -a
Linux dev-Precision-Tower-5810 5.11.0-44-generic #48~20.04.2-Ubuntu SMP Tue Dec 14 15:36:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ az --version
azure-cli                         2.32.0

core                              2.32.0
telemetry                          1.0.6

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/dev/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Dec 31 2021, 08:09:22)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

$ func --version
4.0.3971

$ ping google.com
PING google.com (142.250.191.206) 56(84) bytes of data.
64 bytes from ord38s31-in-f14.1e100.net (142.250.191.206): icmp_seq=1 ttl=54 time=29.2 ms
64 bytes from ord38s31-in-f14.1e100.net (142.250.191.206): icmp_seq=2 ttl=54 time=47.2 ms
64 bytes from ord38s31-in-f14.1e100.net (142.250.191.206): icmp_seq=3 ttl=54 time=30.4 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms

```

**Comment by bcrobinson** [comment]
I am also seeing when using the func cli on windows 10 & powershell 7.

I encountered this the the V3 of the tools, after upgrading to the V4 it still fails with the same error.

Looking at Process Explorer when runnig this command it seems be downloading data at my max download rate, but consistently only get's to about ~85mb before it fails with a similar message.

I suspect it may be due to not having a fast enough internet connection to download that file in the time limit (and unfortunately my ISP wont let me have a faster one to test this with 😞)

```
>func --version
4.0.4426

>func templates list -l node --debug
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|138_0(ExceptionDispatchInfo e)
   at System.Net.Security.SslStream.DecryptData(Int32 frameSize)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.TryDownloadZipFileAsync(Uri zipUri, String filePath, HttpClient httpClient) in /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs:line 200
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.DownloadExtensionBundleAsync(String version, HttpClient httpClient) in /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs:line 171
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetBundle(HttpClient httpClient) in /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs:line 110
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleManager.GetExtensionBundlePath() in /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs:line 79
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleContentProvider.GetFileContent(String path) in /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleContentProvider.cs:line 38
   at Microsoft.Azure.WebJobs.Script.ExtensionBundle.ExtensionBundleContentProvider.GetTemplates() in /_/src/WebJobs.Script/ExtensionBundle/ExtensionBundleContentProvider.cs:line 24
   at Azure.Functions.Cli.Common.TemplatesManager.GetTemplates() in D:\a\_work\1\s\src\Azure.Functions.Cli\Common\TemplatesManager.cs:line 40
   at Azure.Functions.Cli.Actions.LocalActions.ListTemplatesAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\LocalActions\ListTemplatesAction.cs:line 36
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
```

**Comment by bcrobinson** [comment]
Looking in [Azure/azure-functions-host](https://github.com/Azure/azure-functions-host) the method downloading the extension bundle is creating a `HttpClient` without setting the `Timeout` property, so uses the default 100seconds.

[public async Task<string> GetExtensionBundlePath()](https://github.com/Azure/azure-functions-host/blob/c6763c0c581ffd803646528211fe6729d6f48671/src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs#L75) in `src/WebJobs.Script/ExtensionBundle/ExtensionBundleManager.cs`

```csharp
public async Task<string> GetExtensionBundlePath()
{
    using (var httpClient = new HttpClient())
    {
        return await GetBundle(httpClient);
    }
}
```

**Comment by bcrobinson** [comment]
Managed to work around this for now by poking around in the source code then manually downloading the latest extension bundle from:

`https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/3.15.0/Microsoft.Azure.Functions.ExtensionBundle.3.15.0_any-any.zip `

Extracting this file to:

`"${env:USERPROFILE}\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\3.15.0"`

And updating the `host.json` file to explicity use this version (from the previous range `[2.*, 3.0.0)`)

```json
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "3.15.0"
  },
```

Not a long term fix, but does seem to allow it to get up and running for now
