### ISSUE TITLE
Cloud Azure Function error on startup: WorkerConfig for runtime: dotnet-isolated not found

### ISSUE THREAD

**Issue by CarlosGomesMarel** [Azure/azure-functions-core-tools#2960]
Azure Function error on startup: **WorkerConfig for runtime: dotnet-isolated not found** .
Using a linux image from Azure Container Registry with elastic server farm behind a VNet.
I am attempting to upgrade from .net core 3.1.  
The function runs locally.

**Callstack:**
```
System.InvalidOperationException: WorkerConfig for runtime: dotnet-isolated not found
at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeAsync(IEnumerable`1 functions, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 236
at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 328
at Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script/Host/ScriptHost.cs:line 265
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 309
```
**Project file:**
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<LangVersion>10.0</LangVersion>
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
```

**Dockerfile:**
```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
RUN dotnet publish "MyProject.csproj" -c Release --output /app/publish --no-restore

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=build ["/app/publish", "/home/site/wwwroot"]
RUN ls -lh /home/site/wwwroot
```

**Azure Function Template**
[ipapi.json.txt](https://github.com/Azure/azure-functions-core-tools/files/8120617/ipapi.json.txt)

**Azure Function Configuration**
```
[
  {
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "*********",
  },
  {
    "name": "AzureWebJobsStorage",
    "value": "DefaultEndpointsProtocol=***********",
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~4",
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet-isolated",
  },
  {
    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
    "value": "**************",
  },
  {
    "name": "WEBSITE_CONTENTSHARE",
    "value": "*************",
  },
  {
    "name": "WEBSITE_DNS_SERVER",
    "value": "*************",
  },
  {
    "name": "WEBSITE_HEALTHCHECK_MAXPINGFAILURES",
    "value": "10",
  },
  {
    "name": "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
    "value": "10",
  },
  {
    "name": "WEBSITE_VNET_ROUTE_ALL",
    "value": "1",
  },
  {
    "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
    "value": "false",
  }
]
```

**Comment by perkops** [comment]
I was facing the same issue running an azure function v 4 in dotnet-isolated mode utilizing .net 6.

The only thing that helped in getting the function to start again was deleting and re-creating my app service plan.

**Comment by perkops** [comment]
I am having the same issue with azure functions v 4, dotnet-isolated mode, .net 6. Several deployments and azure function restarts later its working - its very unstable.

**Comment by perkops** [comment]
@CarlosGomesMarel are you using linux functionapp? If so, see this issue:

https://github.com/Azure/azure-functions-dotnet-worker/issues/810

I am "sadly" not using functionapplinux, so i dont think it will help to add the runtimeStack: 'DOTNET-ISOLATED|6.0' in my deployment task.

Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops

**Comment by CarlosGomesMarel** [comment]
Got it to work, I think it was a configuration issue.

**Comment by brennfoster** [comment]
@CarlosGomesMarel Can you please post what the configuration issue was in your case? I cannot figure this out.
