### ISSUE TITLE
Two jar files in \annotationLib

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-core-tools#3066]
Created an Azure Functions project on PowerShell using this command: 
`mvn archetype:generate "-DarchetypeGroupId=com.microsoft.azure" "-DarchetypeArtifactId=azure-functions-archetype" "-DjavaVersion=8"` 
(following instructions [here](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-java?tabs=powershell%2Cazure-cli%2Cbrowser#create-a-local-function-project))

Then hit F5 to debug in VSCode and got this error: 

`Worker failed to load function: 'HttpExample' with function id: '8a75a545-7476-4ca0-a6ca'.
[2022-06-04T04:31:48.960Z] Result: Failure
Exception: FileNotFoundException: Error loading java annotation library jar, multiple jars find from path:  C:\Program Files\Microsoft\Azure Functions Core Tools\workers\java/annotationLib
Stack: java.io.FileNotFoundException: Error loading java annotation library jar, multiple jars find from path:  C:\Program Files\Microsoft\Azure Functions Core Tools\workers\java/annotationLib
[2022-06-04T04:31:48.965Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.addJavaAnnotationLibrary(JavaFunctionBroker.java:139)
[2022-06-04T04:31:48.967Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.addDirectory(JavaFunctionBroker.java:129)        
[2022-06-04T04:31:48.969Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.registerWithClassLoaderProvider(JavaFunctionBroker.java:105)
[2022-06-04T04:31:48.972Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.addSearchPathsToClassLoader(JavaFunctionBroker.java:97)
[2022-06-04T04:31:48.974Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:37)
[2022-06-04T04:31:48.978Z]      at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[2022-06-04T04:31:48.981Z]      at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[2022-06-04T04:31:48.983Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2022-06-04T04:31:48.988Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2022-06-04T04:31:48.992Z]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2022-06-04T04:31:48.994Z]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2022-06-04T04:31:48.997Z]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2022-06-04T04:31:49.001Z]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2022-06-04T04:31:49.006Z]      at java.lang.Thread.run(Thread.java:750)`

The two jar files in `C:\Program Files\Microsoft\Azure Functions Core Tools\workers\java\annotationLib` are: 

- azure-functions-java-library-2.0.0-SNAPSHOT.jar 
- azure-functions-java-library-2.0.1.jar

pom.xml references version 2.0.0

Removing one of the jar files and updating file pom to the proper version removes the error. Which version should be used and does it matter?

**Comment by michaelpeng36** [comment]
@lilyjma Do you mind checking which version of Core Tools you have running? How did you install it?
