### ISSUE TITLE
[Triage] Function core tool release 4.0.4629 missing Function Host dependency, host cannot start in certain configurations

### ISSUE THREAD

**Issue by kiwiliam** [Azure/azure-functions-core-tools#3096]
**[Keywords]**
Function core tool, 4.0.4629, missing dependency, Function Host cannot start, "microsoft.azure.webjobs.extensions.http: could not load file or assembly 'system.net.http.formatting, version=5.2.8.0"

**[Issue]**
After upgrading to release 4.0.4629, the Function Host fails on startup with the following AssemblyNotFoundException. Seems some dependencies were missing.
![image](https://user-images.githubusercontent.com/92900343/177912375-68c0a564-3ace-4624-9564-f5cc7ea80972.png)

**[Repro Steps]**
1. Install Azure Function core tool 4.0.4629.
2. Using "func new" to create an HTTP Function.
3. Attach to Node Function in VScode. Start debugging.
4. Function Host startup fails and reports the missing assembly.

**[Mitigation]**
Downgrade to 4.0.4590, try again repro steps, and Function Host starts normally.
![image](https://user-images.githubusercontent.com/92900343/177912470-e5c0f710-1fd3-43f3-8a17-0a5ed398c109.png)

**[Comment]**
Please double-check release 4.0.4629 and fix if the packages were indeed missing. Thanks in advance.

**Comment by kiwiliam** [comment]
[update]
Cannot repro on some systems
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/92900343/177915693-c90fff6e-b296-4119-8ab5-c1ec1c2b9133.png)

**Comment by older** [comment]
I'm getting this exception as well when I'm running deployment to function app on linux from Octopus with the following command line:

    func azure functionapp publish $appServiceName --csharp

**Comment by johnmc-tc** [comment]
Happening for me too. Definitely needs to be fixed

**Comment by kiwiliam** [comment]
Hello, some updates here.

On Windows 11, I can fully resolve this issue for 4.0.4629 by the following steps. "Purging SDKs"
1. Clear all NuGet package caches. 
"dotnet nuget locals all --clear"
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-locals#examples
Also the VS NuGet cache via GUI.

2. Completely uninstall all .NET versions, Function core tools, delete all residual files.

3. Install only the latest .NET, then Function core tools, and do a repro to make sure it starts normally.

4. Then reinstall everything else as needed.

I haven't yet encountered the same on Linux as most are disposable containers. Not sure if purging SDKs will help.

**Comment by kiwiliam** [comment]
> Sounds like a build issue to me. Any sharable repro? I'd suggest flushing the cache first. I haven't yet encountered the same on Linux or on the cloud. Just the local toolchain.

**Comment by older** [comment]
@kiwiliam I'm running Octopus as a windows service, so it is neither Linux nor cloud.
Downgrading function core tools to 4.0.4590 fixed the issue.

**Comment by kdubau** [comment]
Happening with `4.0.5148` too... no updates from MSFT?

**Comment by dgancho** [comment]
@Microsoft, please solve - same thing on Windows 11 v4.0.5148

```
(.venv) C:\Users\User\source\functionapp>func host start --debug
> py --version
> python3 --version
> python --version
> python3.6 --version
> python3.7 --version
> python3.8 --version
> python3.9 --version
> python3.10 --version
Found Python version 3.10.2 (py).
languageWorkers:python:defaultExecutablePath is set to py

Azure Functions Core Tools
Core Tools Version:       4.0.5148 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.17.3.20392

[2023-05-18T03:07:48.662Z] A host error has occurred during startup operation '395e9db6-09f9-4fbc-8165-a8cff5ece2f5'.
[2023-05-18T03:07:48.665Z] System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
[2023-05-18T03:07:48.668Z] File name: 'System.Net.Http.Formatting, Version=5.2.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[2023-05-18T03:07:48.670Z]    at Microsoft.Extensions.Hosting.HttpWebJobsBuilderExtensions.AddHttp(IWebJobsBuilder builder)
[2023-05-18T03:07:48.671Z]    at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_0.<AddScriptHostCore>b__1(HostBuilderContext context, IWebJobsBuilder webJobsBuilder) in /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs:line 192
[2023-05-18T03:07:48.674Z]    at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection services) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsHostBuilderExtensions.cs:line 130
[2023-05-18T03:07:48.676Z]    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
[2023-05-18T03:07:48.678Z]    at Microsoft.Extensions.Hosting.HostBuilder.Build()
[2023-05-18T03:07:48.679Z]    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup, Boolean skipHostConfigurationParsing) in /_/src/WebJobs.Script.WebHost/DefaultScriptHostBuilder.cs:line 59
[2023-05-18T03:07:48.682Z]    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(Boolean skipHostStartup, Boolean skipHostJsonConfiguration) in /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 599
[2023-05-18T03:07:48.685Z]    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 294
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 380
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
[2023-05-18T03:07:48.776Z] Host startup operation has been cancelled
```

**Comment by Oberon00** [comment]
This happened to me on Windows 11 when upgrading from 4.0.4483 to 4.0.5198

**Comment by surgupta-msft** [comment]
I tried the repro steps from @Oberon00 on the latest coretools 4.0.6594 on windows and did not see any issue. If you are still facing the issue with the latest versions, please open a new issue so that we can take a fresh look at it.

**Comment by es-cs1** [comment]
I just tried installing 4.0.7030

i am getting this issue

```
> func start --verbose --debug
Selected out-of-process host.

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.0.7030 Commit hash: N/A +bb4c949899cd5659d6bfe8b92cc923453a2e8f88 (64-bit)
Function Runtime Version: 4.1037.0.23568

[2025-05-22T21:29:51.545Z] Building host: version spec: , startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '10849c8f-79ff-47a1-a043-eb2f01cf1f03'
[2025-05-22T21:29:51.568Z] Reading host configuration file 'C:\<PATH>\dev\host-based-sensor\terraform-functionapp\azfunc-pwsh-durable\host.json'
[2025-05-22T21:29:51.570Z] Host configuration file read:
[2025-05-22T21:29:51.571Z] {
[2025-05-22T21:29:51.572Z]   "version": "2.0",
[2025-05-22T21:29:51.573Z]   "logging": {
[2025-05-22T21:29:51.574Z]     "applicationInsights": {
[2025-05-22T21:29:51.575Z]       "samplingSettings": {
[2025-05-22T21:29:51.576Z]         "isEnabled": true,
[2025-05-22T21:29:51.578Z]         "excludedTypes": "Request"
[2025-05-22T21:29:51.579Z]       }
[2025-05-22T21:29:51.581Z]     }
[2025-05-22T21:29:51.582Z]   },
[2025-05-22T21:29:51.584Z]   "extensionBundle": {
[2025-05-22T21:29:51.585Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2025-05-22T21:29:51.587Z]     "version": "[4.*, 5.0.0)"
[2025-05-22T21:29:51.588Z]   }
[2025-05-22T21:29:51.588Z] }
[2025-05-22T21:29:51.637Z] FUNCTIONS_WORKER_RUNTIME set to powershell. Skipping WorkerConfig for language: java
[2025-05-22T21:29:51.641Z] FUNCTIONS_WORKER_RUNTIME set to powershell. Skipping WorkerConfig for language: node
[2025-05-22T21:29:51.651Z] FUNCTIONS_WORKER_RUNTIME set to powershell. Skipping WorkerConfig for language: python
[2025-05-22T21:29:51.660Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[2025-05-22T21:29:51.662Z] Found a matching extension bundle at C:\<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\4.22.0
[2025-05-22T21:29:51.669Z] Loading functions metadata
[2025-05-22T21:29:51.673Z] Reading functions metadata (Host)
[2025-05-22T21:29:51.684Z] 1 functions found (Host)
[2025-05-22T21:29:51.694Z] 1 functions loaded
[2025-05-22T21:29:51.696Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[2025-05-22T21:29:51.698Z] Found a matching extension bundle at C:\<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\4.22.0
[2025-05-22T21:29:51.699Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2025-05-22T21:29:51.767Z] Skipping bundle download since it already exists at path C:\<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\4.22.0
[2025-05-22T21:29:51.771Z] Loading extension bundle from C:\<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\4.22.0\bin
[2025-05-22T21:29:51.772Z] Script Startup resetting load context with base path: 'C:\<PATH>\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\4.22.0\bin'.
[2025-05-22T21:29:51.783Z] Reading host configuration file 'C:\<PATH>\azfunc-pwsh-durable\host.json'
[2025-05-22T21:29:51.786Z] Host configuration file read:
[2025-05-22T21:29:51.787Z] {
[2025-05-22T21:29:51.789Z]   "version": "2.0",
[2025-05-22T21:29:51.790Z]   "logging": {
[2025-05-22T21:29:51.791Z]     "applicationInsights": {
[2025-05-22T21:29:51.792Z]       "samplingSettings": {
[2025-05-22T21:29:51.794Z]         "isEnabled": true,
[2025-05-22T21:29:51.796Z]         "excludedTypes": "Request"
[2025-05-22T21:29:51.797Z]       }
[2025-05-22T21:29:51.799Z]     }
[2025-05-22T21:29:51.800Z]   },
[2025-05-22T21:29:51.802Z]   "extensionBundle": {
[2025-05-22T21:29:51.803Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2025-05-22T21:29:51.805Z]     "version": "[4.*, 5.0.0)"
[2025-05-22T21:29:51.806Z]   }
[2025-05-22T21:29:51.807Z] }
[2025-05-22T21:29:51.868Z] A host error has occurred during startup operation '10849c8f-79ff-47a1-a043-eb2f01cf1f03'.
[2025-05-22T21:29:51.870Z] System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
[2025-05-22T21:29:51.870Z] File name: 'System.Net.Http.Formatting, Version=5.2.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[2025-05-22T21:29:51.871Z]    at Microsoft.Extensions.Hosting.HttpWebJobsBuilderExtensions.AddHttp(IWebJobsBuilder builder)
[2025-05-22T21:29:51.872Z]    at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_0.<AddScriptHostCore>b__1(HostBuilderContext context, IWebJobsBuilder webJobsBuilder) in /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs:line 218
[2025-05-22T21:29:51.873Z]    at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection services) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsHostBuilderExtensions.cs:line 131
[2025-05-22T21:29:51.874Z]    at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
[2025-05-22T21:29:51.874Z]    at Microsoft.Extensions.Hosting.HostBuilder.Build()
[2025-05-22T21:29:51.875Z]    at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(Boolean skipHostStartup, Boolean skipHostConfigurationParsing) in /_/src/WebJobs.Script.WebHost/DefaultScriptHostBuilder.cs:line 59
[2025-05-22T21:29:51.876Z]    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(Boolean skipHostStartup, Boolean skipHostJsonConfiguration) in /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 685
[2025-05-22T21:29:51.876Z]    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 349
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 441
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 63
[2025-05-22T21:29:51.904Z] Host startup operation has been canceled
[2025-05-22T21:29:51.905Z] Initialization cancellation requested by runtime.
[2025-05-22T21:29:51.908Z] Stopping host...
[2025-05-22T21:29:51.909Z] Host shutdown completed.
```

> dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.201 [C:\Program Files\dotnet\sdk]
6.0.302 [C:\Program Files\dotnet\sdk]
8.0.410 [C:\Program Files\dotnet\sdk]
