### ISSUE TITLE
Azure function run attempt failing

### ISSUE THREAD

**Issue by wordBoy** [Azure/azure-functions-core-tools#3100]
I am trying to run a new HTTP Trigger Azure function locally, but it is failing with the following log. I did try to add my proxy information to local.settings.json but that had no effect - however that did result in the "Skipping" notes below.

Azure Functions Core Tools
Core Tools Version:       4.0.4629 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.6.1.18388

Skipping 'http_proxy' from local settings as it's already defined in current environment variables.
Skipping 'https_proxy' from local settings as it's already defined in current environment variables.
Skipping 'no_proxy' from local settings as it's already defined in current environment variables.   
Skipping 'HTTP_PROXY' from local settings as it's already defined in current environment variables. 
Skipping 'HTTPS_PROXY' from local settings as it's already defined in current environment variables.
Skipping 'NO_PROXY' from local settings as it's already defined in current environment variables.   

Functions:

        HttpTrigger_gb1175_1: [GET,POST] http://localhost:7071/api/HttpTrigger_1

For detailed output, run func with --verbose flag.
[2022-07-13T17:21:47.939Z] Debugger listening on ws://127.0.0.1:9229/f36dc89c-aceb-4f0a-bf7d-d783493e95af
[2022-07-13T17:21:47.942Z] For help, see: https://nodejs.org/en/docs/inspector
[2022-07-13T17:21:48.247Z] [error] Worker 33556106-36fd-4a5f-b1f7-a6511b4b0e54 encountered event stream error:  Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
[2022-07-13T17:21:48.250Z] [error] Worker 33556106-36fd-4a5f-b1f7-a6511b4b0e54 uncaught exception: Error: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error     at l.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:39975)     at l.emit (node:events:390:28)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82395)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[2022-07-13T17:21:48.251Z]     at Object.t.callErrorFromStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:56820)
[2022-07-13T17:21:48.255Z]     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82410)
[2022-07-13T17:21:48.256Z]     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)
[2022-07-13T17:21:48.257Z]     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889
[2022-07-13T17:21:48.258Z]     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
[2022-07-13T17:21:48.259Z] Language Worker Process exited. Pid=6480.
[2022-07-13T17:21:48.259Z]   code: 13,
[2022-07-13T17:21:48.260Z] node exited with code 1 (0x1).     at Object.t.callErrorFromStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:56820),  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',,LanguageWorkerConsoleLog[error] Worker 33556106-36fd-4a5f-b1f7-a6511b4b0e54 uncaught exception: Error: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error     at l.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:39975)     at l.emit (node:events:390:28)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82395)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889     at processTicksAndRejections (node:internal/process/task_queues:78:11).
[2022-07-13T17:21:48.261Z]   details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
[2022-07-13T17:21:48.264Z]   metadata: u { internalRepr: Map(0) {}, options: {} }
[2022-07-13T17:21:48.264Z] }
[2022-07-13T17:21:48.277Z] Failed to start a new language worker for runtime: node.
[2022-07-13T17:21:48.279Z] System.Private.CoreLib: A task was canceled.
[2022-07-13T17:21:48.403Z] Debugger listening on ws://127.0.0.1:9229/1d5067a6-fef2-493e-b89a-05037a6ad827
[2022-07-13T17:21:48.406Z] For help, see: https://nodejs.org/en/docs/inspector
[2022-07-13T17:21:48.707Z] [error] Worker 51fa7e95-afdc-48a2-91ea-312973531b3d encountered event stream error:  Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
[2022-07-13T17:21:48.710Z] [error] Worker 51fa7e95-afdc-48a2-91ea-312973531b3d uncaught exception: Error: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error     at l.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:39975)     at l.emit (node:events:390:28)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82395)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[2022-07-13T17:21:48.710Z]     at Object.t.callErrorFromStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:56820)
[2022-07-13T17:21:48.714Z]     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82410)
[2022-07-13T17:21:48.715Z]     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)
[2022-07-13T17:21:48.716Z]     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889
[2022-07-13T17:21:48.718Z]     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
[2022-07-13T17:21:48.718Z] Language Worker Process exited. Pid=4584.
[2022-07-13T17:21:48.720Z]   code: 13,
[2022-07-13T17:21:48.720Z] node exited with code 1 (0x1).     at Object.t.callErrorFromStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:56820),  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',,LanguageWorkerConsoleLog[error] Worker 51fa7e95-afdc-48a2-91ea-312973531b3d uncaught exception: Error: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error     at l.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:39975)     at l.emit (node:events:390:28)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82395)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889     at processTicksAndRejections (node:internal/process/task_queues:78:11).
[2022-07-13T17:21:48.721Z]   details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
[2022-07-13T17:21:48.723Z]   metadata: u { internalRepr: Map(0) {}, options: {} }
[2022-07-13T17:21:48.724Z] }
[2022-07-13T17:21:52.761Z] Host lock lease acquired by instance ID '0000000000000000000000001DADB7AD'.
[2022-07-13T17:21:58.813Z] Debugger listening on ws://127.0.0.1:9229/bd67d2e5-47c0-44a3-810e-678ed7d2a070
[2022-07-13T17:21:58.815Z] For help, see: https://nodejs.org/en/docs/inspector
[2022-07-13T17:21:59.117Z] [error] Worker 86d28181-ccb4-4e6d-a578-b9d2a3eaa72b encountered event stream error:  Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
[2022-07-13T17:21:59.119Z]     at Object.t.callErrorFromStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:56820)
[2022-07-13T17:21:59.119Z] [error] Worker 86d28181-ccb4-4e6d-a578-b9d2a3eaa72b uncaught exception: Error: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error     at l.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:39975)     at l.emit (node:events:390:28)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82395)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[2022-07-13T17:21:59.120Z]     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82410)
[2022-07-13T17:21:59.123Z]     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)
[2022-07-13T17:21:59.124Z]     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889
[2022-07-13T17:21:59.125Z]     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
[2022-07-13T17:21:59.127Z]   code: 13,
[2022-07-13T17:21:59.128Z]   details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
[2022-07-13T17:21:59.129Z] Language Worker Process exited. Pid=10616.
[2022-07-13T17:21:59.130Z]   metadata: u { internalRepr: Map(0) {}, options: {} }
[2022-07-13T17:21:59.131Z] node exited with code 1 (0x1).     at Object.t.callErrorFromStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:56820),  details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',,LanguageWorkerConsoleLog[error] Worker 86d28181-ccb4-4e6d-a578-b9d2a3eaa72b uncaught exception: Error: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error     at l.<anonymous> (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:39975)     at l.emit (node:events:390:28)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:82395)     at Object.onReceiveStatus (C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:74778)     at C:\Program Files\Microsoft\Azure Functions Core Tools\workers\node\dist\src\worker-bundle.js:2:47889     at processTicksAndRejections (node:internal/process/task_queues:78:11).
[2022-07-13T17:21:59.132Z] }
[2022-07-13T17:21:59.134Z] Exceeded language worker restart retry count for runtime:node. Shutting down and proactively recycling the Functions Host to recover

**Comment by jonasgrunert** [comment]
Are there any updates regarding this? I encounter the same error on an WSL2 Systema fter freshly installing for version:
```
Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554
```
Can I provide any addtional input, that helps resolving this issue?

**Comment by timtucker-dte** [comment]
Following since I'm seeing it sometimes locally as well.

**Comment by aviita** [comment]
This is just a wild guess, but since you mentioned only fiddling with proxy settings from the app settings and prints seem to state they are skipped, are you missing localhost from NO_PROXY? So do you have something in `NO_PROXY`  env, but not this localhost stuff?

I do this in powershell to be able to do `dotnet run`:
```powershell
$env:NO_PROXY="$env:NO_PROXY,localhost,127.0.0.1"
```
