### ISSUE TITLE
worker-bundle.js fromTypedData trying to convert a string to JSON

### ISSUE THREAD

**Issue by saramoji** [Azure/azure-functions-core-tools#3166]
When trying to run azure functions locally I see an exception thrown from the node module (v 12.22.0) in worker-bundle.js, fromTypedData function, when converting a string to json. Screenshot below shows the stack trace. As a result the functions fail repeatedly.

![image](https://user-images.githubusercontent.com/109306710/194464579-fdc5e75f-d79f-4eda-9a15-766c3ed924a9.png)

Azure Functions Core Tools
Core Tools Version:       3.0.4727 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.11.0.0

Logs:
[2022-10-07T03:33:11.599Z] 6e4cb571-86a8-4a13-b163-d525a367a71a: Function 'ExecuteOperations (Activity)' failed with an error. Reason: System.Exception:  Error: Message: {"errors":[{"severity":"Error","location":{"start":104,"end":105},"code":"SC2001","message":"Identifier 'm' could not be resolved."}]}
[2022-10-07T03:33:11.600Z] ActivityId: f004b4c6-2a63-4dba-b33f-95600830c10e, Microsoft.Azure.Documents.Common/2.14.0
[2022-10-07T03:33:11.601Z]  ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: Error: Message: {"errors":[{"severity":"Error","location":{"start":104,"end":105},"code":"SC2001","message":"Identifier 'm' could not be resolved."}]}
[2022-10-07T03:33:11.603Z] ActivityId: f004b4c6-2a63-4dba-b33f-95600830c10e, Microsoft.Azure.Documents.Common/2.14.0
Stack: Error: Message: {"errors":[{"severity":"Error","location":{"start":104,"end":105},"code":"SC2001","message":"Identifier 'm' could not be resolved."}]}
[2022-10-07T03:33:11.604Z] ActivityId: f004b4c6-2a63-4dba-b33f-95600830c10e, Microsoft.Azure.Documents.Common/2.14.0
    at httpRequest (C:\Users\SaraMoji\Repos\messaging\messaging\node_modules\@azure\cosmos\dist\index.js:7779:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async execute (C:\Users\SaraMoji\Repos\messaging\messaging\node_modules\@azure\cosmos\dist\index.js:7614:26)
    at async ClientContext.queryFeed (C:\Users\SaraMoji\Repos\messaging\messaging\node_modules\@azure\cosmos\dist\index.js:8203:26)
    at async DefaultQueryExecutionContext.fetchMore (C:\Users\SaraMoji\Repos\messaging\messaging\node_modules\@azure\cosmos\dist\index.js:2128:30)
    at async QueryIterator.fetchNext (C:\Users\SaraMoji\Repos\messaging\messaging\node_modules\@azure\cosmos\dist\index.js:4045:24)
[2022-10-07T03:33:11.606Z]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in D:\a\_work\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 96
[2022-10-07T03:33:11.607Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in D:\a\_work\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 82
[2022-10-07T03:33:11.607Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in D:\a\_work\1\s\src\WebJobs.Script\Description\FunctionGenerator.cs:line 225
[2022-10-07T03:33:11.608Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[2022-10-07T03:33:11.609Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) 
in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581
[2022-10-07T03:33:11.611Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
[2022-10-07T03:33:11.612Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
[2022-10-07T03:33:11.613Z]    --- End of inner exception stack trace ---. IsReplay: False. State: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.7.2. SequenceNumber: 12. TaskEventId: 1

**Comment by ejizba** [comment]
I don't think the screenshot is the same as the error in your strack trace. The full code for your screenshot looks like this:
```
try {
    if (str != null) {
        str = JSON.parse(str);
    }
} catch (err) {}
```
The error that is thrown is immediately caught and ignored. You might see it when debugging, but you'd never see it when actually running the code.

It looks like perhaps your error is originating from here instead?
at httpRequest (C:\Users\SaraMoji\Repos\messaging\messaging\node_modules@azure\cosmos\dist\index.js:7779:31)
