### ISSUE TITLE
System.Exception: Cannot find the Local Application Data.

### ISSUE THREAD

**Issue by ValtechRickyJiang** [Azure/azure-functions-core-tools#3221]
Enviroment:
Hardware: Mac M1
Dockerfile: FROM --platform=linux/amd64 centos:7

When i am trying to execute "func start" in my container, the error System.Exception: Cannot find the Local Application Data. occurs.
The full error stack log is:

System.Exception: Cannot find the Local Application Data.
   at Azure.Functions.Cli.Utilities.EnsureCoreToolsLocalData() in D:\a\_work\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 180
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.VerifyOrSetDefaultStorageDirectoryPath(String desireStorageDirectoryPath) in D:\a\_work\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 96
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.Init(String storageDirectoryPath) in D:\a\_work\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 76
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.PersistenceChannel..ctor(String storageDirectoryPath, Int32 sendersCount) in D:\a\_work\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\PersistenceChannel.cs:line 41
   at Azure.Functions.Cli.Telemetry.Telemetry.InitializeTelemetry() in D:\a\_work\1\s\src\Azure.Functions.Cli\Telemetry\Telemetry.cs:line 93
> python3 --version
> python --version
> python3.6 --version
> python3.7 --version
> python3.8 --version
> python3.9 --version
Found Python version 3.9.6 (python3).
languageWorkers:python:defaultExecutablePath is set to python3

Azure Functions Core Tools
Core Tools Version:       4.0.4483 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473

System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.BuildWebHost(ScriptApplicationHostOptions hostOptions, Uri listenAddress, Uri baseAddress, X509Certificate2 certificate) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 205
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 371
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64

**Comment by mateoZeppelin** [comment]
Hey, I know this is kind of old, but did you manage to solve this problem?
I updated node version of my project and I'm facing lots of problems I'm solving one by one. 
But this one is getting hard to solve.
Any tips?

**Comment by ValMobRJiang** [comment]
> 

Yes, with the latest version of docker desktop and "Use Rosetta for x86/amd64 emulation on Apple Silicon" function, azure function can be run in container on M1 chip macbook. Hope this will solve your problem
