### ISSUE TITLE
Unhandled exception. System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by SofRPMI** [Azure/azure-functions-core-tools#3282]
Hello,
I'm currently facing an issue while trying to debug my function app in visual studio 2022.
I do not have the issue when running in release mode or running the deployed version

I keep on getting the following error:

> Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
> at Interop.Kernel32.CloseHandle(IntPtr handle)
> at Microsoft.Win32.SafeHandles.SafeWaitHandle.ReleaseHandle()
> at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
> at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
> at System.Runtime.InteropServices.SafeHandle.Finalize()
> 
> C:\Users\xxxxxxxxx\AppData\Local\AzureFunctionsTools\Releases\4.30.0\cli_x64\func.exe (process 31092) exited with code 0.

After some investigations, it seems like VS fails to load some symbols in 

> C:\Users\xxxxxx\AppData\Local\AzureFunctionsTools\Releases\4.30.0\cli_x64
> For instance:
> C:\Users\xxxxxxxxxxx\AppData\Local\AzureFunctionsTools\Releases\4.30.0\cli_x64\System.Private.CoreLib.pdb: Cannot find or open the PDB file.
> C:\Users\xxxxxxxxxxx\AppData\Local\AzureFunctionsTools\Releases\4.30.0\cli_x64\System.Private.CoreLib.pdb: Cannot find or open the PDB file

I have been googling for a while now but I can't seem to find the root cause and how to fix it.
Have you had this issue before?
Could you direct me to some documentation or anything that could help?

I've check all the versions and I'm using the latest version of VS 2022 and AzureFunctionsTools (x64)

Please let me know if you need more details.

Thanks for your help.

Kind regards,
Sofiane

**Comment by SofRPMI** [comment]
When I enable the native code debugging on my Function App project I get the following I get the following on the ".Net Finalizer" thread:

> Exception thrown at 0x00007FF832790FCA (ntdll.dll) in func.exe: 0xC0000008: An invalid handle was specified.

**Comment by SofRPMI** [comment]
I'm using the following settings:

> Azure Functions Core Tools
> Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
> Function Runtime Version: 4.14.0.19631

**Comment by SofRPMI** [comment]
I've managed to get to the bottom of it. All of my issues were caused by cancellationTokens I was passing down from orchestrations to activities and/or sub-orchestration. I'm no expert on the tokens life cycle but it seems it gets cleaned up faster in debug mode...
In the end, removing it fixes the SEHException.
