### ISSUE TITLE
Node 18 error: spawn Unknown system error -8

### ISSUE THREAD

**Issue by mannuelf** [Azure/azure-functions-core-tools#3340]
I experience an error running `"azure-functions-core-tools": "^4.0.5095"` with Node 18.

**CPU:** Apple M1
**OS:** macOS 13.3.1 22E261 x86_64

**NODE:** v18.16.0
**NPM:** 9.5.0

**ARCH:**  
- i386 and 
- arm64

**node -p process.arch:** 
- x64 and 
- arm64

Does azure-core-tools support Node 18?

**ERROR:** 
```bash
func start --port 8080 --script-root dist --javascript

node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at main (/Users/mannuelferreira/workspace/my-fancy-website/node_modules/azure-functions-core-tools/lib/main.js:9:22)
    at Object.<anonymous> (/Users/mannuelferreira/workspace/my-fancy-website/node_modules/azure-functions-core-tools/lib/main.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}

Node.js v18.16.0
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at main (/Users/mannuelferreira/workspace/my-fancy-website/node_modules/azure-functions-core-tools/lib/main.js:9:22)
    at Object.<anonymous> (/Users/mannuelferreira/workspace/my-fancy-website/node_modules/azure-functions-core-tools/lib/main.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}

Node.js v18.16.0
ERROR: "start:data-app" exited with 1.
```

**Comment by mannuelf** [comment]
Thank you very much @ejizba this worked for us 🤘
