### ISSUE TITLE
Error calling sync triggers

### ISSUE THREAD

**Issue by Porges** [Azure/azure-functions-core-tools#3522]
This was previously discussed in #1457.

I'm trying to update a function app to .NET 8.0.

My deployment is failing as follows:

```
Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest). Request ID = '706bb4a9-9523-4e14-9cda-ba84fe140e33'.
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\_work\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 27
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 529
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 513
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 213
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
WARNING:deploy:function failed to deploy, waiting 60 seconds and trying again
Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest). Request ID = '1dfbbbab-5f78-40ea-be05-dd5cfd230faf'.
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\_work\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 27
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 529
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 513
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 213
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
WARNING:deploy:function failed to deploy, waiting 60 seconds and trying again
Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest). Request ID = 'e94690f7-c90d-4cbe-bb20-23436fcc5351'.
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\_work\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 27
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 529
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 513
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 213
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64
```

I'm running with `--verbose` and `CLI_DEBUG=1` but that’s all the information I get.

In the Azure portal, I can see the function app and it seems to be running (live logs shows it grabbing the blob lease). There are no requests showing up in Application Insights.

**Comment by paulducks** [comment]
This started happening to me as well today. I am trying to deploy to a Python 3.10 function app in West US 2. I am deploying from cli with the command ` func azure functionapp publish GameIngestorPriority1-Dev`. Deployment proceeds as normal until the the syncing triggers step. At that point I see:
```
(quackers-jobs) C:\data\repos\game-ingestor [feature/monthly-game-watcher ≡]> func azure functionapp publish GameIngestorPriority1-Dev

...

Resetting all workers for gameingestorpriority1-dev.azurewebsites.net
Deployment successful. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Remote build succeeded!
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = '60d409bf-a14c-4cca-9914-0bd940e8bfde'.
```
I set `$env:CLI_DEBUG=1` and this is the error the client is experiencing.  This is the output when the error occurs:

```Request:
Method: POST, RequestUri: 'https://management.azure.com/subscriptions/1d560c12-339c-4485-a73f-8bd95cd6f144/resourceGroups/ana_hockey_ops_staging/providers/Microsoft.Web/sites/GameIngestorPriority1-Dev/host/default/sync?api-version=2015-08-01', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSIsImtpZCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80YmUwNjRlNS1hYjkzLTRlNDQtYjZjZC0zOTA3ZGYwYmEyMWMvIiwiaWF0IjoxNzAwMDA2MTQ2LCJuYmYiOjE3MDAwMDYxNDYsImV4cCI6MTcwMDAxMTQyNSwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhWQUFBQTduYnZmQ2FaK0JsY2l3dHh4cHM0cEdYa0wzRWlmS0R3c1ZkSTFLSmRoWEx4T2hFRGZMaEVTUmRpK3VDR01RRFFRVzNNRDBndERJLzJyYVFvSlVkWkQwMzR2dTU3d0Z1M055NHlJQU1zN1dFPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJjYXBvbGlkc19sYXRlYmluZCI6WyJjMTBlOWJjNC1lYjMzLTQ0ZmUtOWVjYi1hODM1Y2FjZGVjYmYiXSwiZmFtaWx5X25hbWUiOiJQaWdnb3R0IiwiZ2l2ZW5fbmFtZSI6IlBhdWwiLCJncm91cHMiOlsiY2IzZTU3MDUtY2QwYS00YjU0LTk5YWQtZmE2Nzc4NmE2YTk5IiwiNmU4OTJhMjEtMGU1OC00NzQ4LWE5YTAtMGIwOTMyNzQ5OGJiIiwiNjM0YTZhMjktMjg0Yy00ODQ5LTllZTAtZTc4MDhmYmNjYTJhIiwiYTY1YTQ2NDctNTZkYi00MDE3LTlhYjAtYTFkZDY0MWY4NjQ5IiwiY2YyZTc4YjYtNmQyMS00M2FmLWJjZGYtMWI1ODdjMmI4MTk4IiwiN2M5MGI3YmItMzVkYS00MjhhLWIyNDgtZWZhYzVlZGU0YWNlIiwiMmFhMjhlYmMtM2U0My00MTZkLTg0NTAtMDIxZDNhNWJiMDgzIiwiNjgxZGI3YzktMzYyNC00MDM2LWEzMjMtZTMwNjMxZTIyNzM1IiwiOGI2ZGYyZGMtZmYyOC00ZjczLTlhMmItNTZhZmM2M2M2NTYzIiwiZDZiZThjZjUtZDAyNi00OWM0LTkzYzYtYWIxNTE2ZTk3ZDZhIl0sImlkdHlwIjoidXNlciIsImlwYWRkciI6IjE0Mi4xODIuMTcxLjIwNyIsIm5hbWUiOiJQYXVsIFBpZ2dvdHQiLCJvaWQiOiJiNGEzNzY0ZC0zNDVjLTRiZmUtYjk1OC1hZGViNTcxNTIwYWIiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTAwNTk0MTc2NS0zOTk3MTM4MjY5LTIxNjE2ODE0NDUtMTMzNDIiLCJwdWlkIjoiMTAwMzIwMDI5RENBRjYwNyIsInJoIjoiMC5BUndBNVdUZ1M1T3JSRTYyelRrSDN3dWlIRVpJZjNrQXV0ZFB1a1Bhd2ZqMk1CTWNBTkUuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiU0lPSDB5Z2czVWkwNk9FWXVOV2NYQkhKSjNkNW1LcjVPOTRQbEFNd0VWQSIsInRpZCI6IjRiZTA2NGU1LWFiOTMtNGU0NC1iNmNkLTM5MDdkZjBiYTIxYyIsInVuaXF1ZV9uYW1lIjoicHBpZ2dvdHRAYW5haGVpbWR1Y2tzLmNvbSIsInVwbiI6InBwaWdnb3R0QGFuYWhlaW1kdWNrcy5jb20iLCJ1dGkiOiJhb0RKdzhNUk9rT0RaLVNTUC0yTUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2NhZSI6IjEiLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19maWx0ZXJfaW5kZXgiOlsiMjgiXSwieG1zX3JkIjoiMC40MkxsWUJSaWxBRUEiLCJ4bXNfc3NtIjoiMSIsInhtc190Y2R0IjoxNDgyMzU4Mzc5fQ.ZdkQsm8O_2mMzcQYJlgSUFtjc7cqfrtPHYRHVV6xmvL0BlPalY0TxnJWt2j0H4Ja0SgIlAtwyp8NO6HrO711lP2ULQS3Ph9xC8DxHNSuoKI9DX57MxPcWWbbY4MD9eP-_aOvGCZ3ja25vGm4cTXVQtQLb2zgpEh9w8DXGTOJvCDzedDbDmcauhdds-qyjgTHrNQzw7hZ6UV1zJzJESjmITwlmHtedFc25iAJ0Zs4QkjA5qflACaTYvBC_e-dCEnshGL0877C625ZDnkekN5BME31oFFLLawIOzu5bO9miP560MaIgIWEIfm9FJWENkRBk9-uNfO6NZ_TdqvzPDCH_g
  User-Agent: functions-core-tools/4.0.5198
  Accept: application/json
  x-ms-request-id: 339d0001-a9e3-4ce2-bfc1-486134954117
  Content-Type: application/json; charset=utf-8
}
null

Response:
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Server: Microsoft-IIS/10.0
  X-AspNet-Version: 4.0.30319
  X-Powered-By: ASP.NET
  x-ms-ratelimit-remaining-subscription-writes: 1199
  x-ms-request-id: 62293244-93ec-497b-8296-2e968baafe16
  x-ms-correlation-request-id: 62293244-93ec-497b-8296-2e968baafe16
  x-ms-routing-request-id: CANADACENTRAL:20231115T000210Z:62293244-93ec-497b-8296-2e968baafe16
  X-Content-Type-Options: nosniff
  Date: Wed, 15 Nov 2023 00:02:10 GMT
  Content-Length: 346
  Content-Type: application/json; charset=utf-8
  Expires: -1
}
{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}


Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest). Request ID = '62293244-93ec-497b-8296-2e968baafe16'.
   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\_work\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 27
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 519
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 503
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\_work\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 209
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\_work\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 64```

My app has a single function that is triggered by Service Bus. I checked the queue this function listens to. It has 78 messages on it. So I checked the activity on the queue. The last time a message was processed by the function was 3:37PM EST on 2023-11-13. Then I checked the logs in Application Insights (not just the logs my code is writing, but all traces including the system ones). Selecting all traces reveals that the last message published to Application Insights (by any code) was also at 3:37 PM EST on 2023-11-13. Since then, no traces.

This leads me to believe the app is somehow dead? I tried stopping it and restarting it in the Portal. I didn't get any error messages for either action. But this had no effect. Any help would be greatly appreciated. This is occurring on the dev instance of this function app. The production instance is still operating normally. It would be soothing to know the cause, such that it won't affect my production environment.

**Comment by Porges** [comment]
Without me doing anything, this randomly started working today.

**Comment by paulducks** [comment]
I opened a support ticket with the Microsoft Azure team last week. Took them a few days to track down the issue, but they informed me it was a hardware configuration issue affecting multiple applications in the West US 2 region. A fix was deployed Friday and my issues were resolved soon after. Not sure if your thing is related or not.

**Comment by gfbassous** [comment]
Having the same in Brazil South with premium plan. Consumption was working this morning, but premium, not.

**Comment by mikekistler** [comment]
I just hit the same problem with an Azure Functions deployment in South Central US.

**Comment by infobrixGit** [comment]
I am facing the same issue - UK South , UK West
[2024-05-01T06:12:50.307Z] Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = 'd74b3165-
How can the key features like publish stop working?

**Comment by codebrane** [comment]
is this going to be fixed? UK West:

`func azure functionapp publish TheDurableFunctionOrchestration`

```
Getting site publishing info...
[2024-08-14T14:12:27.679Z] Starting the function app deployment...
Creating archive for current directory...
Uploading 32.71 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
[2024-08-14T14:14:53.797Z] Syncing triggers...
[2024-08-14T14:14:57.375Z] Syncing triggers...
[2024-08-14T14:15:00.600Z] Syncing triggers...
[2024-08-14T14:15:18.809Z] Syncing triggers...
[2024-08-14T14:15:22.196Z] Syncing triggers...
[2024-08-14T14:15:25.551Z] Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = '....

```

every time.

**Comment by codebrane** [comment]
It started working after I checked the wiring. The function app is using a user assigned managed identity to access its key vault using RBAC and the Key Vault Secrets User role but it had been set up as a "User, group, or service principal" in the key vault. I set it up as a "Managed identity" and it looked better. It still failed to deploy but now with a 500 internal server error from Azure. It initially failed to deploy anything so I stopped the function app and it then got as far as the 401 error. To get rid of the 500 error I had to restart the function app and deploying now works.

So it seemed there were two issues. The wiring to the key vault and the fact the deployment infrastructure had failed due to not being able to stop the running function app in the first place.
