### ISSUE TITLE
Azure set-azcontext from PowerShell Az.Accounts 2.13.2 cannot be used in VSCode with Azure Functions Core Tools

### ISSUE THREAD

**Issue by ehuggz1** [Azure/azure-functions-core-tools#3562]
**Summary**

Ran into an issue in VSCode when setting a Subscription context using the latest AZ 11.1.0 module or the Az.Accounts dependency 2.13.2 within powershell code inside a powershell function app.

Setting the context within an Azure Function PowerShell Script caused nothing to be returned and produces an error message on the PowerShell Function Host Screen.
Running set-azcontext from a PS7 console works without issue.

Pinning the Az.Accounts version to 2.11.2 used in Az 9.* resolved the issue.
I was previously using AZ 9.* successfully and did not test Az 10.* due to time constraints.

**Steps to Replicate**
- Open VSCode 
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.23606

- Core Function Tools v 4.0.4915
- Successfully authenticate to Azure via Azure Accounts extension
- Require Az.Accounts 2.13.2 or Import-Module Az.Accounts -RequiredVersion 2.13.2 in powershell function code
- Use set-context -Subscription <SubscriptionName> to set Subscription context from within Azure PowerShell Function Code.

**Observed Behavior**
set-azcontext -Subscription <SubscriptionName> returns $null.
Powershell Function Host screen displays errors:
[2023-12-29T15:50:57.914Z] ERROR: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.916Z]
[2023-12-29T15:50:57.917Z] Exception             :
[2023-12-29T15:50:57.918Z]     Type       : System.IO.FileLoadException
[2023-12-29T15:50:57.919Z]     Message    : Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.920Z]     TargetSite :
[2023-12-29T15:50:57.921Z]         Name          : Bind_LoadAssemblies
[2023-12-29T15:50:57.922Z]         DeclaringType : initialsessionstate
[2023-12-29T15:50:57.923Z]         MemberType    : Method
[2023-12-29T15:50:57.924Z]         Module        : System.Management.Automation.dll
[2023-12-29T15:50:57.926Z]     StackTrace :
[2023-12-29T15:50:57.927Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
[2023-12-29T15:50:57.928Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
[2023-12-29T15:50:57.929Z]    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
[2023-12-29T15:50:57.930Z]     Source     : System.Management.Automation
[2023-12-29T15:50:57.933Z]     HResult    : -2146232799
[2023-12-29T15:50:57.934Z] CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
[2023-12-29T15:50:57.935Z] FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
[2023-12-29T15:50:57.936Z] InvocationInfo        :
[2023-12-29T15:50:57.939Z]     MyCommand        : Import-Module
[2023-12-29T15:50:57.940Z]     ScriptLineNumber : 525
[2023-12-29T15:50:57.941Z]     OffsetInLine     : 1
[2023-12-29T15:50:57.942Z]     HistoryId        : 17
[2023-12-29T15:50:57.943Z]     ScriptName       : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.944Z]     Line             : Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.945Z]
[2023-12-29T15:50:57.946Z]     PositionMessage  : At D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1:525 char:1
[2023-12-29T15:50:57.948Z]                        + Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.950Z]                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-12-29T15:50:57.951Z]     PSScriptRoot     : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7
[2023-12-29T15:50:57.952Z]     PSCommandPath    : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.953Z]     InvocationName   : Import-Module
[2023-12-29T15:50:57.954Z]     CommandOrigin    : Internal
[2023-12-29T15:50:57.955Z] ScriptStackTrace      : at <ScriptBlock>, D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1: line 525      
[2023-12-29T15:50:57.957Z]
[2023-12-29T15:50:57.958Z]
[2023-12-29T15:50:57.959Z] Result: ERROR: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.960Z]
[2023-12-29T15:50:57.960Z] Exception             :
[2023-12-29T15:50:57.961Z]     Type       : System.IO.FileLoadException
[2023-12-29T15:50:57.963Z]     Message    : Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.964Z]     TargetSite :
[2023-12-29T15:50:57.965Z]         Name          : Bind_LoadAssemblies
[2023-12-29T15:50:57.966Z]         DeclaringType : initialsessionstate
[2023-12-29T15:50:57.967Z]         MemberType    : Method
[2023-12-29T15:50:57.969Z]         Module        : System.Management.Automation.dll
[2023-12-29T15:50:57.970Z]     StackTrace :
[2023-12-29T15:50:57.971Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
[2023-12-29T15:50:57.972Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
[2023-12-29T15:50:57.973Z]    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
[2023-12-29T15:50:57.975Z]     Source     : System.Management.Automation
[2023-12-29T15:50:57.976Z]     HResult    : -2146232799
[2023-12-29T15:50:57.977Z] CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
[2023-12-29T15:50:57.978Z] FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
[2023-12-29T15:50:57.979Z] InvocationInfo        :
[2023-12-29T15:50:57.980Z]     MyCommand        : Import-Module
[2023-12-29T15:50:57.981Z]     ScriptLineNumber : 525
[2023-12-29T15:50:57.982Z]     OffsetInLine     : 1
[2023-12-29T15:50:57.983Z]     HistoryId        : 17
[2023-12-29T15:50:57.984Z]     ScriptName       : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.986Z]     Line             : Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.987Z]
[2023-12-29T15:50:57.988Z]     PositionMessage  : At D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1:525 char:1
[2023-12-29T15:50:57.989Z]                        + Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.990Z]                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-12-29T15:50:57.991Z]     PSScriptRoot     : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7
[2023-12-29T15:50:57.995Z]     PSCommandPath    : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.996Z]     InvocationName   : Import-Module
[2023-12-29T15:50:57.996Z]     CommandOrigin    : Internal
[2023-12-29T15:50:57.998Z] ScriptStackTrace      : at <ScriptBlock>, D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1: line 525      
[2023-12-29T15:50:57.999Z]
[2023-12-29T15:50:57.999Z]
Exception: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.  
Stack:    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
[2023-12-29T15:50:58.006Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
[2023-12-29T15:50:58.040Z]    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors).
[2023-12-29T15:50:57.914Z] ERROR: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.916Z]
[2023-12-29T15:50:57.917Z] Exception             :
[2023-12-29T15:50:57.918Z]     Type       : System.IO.FileLoadException
[2023-12-29T15:50:57.919Z]     Message    : Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.920Z]     TargetSite :
[2023-12-29T15:50:57.921Z]         Name          : Bind_LoadAssemblies
[2023-12-29T15:50:57.922Z]         DeclaringType : initialsessionstate
[2023-12-29T15:50:57.923Z]         MemberType    : Method
[2023-12-29T15:50:57.924Z]         Module        : System.Management.Automation.dll
[2023-12-29T15:50:57.926Z]     StackTrace :
[2023-12-29T15:50:57.927Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
[2023-12-29T15:50:57.928Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
[2023-12-29T15:50:57.929Z]    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
[2023-12-29T15:50:57.930Z]     Source     : System.Management.Automation
[2023-12-29T15:50:57.933Z]     HResult    : -2146232799
[2023-12-29T15:50:57.934Z] CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
[2023-12-29T15:50:57.935Z] FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
[2023-12-29T15:50:57.936Z] InvocationInfo        :
[2023-12-29T15:50:57.939Z]     MyCommand        : Import-Module
[2023-12-29T15:50:57.940Z]     ScriptLineNumber : 525
[2023-12-29T15:50:57.941Z]     OffsetInLine     : 1
[2023-12-29T15:50:57.942Z]     HistoryId        : 17
[2023-12-29T15:50:57.943Z]     ScriptName       : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.944Z]     Line             : Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.945Z]
[2023-12-29T15:50:57.946Z]     PositionMessage  : At D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1:525 char:1
[2023-12-29T15:50:57.948Z]                        + Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.950Z]                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-12-29T15:50:57.951Z]     PSScriptRoot     : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7
[2023-12-29T15:50:57.952Z]     PSCommandPath    : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.953Z]     InvocationName   : Import-Module
[2023-12-29T15:50:57.954Z]     CommandOrigin    : Internal
[2023-12-29T15:50:57.955Z] ScriptStackTrace      : at <ScriptBlock>, D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1: line 525      
[2023-12-29T15:50:57.957Z]
[2023-12-29T15:50:57.958Z]
[2023-12-29T15:50:57.959Z] Result: ERROR: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.960Z]
[2023-12-29T15:50:57.960Z] Exception             :
[2023-12-29T15:50:57.961Z]     Type       : System.IO.FileLoadException
[2023-12-29T15:50:57.963Z]     Message    : Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-29T15:50:57.964Z]     TargetSite :
[2023-12-29T15:50:57.965Z]         Name          : Bind_LoadAssemblies
[2023-12-29T15:50:57.966Z]         DeclaringType : initialsessionstate
[2023-12-29T15:50:57.967Z]         MemberType    : Method
[2023-12-29T15:50:57.969Z]         Module        : System.Management.Automation.dll
[2023-12-29T15:50:57.970Z]     StackTrace :
[2023-12-29T15:50:57.971Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
[2023-12-29T15:50:57.972Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
[2023-12-29T15:50:57.973Z]    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
[2023-12-29T15:50:57.975Z]     Source     : System.Management.Automation
[2023-12-29T15:50:57.976Z]     HResult    : -2146232799
[2023-12-29T15:50:57.977Z] CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
[2023-12-29T15:50:57.978Z] FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
[2023-12-29T15:50:57.979Z] InvocationInfo        :
[2023-12-29T15:50:57.980Z]     MyCommand        : Import-Module
[2023-12-29T15:50:57.981Z]     ScriptLineNumber : 525
[2023-12-29T15:50:57.982Z]     OffsetInLine     : 1
[2023-12-29T15:50:57.983Z]     HistoryId        : 17
[2023-12-29T15:50:57.984Z]     ScriptName       : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.986Z]     Line             : Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.987Z]
[2023-12-29T15:50:57.988Z]     PositionMessage  : At D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1:525 char:1
[2023-12-29T15:50:57.989Z]                        + Import-Module -Name Az.Accounts -RequiredVersion 2.13.2
[2023-12-29T15:50:57.990Z]                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-12-29T15:50:57.991Z]     PSScriptRoot     : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7
[2023-12-29T15:50:57.995Z]     PSCommandPath    : D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1
[2023-12-29T15:50:57.996Z]     InvocationName   : Import-Module
[2023-12-29T15:50:57.996Z]     CommandOrigin    : Internal
[2023-12-29T15:50:57.998Z] ScriptStackTrace      : at <ScriptBlock>, D:\RightRezADO2\DevOps.Tools\QueryRunner7\QueryRunner7\run.ps1: line 525      
[2023-12-29T15:50:57.999Z]
[2023-12-29T15:50:57.999Z]
Exception: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.18.0.315, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.  
Stack:    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
[2023-12-29T15:50:58.006Z]    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
[2023-12-29T15:50:58.040Z]    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors).

**Temporary Fix**

- Add Az.Accounts 2.11.2 to Modules folder and require it in requirements.psd1
or

- Manually reference the version in code with Import-Module -Name Az.Accounts -RequiredVersion 2.11.2

**Comment by ehuggz1** [comment]
Resolved by upgrading from azure-core-functions-tools v 4.0.4915 to 4.0.5455
