### ISSUE TITLE
Integration tests failed with exception "The Functions Host Runtime did not start properly after 180 seconds"

### ISSUE THREAD

**Issue by hejingkan2005** [Azure/azure-functions-core-tools#4190]
### Version

Dotnet Version: 8.0.403/8.0.404
Azure Function Core Tools Version: 4.0.6594

### Description

Hit below exception in Onebranch pipeline, we don't meet this error before, and reverting to version 4.0.6543 seems mitigate the issue:

[xUnit.net 00:03:02.80]     Learn.VectorSearch.API.IntegrationTests.RelevanceApiTest.TestGetRelevantItemByText(category: QnA, input: "What is the best programming language", count: 0, expectedItemId: "", score: "") [FAIL]
  Failed Learn.VectorSearch.API.IntegrationTests.ItemSpecApiTest.TestGetItemSpecByItemId_NotExistingItem(category: QnA, contentId: "invalidId") [1 ms]
  Error Message:
   System.Exception : The Functions Host Runtime did not start properly after 180 seconds.
  Stack Trace:
     at Microsoft.Learn.AzureFunctionsTesting.FunctionFixture`1.InitializeAsync()
   at Microsoft.Docs.FunctionsIntegrationTesting.DocsFunctionFixture`1.InitializeAsync()

### Steps to reproduce

- Install Azure Function Core Tools version:  4.0.6594
- Run a pipeline relying on this version of Azure Function Core Tools
- Repro the exception in description.
- Revert to version: 4.0.6543 will resolve this.

**Comment by liliankasem** [comment]
@aishwaryabh could this be related to the other ADO issue you were looking at? https://github.com/Azure/azure-functions-core-tools/issues/4156#issuecomment-2469230570

**Comment by hejingkan2005** [comment]
@liliankasem , thank you for reference. Btw, I just verified with the latest release version 4.0.6610, unfortunately it looks the same issue.

**Comment by ksgopal4** [comment]
We have same issue, integration tests fail as `func start` no longer works. Output seems to indicate that func start needs more information
```
 Select a number for worker runtime:
1. dotnet (isolated worker model)
2. dotnet (in-process model)
3. node
4. python
5. powershell
6. custom
```

**Comment by dffisker** [comment]
We have the exact the same issue here where integration tests will fail with runtime not being able to start with the timeout. Both in 4.0.6594 and 4.0.6610. Running 4.0.6543 resolves this.

Any news on this issue?

**Comment by liliankasem** [comment]
It looks like there was a regression where environment variables were no longer being checked, this has been fixed in [this](https://github.com/Azure/azure-functions-core-tools/pull/4219) PR. We're working on a hotfix to get this released asap.

**Comment by liliankasem** [comment]
Hot fix is out (v4.6821) - closing this issue. If you are still experiencing the issue, please open a new ticket for us to triage and investigate, thanks!
