### ISSUE TITLE
Cannot find module azurefunctions/functions.js in 1.0.10

### ISSUE THREAD

**Issue by rogersmj** [Azure/azure-functions-core-tools#426]
I'm in the process of trying to get a local Azure functions environment spun up, and I've run into something I've never run into before (this is the third machine I've setup). I'm using runtime 1.x, installed using

npm install -g azure-functions-core-tools

It installs successfully. I'm using Node 6.5.0 currently (also tried with 8.11.1, using nvm to manage node versions). On Windows 10.

I have a simple function that is getting triggered by a Service Bus topic subscription. The only thing it is currently doing is writing to the context log that it has been triggered. When I run the local function host, everything appears to start up fine. Then when I place a message in the service bus topic, causing the function to be triggered, I get tons of messages like this:

```
[4/6/2018 7:44:31 PM] Executing 'Functions.refresh-manager' (Reason='New ServiceBus message detected on 'powerbi-refresh/Subscriptions/pbimanager-refresh-manager'.', Id=0b1cc959-8956-4d3b-8470-6634144d55fc)
[4/6/2018 7:44:31 PM] A ScriptHost error has occurred
[4/6/2018 7:44:31 PM] Exception while executing function: Functions.refresh-manager. mscorlib: One or more errors occurred. Error: Cannot find module '../azurefunctions/functions.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at eval (eval at compileFunc (C:\Users\mrogers\AppData\Roaming\nvm\v6.5.0\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:34:28), <anonymous>:1:23)
    at compileFunc (C:\Users\mrogers\AppData\Roaming\nvm\v6.5.0\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:35:16).
[4/6/2018 7:44:31 PM] Exception while executing function: Functions.refresh-manager. mscorlib: One or more errors occurred. Error: Cannot find module '../azurefunctions/functions.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at eval (eval at compileFunc (C:\Users\mrogers\AppData\Roaming\nvm\v6.5.0\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:34:28), <anonymous>:1:23)
    at compileFunc (C:\Users\mrogers\AppData\Roaming\nvm\v6.5.0\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:35:16).

```

I have the .NET 4.7.1 framework installed, afaik...I tried to reinstall it and it said I couldn't because it was already installed (pretty sure it got installed with Visual Studio).

I'm using azure-functions-core-tools@1.0.10. Using Windows Explorer, I went and looked and verified that the file double_edge.js is attempting to load (../azurefunctions/functions.js) is indeed not there.

I have been unsuccessful in tracking down anyone else having this problem and I'm stumped.

**Comment by rogersmj** [comment]
I downgraded to azure-functions-core-tools@1.0.9 and it all works now. Looks like there's a bug in 1.0.10.

**Comment by reks-scripts** [comment]
@rogersmj, thank you!  Just wanted to confirm I had the same issue and downgrading to 1.0.9 resolved it for me as well.

**Comment by brugos** [comment]
@rogersmj @reks-scripts , I do confirm the same: 1.0.10 is BUGGY !!! downgraded to 1.0.9 will fix it. Bare in mind that you will need admin privileges to remove it. Just in case went to your

**Comment by fulls1z3** [comment]
@RogerBestMsft @reks-scripts @brugos I can also confirm that `v1.0.10` is **BUGGY**!

**Comment by GavinOsborn** [comment]
Yup, same problem, same fix.

**Comment by ahmelsayed** [comment]
fixed in `12`
