### ISSUE TITLE
Failed to load gRPC binary module because it was not installed for the current system

### ISSUE THREAD

**Issue by petmat** [Azure/azure-functions-core-tools#442]
I created a new Azure Functions project (runtime v1, Node.js) and added a new HttpTrigger function. I then created a package.json with npm init inside the function directory and installed an NPM module called dialogflow. This package is an SDK for using the Dialogflow service and has a dependency on a grpc binary module.

When I run the function app locally with func host start it starts without errors but when I call my HttpTrigger function I get the following error:

```
[19.4.2018 10.40.06] A ScriptHost error has occurred
[19.4.2018 10.40.06] Exception while executing function: Functions.Answer. mscorlib: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v48-win32-ia32-unknown
Found: [node-v48-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\node\extension_binary\node-v48-win32-ia32-unknown\grpc_node.node'
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\client.js:37:12)
    at Module._compile (module.js:570:32).
[19.4.2018 10.40.06] Exception while executing function: Functions.Answer. mscorlib: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v48-win32-ia32-unknown
Found: [node-v48-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\node\extension_binary\node-v48-win32-ia32-unknown\grpc_node.node'
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\client.js:37:12)
    at Module._compile (module.js:570:32).
[19.4.2018 10.40.06]
[19.4.2018 10.40.06] Exception while executing function: Functions.Answer
[19.4.2018 10.40.06] Exception while executing function: Functions.Answer. mscorlib: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v48-win32-ia32-unknown
Found: [node-v48-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\node\extension_binary\node-v48-win32-ia32-unknown\grpc_node.node'
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\client.js:37:12)
    at Module._compile (module.js:570:32).
[19.4.2018 10.40.06] Function completed (Failure, Id=039e8f5c-eda8-464e-8def-1dd0d2680b91, Duration=1112ms)
[19.4.2018 10.40.06]
[19.4.2018 10.40.06] Executed 'Functions.Answer' (Failed, Id=039e8f5c-eda8-464e-8def-1dd0d2680b91)
[19.4.2018 10.40.06] mscorlib: Exception while executing function: Functions.Answer. mscorlib: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v48-win32-ia32-unknown
Found: [node-v48-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\node\extension_binary\node-v48-win32-ia32-unknown\grpc_node.node'
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\client.js:37:12)
    at Module._compile (module.js:570:32).
[19.4.2018 10.40.06]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '039e8f5c-eda8-464e-8def-1dd0d2680b91'
[19.4.2018 10.40.06] mscorlib: Exception while executing function: Functions.Answer. mscorlib: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v48-win32-ia32-unknown
Found: [node-v48-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\node\extension_binary\node-v48-win32-ia32-unknown\grpc_node.node'
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\client.js:37:12)
    at Module._compile (module.js:570:32).
[19.4.2018 10.40.06] {"id":"041a50b9-8867-4bb0-b6b7-ddbe1e5c1c20","requestId":"7dc886e1-4e7d-450a-8142-f8a888ce8524","statusCode":500,"errorCode":0,"message":"Exception while executing function: Functions.Answer -> Error: Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v48-win32-ia32-unknown\nFound: [node-v48-win32-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module 'C:\\sandbox\\dialogflow-func-test\\Answer\\node_modules\\grpc\\src\\node\\extension_binary\\node-v48-win32-ia32-unknown\\grpc_node.node'\n    at Object.<anonymous> (C:\\sandbox\\dialogflow-func-test\\Answer\\node_modules\\grpc\\src\\grpc_extension.js:53:17)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\\sandbox\\dialogflow-func-test\\Answer\\node_modules\\grpc\\src\\client.js:37:12)\n    at Module._compile (module.js:570:32)","errorDetails":"Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.Answer ---> System.Exception : Error: Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v48-win32-ia32-unknown\nFound: [node-v48-win32-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module 'C:\\sandbox\\dialogflow-func-test\\Answer\\node_modules\\grpc\\src\\node\\extension_binary\\node-v48-win32-ia32-unknown\\grpc_node.node'\n    at Object.<anonymous> (C:\\sandbox\\dialogflow-func-test\\Answer\\node_modules\\grpc\\src\\grpc_extension.js:53:17)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (C:\\sandbox\\dialogflow-func-test\\Answer\\node_modules\\grpc\\src\\client.js:37:12)\n    at Module._compile (module.js:570:32)\r\n   at async Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context)\r\n   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) \r\n   End of inner exception\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw()\r\n   at async Microsoft.Azure.WebJobs.JobHost.CallAsync(??)\r\n   at async Microsoft.Azure.WebJobs.Script.ScriptHost.CallAsync(String method,Dictionary`2 arguments,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.HandleRequestAsync(FunctionDescriptor function,HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.Host.FunctionRequestInvoker.ProcessRequestAsync(HttpRequestMessage request,CancellationToken cancellationToken,WebScriptHostManager scriptHostManager,WebHookReceiverManager webHookReceiverManager)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<ExecuteAsync>b__0(??)\r\n   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.ProcessRequestAsync(HttpRequestMessage request,Func`3 processRequestHandler,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ExecuteAsync(HttpControllerContext controllerContext,CancellationToken cancellationToken)\r\n   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)\r\n   at async System.Web.Http.HttpServer.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)"}
[19.4.2018 10.40.06] mscorlib: Exception while executing function: Functions.Answer. mscorlib: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v48-win32-ia32-unknown
Found: [node-v48-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\node\extension_binary\node-v48-win32-ia32-unknown\grpc_node.node'
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\grpc_extension.js:53:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\sandbox\dialogflow-func-test\Answer\node_modules\grpc\src\client.js:37:12)
    at Module._compile (module.js:570:32).
```

Microsoft Windows 10 Pro
10.0.16299 Build 16299

Azure Functions Core Tools (1.0.9)
Function Runtime Version: 1.0.11535.0
Node.js version: 6.11.2

**Comment by ahmelsayed** [comment]
You'll need to do npm install from an x86 node. or use an x64 build of Azure Functions Core Tools.

**Comment by black** [comment]
I have encounter similar problem, can you help?

https://stackoverflow.com/questions/50476054/nw-js-failed-to-load-grpc-binary-module
