### ISSUE TITLE
FunctionInvocationException thrown when triggering a js HttpTrigger(template) in v1.0.11 core tool

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-core-tools#446]
I install v1.0.11 function core tool and create a httptrigger template locally.
Node: v8.11.1  OS: Windows 10

When I run the function app, it starts successfully. But when I trigger the js httptrigger(a template), exception thrown

> Exception while executing function: Functions.myjstrigger -> One or more errors occurred. -> Error: Cannot find module '../azurefunctions/functions.js' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at eval (eval at compileFunc (C:\Users\UserName\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:34:28), <anonymous>:1:23) at compileFunc (C:\Users\UserName\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:35:16)

Same error happens when I try to use js blobtrigger, but for c#, http&blob trigger both work well.

Details

> Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.myjstrigger ---> System.AggregateException : One or more errors occurred. ---> Error: Cannot find module '../azurefunctions/functions.js' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at eval (eval at compileFunc (C:\Users\UserName\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:34:28), <anonymous>:1:23) at compileFunc (C:\Users\UserName\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:35:16) at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken) at EdgeJs.Edge.Func(String code) at Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.get_GlobalInitializationFunc() at async Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.InitializeAsync() at async Microsoft.Azure.WebJobs.Script.Description.NodeFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) ---> (Inner Exception #0) System.Exception : Error: Cannot find module '../azurefunctions/functions.js' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at eval (eval at compileFunc (C:\Users\UserName\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:34:28), <anonymous>:1:23) at compileFunc (C:\Users\UserName\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\double_edge.js:35:16)<--- End of inner exception at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw() at async Microsoft.Azure.WebJobs.JobHost.CallAsync(??) at async Microsoft.Azure.WebJobs.Script.ScriptHost.CallAsync(String method,Dictionary`2 arguments,CancellationToken cancellationToken) at async Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.HandleRequestAsync(FunctionDescriptor function,HttpRequestMessage request,CancellationToken cancellationToken) at async Microsoft.Azure.WebJobs.Script.Host.FunctionRequestInvoker.ProcessRequestAsync(HttpRequestMessage request,CancellationToken cancellationToken,WebScriptHostManager scriptHostManager,WebHookReceiverManager webHookReceiverManager) at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<ExecuteAsync>b__0(??) at async Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.ProcessRequestAsync(HttpRequestMessage request,Func`3 processRequestHandler,CancellationToken cancellationToken) at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ExecuteAsync(HttpControllerContext controllerContext,CancellationToken cancellationToken) at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken) at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken) at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken) at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken) at async System.Web.Http.HttpServer.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)

**Comment by davidebbo** [comment]
This came from StackOverflow question: https://stackoverflow.com/questions/50055354/azure-functions-core-tools-throwing-error-with-default-function-cant-find-a.

**Comment by ahmelsayed** [comment]
Fixed in https://github.com/Azure/azure-functions-core-tools/commit/3f562146140929ffcda7cf4e20bda3b89563f44e 

I'm preparing an update now
