### ISSUE TITLE
Warning: Only got partial types from assembly

### ISSUE THREAD

**Issue by petarvucetin** [Azure/azure-functions-core-tools#457]
Pardon me if this is not the right place 

As of a month ago,  this worked fine. Now I am getting this error:

```
Warning: Only got partial types from assembly: MyInsight.AzureFunctions.Automation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
```

The only way to make this stop is to remove this line from my source code:

```cs
var item = await Kvclient.GetSecretAsync(builder.Uri.ToString());
```

```cs
var azureServiceTokenProvider = new AzureServiceTokenProvider();

Kvclient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback), HttpClient);
```

**Comment by vbouret** [comment]
Same issue here but with a class derived from TableEntity. Whenever I comment the TableEntity reference in a class, the error goes away. Is there any way to have more details and the content of LoaderExceptions as written in the error message?

Hosting environment: Production
Content root path: C:\Dev\Net\BasicWatch\BasicWatch\bin\Debug\netstandard2.0
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[2018-05-04 2:36:14] Reading host configuration file 'C:\Dev\Net\BasicWatch\BasicWatch\bin\Debug\netstandard2.0\host.json'
[2018-05-04 2:36:14] Host configuration file read:
[2018-05-04 2:36:14] {}
[2018-05-04 2:36:14] Starting Host (HostId=aaaaaaa, InstanceId=bc7dd0f9-0c71-44f4-b5b5-86bdb2fb795d, Version=2.0.11651.0, ProcessId=33460, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[2018-05-04 2:36:14] Unable to configure java worker. Could not find JAVA_HOME app setting.
[2018-05-04 2:36:14]
[2018-05-04 2:36:14] Could not configure language worker Java.
[2018-05-04 2:36:14]
Warning: Only got partial types from assembly: BasicWatch, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
[2018-05-04 2:36:15] Generating 0 job function(s)
[2018-05-04 2:36:15] Found the following functions:
[2018-05-04 2:36:15] BasicWatch.BasicUltimateWatch.Run
[2018-05-04 2:36:15] BasicWatch.SendMailNotification.Run
[2018-05-04 2:36:15]
[2018-05-04 2:36:15] Host initialized (1614ms)
[2018-05-04 2:36:15] Host lock lease acquired by instance ID '00000000000000000000000058B8642E'.
[2018-05-04 2:36:15] Host started (1788ms)
[2018-05-04 2:36:15] Job host started
[2018-05-04 2:36:15] The following 2 functions are in error:
[2018-05-04 2:36:15] BasicUltimateWatch: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[2018-05-04 2:36:15] SendMailNotification: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[2018-05-04 2:36:15]
[2018-05-04 2:36:15]
Listening on http://localhost:7071/
Hit CTRL-C to exit...

**Comment by ahmelsayed** [comment]
@fabiocav this looks like a runtime issue to me. Can you confirm before I move it over there?

**Comment by fabiocav** [comment]
This issue was moved to Azure/azure-functions-host#2885

**Comment by fabiocav** [comment]
@ahmelsayed it's an SDK/Host issue. Moved.

**Comment by fabiocav** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1715
