### ISSUE TITLE
Refered binary not installed with apt

### ISSUE THREAD

**Issue by prog-re** [Azure/azure-functions-core-tools#463]
When azure-functions-core-tools is installed using apt the installations does not include binaries refered by the cli:

```
Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/lib/azure-functions-core-tools/workers/node/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'
```

The directory `/azure-functions-core-tools/workers/node/grpc/src/node/extension_binary` only contains node-v57-xxxx subdirectories

This is the install 

```
(vesta)martin@localhost:~/tmp/afunc$ sudo apt install azure-functions-core-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  azure-functions-core-tools
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 0 B/53.1 MB of archives.
After this operation, 0 B of additional disk space will be used.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package azure-functions-core-tools.
(Reading database ... 96586 files and directories currently installed.)
Preparing to unpack .../azure-functions-core-tools_2.0.1~beta.25-1_amd64.deb ...
Unpacking azure-functions-core-tools (2.0.1~beta.25-1) ...
Setting up azure-functions-core-tools (2.0.1~beta.25-1) ...
```

Then I run the example javascript function

```
(vesta)martin@localhost:~/tmp/afunc$ func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Hosting environment: Production
Content root path: /home/martin/tmp/afunc
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[5/11/18 4:44:18 PM] Reading host configuration file '/home/martin/tmp/afunc/host.json'
[5/11/18 4:44:18 PM] Host configuration file read:
[5/11/18 4:44:18 PM] {}
[5/11/18 4:44:18 PM] Starting Host (HostId=localhost-2012303441, InstanceId=d710fe7f-359d-488e-9b1a-5b908418cd2a, Version=2.0.11651.0, ProcessId=13755, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[5/11/18 4:44:18 PM] Unable to configure java worker. Could not find JAVA_HOME app setting.
[5/11/18 4:44:18 PM]
[5/11/18 4:44:18 PM] Could not configure language worker Java.
[5/11/18 4:44:18 PM]
[5/11/18 4:44:19 PM] Start Process: node  --inspect=5858 "/usr/lib/azure-functions-core-tools/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 44308 --workerId 6725201b-a989-49d3-8f80-445cbcc3c8af --requestId 93574187-c59d-4bf6-a996-46ffc672d0ae
[5/11/18 4:44:19 PM] Generating 1 job function(s)
[5/11/18 4:44:19 PM] Debugger listening on ws://127.0.0.1:5858/a32b68e6-141d-47c7-a7d1-a32a6f6671bd
[5/11/18 4:44:19 PM] For help see https://nodejs.org/en/docs/inspector
[5/11/18 4:44:19 PM] Found the following functions:
[5/11/18 4:44:19 PM] Host.Functions.MyHttpTrigger
[5/11/18 4:44:19 PM]
[5/11/18 4:44:19 PM] Host initialized (1863ms)
[5/11/18 4:44:19 PM] Host started (1983ms)
[5/11/18 4:44:19 PM] Job host started
[5/11/18 4:44:20 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/lib/azure-functions-core-tools/workers/node/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'
[5/11/18 4:44:20 PM] internal/modules/cjs/loader.js:550
[5/11/18 4:44:20 PM]     throw err;
[5/11/18 4:44:20 PM]     ^
[5/11/18 4:44:20 PM] Error: Cannot find module './Worker.js'
[5/11/18 4:44:20 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
[5/11/18 4:44:20 PM]     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
[5/11/18 4:44:20 PM]     at Module.require (internal/modules/cjs/loader.js:598:17)
[5/11/18 4:44:20 PM]     at require (internal/modules/cjs/helpers.js:11:18)
[5/11/18 4:44:20 PM]     at Object.<anonymous> (/usr/lib/azure-functions-core-tools/workers/node/dist/src/nodejsWorker.js:8:14)
[5/11/18 4:44:20 PM]     at Module._compile (internal/modules/cjs/loader.js:654:30)
[5/11/18 4:44:20 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
[5/11/18 4:44:20 PM]     at Module.load (internal/modules/cjs/loader.js:566:32)
[5/11/18 4:44:20 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
[5/11/18 4:44:20 PM]     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Listening on http://localhost:7071/
Hit CTRL-C to exit...

Http Functions:

        MyHttpTrigger: http://localhost:7071/api/MyHttpTrigger

[5/11/18 4:44:20 PM] Worker encountered an error.
[5/11/18 4:44:20 PM] Worker process with pid 13820 exited with code 1.
[5/11/18 4:44:20 PM] Start Process: node  --inspect=5858 "/usr/lib/azure-functions-core-tools/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 44308 --workerId 590a9a1a-60df-4467-bc0d-3adffb378df7 --requestId 51b0ad99-f30b-45a6-84bd-ec2abac5dcbd
[5/11/18 4:44:20 PM] Debugger listening on ws://127.0.0.1:5858/c353a09b-d3fc-4c4c-8588-88d47b6eb394
[5/11/18 4:44:20 PM] For help see https://nodejs.org/en/docs/inspector
[5/11/18 4:44:20 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/lib/azure-functions-core-tools/workers/node/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'
[5/11/18 4:44:20 PM] internal/modules/cjs/loader.js:550
[5/11/18 4:44:20 PM]     throw err;
[5/11/18 4:44:20 PM]     ^
[5/11/18 4:44:20 PM] Error: Cannot find module './Worker.js'
[5/11/18 4:44:20 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
[5/11/18 4:44:20 PM]     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
[5/11/18 4:44:20 PM]     at Module.require (internal/modules/cjs/loader.js:598:17)
[5/11/18 4:44:20 PM]     at require (internal/modules/cjs/helpers.js:11:18)
[5/11/18 4:44:20 PM]     at Object.<anonymous> (/usr/lib/azure-functions-core-tools/workers/node/dist/src/nodejsWorker.js:8:14)
[5/11/18 4:44:20 PM]     at Module._compile (internal/modules/cjs/loader.js:654:30)
[5/11/18 4:44:20 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
[5/11/18 4:44:20 PM]     at Module.load (internal/modules/cjs/loader.js:566:32)
[5/11/18 4:44:20 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
[5/11/18 4:44:20 PM]     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
[5/11/18 4:44:20 PM] Worker encountered an error.
[5/11/18 4:44:20 PM] Worker process with pid 13829 exited with code 1.
[5/11/18 4:44:20 PM] Start Process: node  --inspect=5858 "/usr/lib/azure-functions-core-tools/workers/node/dist/src/nodejsWorker.js" --host 127.0.0.1 --port 44308 --workerId 2b39de60-ece3-4d0e-8ed2-56ea59576fdb --requestId c3a58f84-7dc5-4488-8c34-9649fb36cb4e
[5/11/18 4:44:20 PM] Debugger listening on ws://127.0.0.1:5858/0254d1d9-eed5-4732-8b78-9b787c372041
[5/11/18 4:44:20 PM] For help see https://nodejs.org/en/docs/inspector
[5/11/18 4:44:21 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/usr/lib/azure-functions-core-tools/workers/node/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'
[5/11/18 4:44:21 PM] internal/modules/cjs/loader.js:550
[5/11/18 4:44:21 PM]     throw err;
[5/11/18 4:44:21 PM]     ^
[5/11/18 4:44:21 PM] Error: Cannot find module './Worker.js'
[5/11/18 4:44:21 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
[5/11/18 4:44:21 PM]     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
[5/11/18 4:44:21 PM]     at Module.require (internal/modules/cjs/loader.js:598:17)
[5/11/18 4:44:21 PM]     at require (internal/modules/cjs/helpers.js:11:18)
[5/11/18 4:44:21 PM]     at Object.<anonymous> (/usr/lib/azure-functions-core-tools/workers/node/dist/src/nodejsWorker.js:8:14)
[5/11/18 4:44:21 PM]     at Module._compile (internal/modules/cjs/loader.js:654:30)
[5/11/18 4:44:21 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
[5/11/18 4:44:21 PM]     at Module.load (internal/modules/cjs/loader.js:566:32)
[5/11/18 4:44:21 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
[5/11/18 4:44:21 PM]     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
[5/11/18 4:44:21 PM] Worker encountered an error.
[5/11/18 4:44:21 PM] Worker process with pid 13836 exited with code 1.`
```

**Comment by ahmelsayed** [comment]
what node version do you have on your machine? only node 8 would work

**Comment by prog-re** [comment]
`node -v
v9.11.1
`
Is this a hard requrement of node 8 or is it "8 or above"?

**Comment by prog-re** [comment]
Downgraded to 8.11.1 and now it works. So I guess the answer is that 8 is a hard requirement
