### ISSUE TITLE
Durable Task extension causing Docker runtime to fail on startup

### ISSUE THREAD

**Issue by msimpsonnz** [Azure/azure-functions-core-tools#598]
I was trying to build an existing working project with Docker and ran into this issue.

Microsoft.NET.Sdk.Functions 1.0.14
Microsoft.Azure.WebJobs.Extensions.DurableTask 1.5.0

Using Function CLI 2.0.1-beta.33

Container just loops reporting this error

```
fail: Host.Startup[0]
      ScriptHost initialization failed
System.MissingMethodException: Method not found: 'FluentBinder<!0> Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.BindToInput(System.Func`2<!0,!!0>)'.
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.Microsoft.Azure.WebJobs.Host.Config.IExtensionConfigProvider.Initialize(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.InvokeExtensionConfigProviders(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config)
   at Microsoft.Azure.WebJobs.JobHost.PopulateStaticServices()
   at Microsoft.Azure.WebJobs.JobHost.get_Services()
   at Microsoft.Azure.WebJobs.Script.Utility.CreateMetadataProvider(JobHost host) in /home/ahmed/repos/azure-webjobs-sdk-script/src/WebJobs.Script/Utility.cs:line 375
   at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadCustomExtensions() in /home/ahmed/repos/azure-webjobs-sdk-script/src/WebJobs.Script/Host/ScriptHost.cs:line 736
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() in /home/ahmed/repos/azure-webjobs-sdk-script/src/WebJobs.Script/Host/ScriptHost.cs:line 526
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment, IScriptEventManager eventManager, ScriptHostConfiguration scriptConfig, ScriptSettingsManager settingsManager, ILoggerFactoryBuilder loggerFactoryBuilder, ProxyClientExecutor proxyClient) in /home/ahmed/repos/azure-webjobs-sdk-script/src/WebJobs.Script/Host/ScriptHost.cs:line 969
```

**Comment by ahmelsayed** [comment]
what base image are you using?

**Comment by msimpsonnz** [comment]
microsoft/dotnet:2.1-sdk AS installer-env

and microsoft/azure-functions-dotnet-core2.0:2.0 for deployment

**Comment by ahmelsayed** [comment]
hmmm, I'm unable to repro this. Can you make sure you do either 
```bash
docker pull microsoft/azure-functions-dotnet-core2.0:2.0
```

or 

```
docker build --no-cache .
```

when building your local image and try again? I think that error is probably indicating that the runtime version is older than your function dependencies, so I'm thinking you might be using a cached old version of the image on your machine

**Comment by msimpsonnz** [comment]
Tried to building local images again but still the same, why I am seeing what appears to be refs to your local directories? `/home/ahmed/repos/azure-webjobs-sdk-script/src/WebJobs.Script/Host/ScriptHost.cs:line 526`
