### ISSUE TITLE
Bug when invoke local Time Trigger functions by HTTP

### ISSUE THREAD

**Issue by ArtemTereshkovich** [Azure/azure-functions-core-tools#725]
## Problem

Hello. 
When i try invoke Timer Trigger Function by HTTP request the Function CLI . The function launched by Visual Studio  and after i make HTTP request to `http://localhost:{port}/admin/functions/{function_name}` by Postman or Browser and get 500 Error code. I follow guide from [Microsoft Guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#non-http-triggered-functions) .

## CLI version

Azure Functions Core Tools (2.0.1-beta.35)
Function Runtime Version: 2.0.11960.0

## Visual Studio version

Microsoft Visual Studio Community 2017
Version 15.8.4

## Stack Trace from CLI console
 ```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:7071/admin/functions/*FunctionName*
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Get", controller = "Functions"}. Executing action Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.Get (Microsoft.Azure.WebJobs.Script.WebHost)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.Get (Microsoft.Azure.WebJobs.Script.WebHost) with arguments (*FunctionName*) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.Get (Microsoft.Azure.WebJobs.Script.WebHost) in 521.3377ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLGQ9Q6EEV6M", Request id "0HLGQ9Q6EEV6M:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Azure.WebJobs.Script.WebHost.Extensions.FunctionMetadataExtensions.GetTestDataFilePath(String functionName, ScriptJobHostOptions config) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Extensions\FunctionMetadataExtensions.cs:line 98
   at Microsoft.Azure.WebJobs.Script.WebHost.Extensions.FunctionMetadataExtensions.GetTestDataFilePath(FunctionMetadata functionMetadata, ScriptJobHostOptions config) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Extensions\FunctionMetadataExtensions.cs:line 95
   at Microsoft.Azure.WebJobs.Script.WebHost.Extensions.FunctionMetadataExtensions.ToFunctionMetadataResponse(FunctionMetadata functionMetadata, HttpRequest request, ScriptJobHostOptions config, IWebJobsRouter router) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Extensions\FunctionMetadataExtensions.cs:line 35
   at Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.TryGetFunction(String name, HttpRequest request, IWebJobsRouter router) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Management\WebFunctionsManager.cs:line 143
   at Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.Get(String name) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Controllers\FunctionsController.cs:line 59
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HostWarmupMiddleware.Invoke(HttpContext httpContext) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\HostWarmupMiddleware.cs:line 34
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\FunctionInvocationMiddleware.cs:line 48
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HomepageMiddleware.Invoke(HttpContext context) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\HomepageMiddleware.cs:line 34
   at Microsoft.AspNetCore.Buffering.ResponseBufferingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.HttpExceptionMiddleware.Invoke(HttpContext context) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\HttpExceptionMiddleware.cs:line 23
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.EnvironmentReadyCheckMiddleware.Invoke(HttpContext httpContext, IScriptWebHostEnvironment webHostEnvironment) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\EnvironmentReadyCheckMiddleware.cs:line 29
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.AppServiceHeaderFixupMiddleware.Invoke(HttpContext httpContext) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\AppServiceHeaderFixupMiddleware.cs:line 35
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ScriptHostRequestServiceProviderMiddleware.Invoke(HttpContext httpContext, WebJobsScriptHostService manager) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\ScriptHostRequestServiceProviderMiddleware.cs:line 36
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1539.2081ms 500
```

**Comment by ArtemTereshkovich** [comment]
This problem fixed in new version (2.6.0)
