### ISSUE TITLE
func azure functionapp list-functions <functionappname>: 401 Unauthorized

### ISSUE THREAD

**Issue by l0010o0001l** [Azure/azure-functions-core-tools#948]
Hey there,

Thank you in advance for taking the time to read this issue.

I am working with a Python, Linux Function App on runtime ~2.

I authenticated with `az login`, and made sure that I am an Owner in the relevant Subscription. I was able to `func azure functionapp publish <functionappname>`, however, I was unable to successfully `func azure functionapp list-functions <functionappname>`. Here is the trace (past all the logging involving auth and JWT access tokens) when setting `CLI_DEBUG=1`:

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 219
   at Azure.Functions.Cli.Helpers.AzureHelper.PrintFunctionsInfo(Site functionApp, String accessToken, Boolean showKeys) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 274
   at Azure.Functions.Cli.Actions.AzureActions.ListFunctionsActions.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\ListFunctionsActions.cs:line 39
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
``` 

I'm on version `azure-functions-core-tools` `2.3.199`, my `azure-cli` version is `2.0.54`.

What are some things I may have overlooked? Thanks again for looking into this!

**Comment by l0010o0001l** [comment]
It seems like eventually (I'm not sure when) I was able to `list-functions`, but only after having tried `publish` several times. I do not know why. 😆
