### ISSUE TITLE
func azure functionapp publish <functionappname> : Settings must be of the form "name=value"

### ISSUE THREAD

**Issue by l0010o0001l** [Azure/azure-functions-core-tools#949]
Hello!

Thank you for looking into this issue.

I am trying to publish a single Python 3.6 Function to a Function App that has already been created.

I have a `AzureWebJobsStorage` environment variable set to a connection string with access token. Each time I attempt to publish, I am returned the following stack trace, whether or not `AzureWebJobsStorage` is set. It also seems as though the value in `local.settings.json` has no effect on the results of a publishing attempt:

```
Preparing archive...
System.FormatException: Settings must be of the form "name=value".
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.<>c.<Parse>b__97_0(String err)
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseStringIntoSettings(String connectionString, Action`1 error)
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.ParseImpl(String connectionString, CloudStorageAccount& accountInformation, Action`1 error)
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.UploadZipToStorage(Stream zip, IDictionary`2 appSettings)
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishRunFromZip(Site functionApp, Stream zipFile) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 345
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 288
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 159
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 52
```

I'm on version azure-functions-core-tools `2.3.199`, my azure-cli version is `2.0.54`.

Any advice or things I may be overlooking? Thank you again.

**Comment by l0010o0001l** [comment]
I ended up deleting the `AzureWebJobsStorage` setting via Portal and saving, and the publish command was able to complete without errors. Before that, I had attempted using the `--publish-local-settings` flag which didn't seem to resolve the above `Settings must be of the form "name=value"` exception.

I have a new issue. It appears the function was added to the Storage Account as a `.zip` file, however, it doesn't seem to be listed or associated with the Function App, either in Portal or via `func azure functionapp list-functions <functionappname>`. Any ideas? Thanks!
