### ISSUE TITLE
`func host start` does not properly load azure.functions

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#954]
_From @sptramer on December 28, 2018 23:35_

#### Investigative information

Env: Windows 10 CMD, Python 3.6 w/venv installed via installer, Azure Functions Core Tools installed via chocolatey package

Function created with:

`func init` (Python)
`func new` (HTTP Trigger)

Following instructions on: 

#### Repro steps

Provide the steps required to reproduce the problem:

1. `func host start`

#### Expected behavior

Application and python workers start as expected.

#### Actual behavior

Fails to start python worker:

```
(ENV) C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.3.199 Commit hash: fdf734b09806be822e7d946fe17928b419d8a289)
Function Runtime Version: 2.0.12246.0
[12/28/2018 11:24:29 PM] Starting Rpc Initialization Service.
[12/28/2018 11:24:29 PM] Initializaing RpcServer
[12/28/2018 11:24:29 PM] Building host: startup suppressed:False, configuration suppressed: False
[12/28/2018 11:24:30 PM] Reading host configuration file 'C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\host.json'
[12/28/2018 11:24:30 PM] Host configuration file read:
[12/28/2018 11:24:30 PM] {
[12/28/2018 11:24:30 PM]   "version": "2.0"
[12/28/2018 11:24:30 PM] }
[12/28/2018 11:24:30 PM] Initializing Host.
[12/28/2018 11:24:30 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[12/28/2018 11:24:30 PM] Starting JobHost
[12/28/2018 11:24:30 PM] Starting Host (HostId=sttramerspro4-639159208, InstanceId=dc3e9338-9106-488e-b539-8c5077f10100, Version=2.0.12246.0, ProcessId=18980, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[12/28/2018 11:24:30 PM] Loading functions metadata
[12/28/2018 11:24:30 PM] 1 functions loaded
[12/28/2018 11:24:30 PM] WorkerRuntime: python. Will shutdown other standby channels
[12/28/2018 11:24:30 PM] Starting language worker process:python  "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py" --host 127.0.0.1 --port 52822 --workerId d660bb33-ce01-4498-aede-e88eefe0d878 --requestId 19f23634-1710-43bb-9c26-d0b6468b802e --grpcMaxMessageLength 134217728
[12/28/2018 11:24:30 PM] python process with Id=19164 started
[12/28/2018 11:24:30 PM] Generating 1 job function(s)
[12/28/2018 11:24:30 PM] Found the following functions:
[12/28/2018 11:24:30 PM] Host.Functions.MergeExt
[12/28/2018 11:24:30 PM]
[12/28/2018 11:24:30 PM] Host initialized (209ms)
[12/28/2018 11:24:30 PM] Host started (222ms)
[12/28/2018 11:24:30 PM] Job host started
[12/28/2018 11:24:30 PM] Traceback (most recent call last):
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:30 PM]     main()
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:30 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:30 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:30 PM] Language Worker Process exited.
[12/28/2018 11:24:30 PM] python exited with code 1
 .
[12/28/2018 11:24:30 PM] Starting language worker process:python  "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py" --host 127.0.0.1 --port 52822 --workerId 9e890255-6327-42f3-abc1-d29a8733eb85 --requestId 590237f2-47d0-4336-8059-3159a465afca --grpcMaxMessageLength 134217728Hosting environment: Production
Content root path: C:\Users\sttramer\src\azure-docs-cli-python\ci-merger
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

[12/28/2018 11:24:30 PM] python process with Id=11484 started

Http Functions:

        MergeExt: [GET,POST] http://localhost:7071/api/MergeExt

[12/28/2018 11:24:30 PM] Traceback (most recent call last):
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:30 PM]     main()
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:30 PM] Language Worker Process exited.
[12/28/2018 11:24:30 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:30 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:30 PM] python exited with code 1
 .
[12/28/2018 11:24:30 PM] Starting language worker process:python  "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py" --host 127.0.0.1 --port 52822 --workerId 82171357-eed5-4f7b-a9a1-79166d4783fb --requestId d71361db-dae7-4bc9-84d1-29fb0c4bb41f --grpcMaxMessageLength 134217728
[12/28/2018 11:24:30 PM] python process with Id=13564 started
[12/28/2018 11:24:31 PM] Traceback (most recent call last):
[12/28/2018 11:24:31 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:31 PM]     main()
[12/28/2018 11:24:31 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:31 PM] Language Worker Process exited.
[12/28/2018 11:24:31 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:31 PM] python exited with code 1
 .
[12/28/2018 11:24:31 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:35 PM] Host lock lease acquired by instance ID '000000000000000000000000792E1ADF'.
Application is shutting down...
```

#### Related information 

When starting python3 in the venv, `azure.functions` can be loaded as a module:

```
(ENV) C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.functions
>>> exit
```

_Copied from original issue: Azure/azure-functions-python-worker#270_

**Comment by maiqbal11** [comment]
I was unable to repro this locally when using a Chocolatey core tools installation and an HttpTrigger function.  @sptramer, would you be able to share your `PYTHONPATH` from within the virtual environment by using `sys.path`?

**Comment by sptramer** [comment]
Looks like it's the ordinary system path:

```
>>> sys.path
['', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\python36.zip', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\DLLs', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages']
```

Which is definitely strange, since the venv is active. I double-checked the pip behavior here, and found that it was indeed referencing the global install, but all the packages were available:

```
(ENV) C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>pip install -r requirements.txt
Requirement already satisfied: azure-functions==1.0.0a5 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1)) (1.0.0a5)
Requirement already satisfied: azure-functions-worker==1.0.0a6 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 2)) (1.0.0a6)
Requirement already satisfied: grpcio==1.14.2 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 3)) (1.14.2)
Requirement already satisfied: grpcio-tools==1.14.2 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 4)) (1.14.2)
Requirement already satisfied: protobuf==3.6.1 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 5)) (3.6.1)
Requirement already satisfied: six==1.12.0 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 6)) (1.12.0)
Requirement already satisfied: setuptools in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from protobuf==3.6.1->-r requirements.txt (line 5)) (39.0.1)
```

Not quite sure what's happening here - venv bug or user error?

**Comment by maiqbal11** [comment]
How did you create and activate the virtual environment? Could you try this from Powershell instead of CMD?

**Comment by sptramer** [comment]
I created and activated from CMD, but also tried powershell, which resulted in some different errors. Here's the PowerShell output from a clean 3.6.7 install, creating a new venv:

```
$> get-command python |Select Source

Source
------
C:\Users\sttramer\AppData\Local\Programs\Python\Python36\python.exe

$>  python -m venv ENV
$> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted
$> .\ENV\Scripts\Activate.ps1
(ENV) $> get-command python |select source

Source
------
C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\ENV\Scripts\python.exe

$> pip install -r .\requirements.txt
Fatal error in launcher: Unable to create process using '"c:\users\sttramer\src\azure-docs-cli-python\ci-merger\env\scripts\python.exe"  "C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\ENV\Scripts\pip.exe" install -r .\requirements.txt'
```

This looks more like an error in the venv creation in 3.6 under PowerShell than anything else, unless elevated privileges are required (no idea why they would need to be.)

**Comment by maiqbal11** [comment]
Does it make a difference if you use the explicit instructions noted here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python#create-and-activate-a-virtual-environment?

**Comment by sptramer** [comment]
The `activate` script is not meant to be used on Powershell (see https://docs.python.org/3/library/venv.html) and running it requires changing execution policy since it's remote-signed. Otherwise this is how I created the venv.

What I didn't do was run the `func init` and `func new` commands in the PowerShell venv. They were created in a git repository, which I pulled from, then created a venv and ran `pip install -r requirements.txt` - which is where the problems happened.

Issue with the pip requirements then, maybe?

**Comment by sptramer** [comment]
I also decided to check `sys.path` here just to see if something different was happening where the functions module would be resolved differently, and it looks exactly like the other venv:

```python
>>> import sys
>>> sys.path
['', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\python36.zip', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\DLLs', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\Users\\sttramer\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages']
```

**Comment by sptramer** [comment]
Site-packages looks correct for the .venv which works (env created, then `func init`, then `func new`.)

```
PS C:\Users\sttramer\src\wtf> dir .\.env\Lib\site-packages\


    Directory: C:\Users\sttramer\src\wtf\.env\Lib\site-packages


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         1/4/2019  11:18 AM                azure
d-----         1/4/2019  11:18 AM                azure_functions-1.0.0a5.dist-info
d-----         1/4/2019  11:18 AM                azure_functions_worker-1.0.0a6.dist-info
d-----         1/4/2019  11:18 AM                google
d-----         1/4/2019  11:18 AM                grpc
d-----         1/4/2019  11:18 AM                grpcio-1.14.2.dist-info
d-----         1/4/2019  11:18 AM                grpcio_tools-1.14.2.dist-info
d-----         1/4/2019  11:18 AM                grpc_tools
d-----         1/4/2019  11:15 AM                pip
d-----         1/4/2019  11:15 AM                pip-10.0.1.dist-info
d-----         1/4/2019  11:15 AM                pkg_resources
d-----         1/4/2019  11:18 AM                protobuf-3.6.1.dist-info
d-----         1/4/2019  11:15 AM                setuptools
d-----         1/4/2019  11:15 AM                setuptools-39.0.1.dist-info
d-----         1/4/2019  11:18 AM                six-1.12.0.dist-info
d-----         1/4/2019  11:18 AM                wheel
d-----         1/4/2019  11:18 AM                wheel-0.32.3.dist-info
d-----         1/4/2019  11:18 AM                __pycache__
-a----         1/4/2019  11:15 AM            126 easy_install.py
-a----         1/4/2019  11:18 AM            540 protobuf-3.6.1-py3.6-nspkg.pth
-a----         1/4/2019  11:18 AM          32452 six.py
```

I decided to see if there was a difference with an env created inside of a git clone with an existing function (default created with `func init` and `func new`) after running `pip install -r requirements.txt`.

```
PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> py -3.6 -m venv .env
PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> .\.env\Scripts\Activate.ps1
(.env) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> pip install -r .\requirements.txt
Fatal error in launcher: Unable to create process using '"c:\users\sttramer\src\azure-docs-cli-python\ci-merger\.env\scripts\python.exe"  "C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\.env\Scripts\pip.exe" install -r .\requirements.txt'
(.env) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> .\.env\Scripts\python.exe -m pip install -r .\requirements.txt
C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\.env\Scripts\python.exe: No module named pip
```

What commands are run, exactly, with `func init` and `func new` that might be modifying the venv in such a way that it avoids this apparent configuration problem with Python 3.6 venv in PowerShell?

**Comment by maiqbal11** [comment]
`func init` is installing the requirements that are needed to run the Python program responsible for handling functions (e.g. `azure_functions_worker` and `azure_functions`). Aside from this, it is also installing the `wheel` package as well as calling `pip freeze` to generate the `requirements.txt` containing these requirements.

**Comment by sptramer** [comment]
If that's the case, then running `pip install -r requirements.txt` should properly provide all the dependencies so that functions will run after a repo is cloned. Somehow `azure.functions` is being missed:

```
[12/28/2018 11:24:30 PM] Traceback (most recent call last):
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:30 PM]     main()
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:30 PM] Language Worker Process exited.
[12/28/2018 11:24:30 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:30 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:30 PM] python exited with code 1
```

**Comment by maiqbal11** [comment]
Looping in @ankitkumarr to help with the investigation. Do you know why `pip install -r requirements.txt` would not provide the right configuration for an existing venv?

**Comment by ankitkumarr** [comment]
From your `site-packages` info, looks like `azure-functions` is being installed in the venv.

I think what might be happening is that your venv is launching your global python interpreter.
Can you try from your venv-
```
(.env)> python
>>> import sys
>>> sys.executable
```
The path should be of your venv's python interpreter. If it's not it means the venv python is not being used.

If so, try `where python` and which python path(s) show up.

Do have have some kind of alias for `python` that might be taking over, similar to [this](https://stackoverflow.com/questions/29528954/virtualenv-using-incorrect-sys-path) I found.

**Comment by sptramer** [comment]
I decided to check both the `python` and `py` command locations with the venv activated:

```
(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> get-command python |select Source

Source
------
C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\ENV\Scripts\python.exe

(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> get-command py |select Source

Source
------
C:\WINDOWS\py.exe
```

So one possibility for the import error is that the `py` command is called at any point during the `func` command execution on Windows platforms. This would also explain why the packages might be installed site-wide.

**Comment by ankitkumarr** [comment]
Sorry for the confusion!

Looking at your original issue, which was in `ENV`, with `sys.path` not showing the venv's location, were the azure packages installed in the virtual environment at all?

**Comment by sptramer** [comment]
I've been recreating the venv whenever necessary to get a clean environment set up, and alternately using `.env` and `ENV`. Both are showing the same issues under Windows PowerShell. I should probably be a bit clearer about where I'm seeing which issues, and under what circumstances.

## Creating a new project (running `func init/func new`)

```powershell
PS C:\Users\sttramer\src\wtf> py -3.6 -m venv ENV
PS C:\Users\sttramer\src\wtf> .\ENV\Scripts\Activate.ps1
PS C:\Users\sttramer\src\wtf> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
PS C:\Users\sttramer\src\wtf> .\ENV\Scripts\Activate.ps1
(ENV) PS C:\Users\sttramer\src\wtf> func init
Select a worker runtime: python
Installing wheel package
Installing azure-functions==1.0.0a5 package
Installing azure-functions-worker==1.0.0a6 package
Running pip freeze
Writing .funcignore
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing C:\Users\sttramer\src\wtf\.vscode\extensions.json
(ENV) PS C:\Users\sttramer\src\wtf> func new HttpTrigger
Select a template: HTTP trigger
Function name: [HttpTrigger]
Writing C:\Users\sttramer\src\wtf\HttpTrigger\sample.dat
Writing C:\Users\sttramer\src\wtf\HttpTrigger\__init__.py
Writing C:\Users\sttramer\src\wtf\HttpTrigger\function.json
The function "HttpTrigger" was created successfully from the "HTTP trigger" template.
(ENV) PS C:\Users\sttramer\src\wtf> func host start
```

The host starts as expected. So there's no issue when the application is created in PowerShell from a clean venv. I checked where the pip requirements were installed:

```
    Directory: C:\Users\sttramer\src\wtf\ENV\Lib\site-packages


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/10/2019   9:39 AM                azure
d-----        1/10/2019   9:39 AM                azure_functions-1.0.0a5.dist-info
d-----        1/10/2019   9:39 AM                azure_functions_worker-1.0.0a6.dist-info
d-----        1/10/2019   9:39 AM                google
d-----        1/10/2019   9:39 AM                grpc
d-----        1/10/2019   9:39 AM                grpcio-1.14.2.dist-info
d-----        1/10/2019   9:39 AM                grpcio_tools-1.14.2.dist-info
d-----        1/10/2019   9:39 AM                grpc_tools
d-----        1/10/2019   9:38 AM                pip
d-----        1/10/2019   9:38 AM                pip-10.0.1.dist-info
d-----        1/10/2019   9:38 AM                pkg_resources
d-----        1/10/2019   9:39 AM                protobuf-3.6.1.dist-info
d-----        1/10/2019   9:38 AM                setuptools
d-----        1/10/2019   9:38 AM                setuptools-39.0.1.dist-info
d-----        1/10/2019   9:39 AM                six-1.12.0.dist-info
d-----        1/10/2019   9:39 AM                wheel
d-----        1/10/2019   9:39 AM                wheel-0.32.3.dist-info
d-----        1/10/2019   9:39 AM                __pycache__
-a----        1/10/2019   9:38 AM            126 easy_install.py
-a----        1/10/2019   9:39 AM            540 protobuf-3.6.1-py3.6-nspkg.pth
-a----        1/10/2019   9:39 AM          32452 six.py
```

Looks correct to me.

## Trying to start a function with infrastructure cloned from a git repo (powershell)

Again, with a clean local venv. The `func init/func new` commands were run on a different host.

```powershell
PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> py -3.6 -m venv ENV
PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> .\ENV\Scripts\Activate.ps1
(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> get-command python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.6.715... C:\Users\sttramer\src\azure-docs-cli-p...


(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> dir


    Directory: C:\Users\sttramer\src\azure-docs-cli-python\ci-merger


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         1/4/2019   2:07 PM                .vscode
d-----        1/10/2019   9:44 AM                ENV
d-----         1/4/2019   2:07 PM                MergeExt
-a----         1/4/2019   2:07 PM              1 .funcignore
-a----         1/4/2019   2:07 PM            390 .gitignore
-a----         1/4/2019   2:07 PM             25 host.json
-a----         1/4/2019   2:07 PM            122 requirements.txt


(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> pip install -r .\requirements.txt
Fatal error in launcher: Unable to create process using '"c:\users\sttramer\src\azure-docs-cli-python\ci-merger\env\scripts\python.exe"  "C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\ENV\Scripts\pip.exe" install -r .\requirements.txt'
```

So there's something happening with `func init` which is running `pip` successfully in the venv, and running `pip` manually doesn't work. `pip` also isn't available as a module in the venv, somehow:

```powershell
(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> python -m pip install -r .\requirements.txt
C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\ENV\Scripts\python.exe: No module named pip
```

This is most likely a Python bug, see https://github.com/pypa/pip/issues/5223 (which is somehow closed.) It could be related to the Python launcher, so I uninstalled that (and all existing versions of Python on my system) then reinstalled to give it another try:

```powershell
PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> python -m venv ENV
PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> .\ENV\Scripts\Activate.ps1
(ENV) PS C:\Users\sttramer\src\azure-docs-cli-python\ci-merger> pip install -r .\requirements.txt
Fatal error in launcher: Unable to create process using '"c:\users\sttramer\src\azure-docs-cli-python\ci-merger\env\scripts\python.exe"  "C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\ENV\Scripts\pip.exe" install -r .\requirements.txt'
```

So this is definitely some kind of issue with venv on Windows. I'll look into it and file a bug with Python, but any insight into the commands run as part of `func init` would be useful before I do that, because then I can isolate the differences between a manual `pip` run in the venv and whatever the core function tools are doing.

## Trying to start a function with infrastructure cloned from a git repo (CMD)

CMD has its own issues, which may be related to the PowerShell problems.

```cmd
C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>python -m venv ENV

C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>.\ENV\Scripts\activate.bat

(ENV) C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>pip install -r requirements.txt
Requirement already satisfied: azure-functions==1.0.0a5 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1)) (1.0.0a5)
Requirement already satisfied: azure-functions-worker==1.0.0a6 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 2)) (1.0.0a6)
Requirement already satisfied: grpcio==1.14.2 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 3)) (1.14.2)
Requirement already satisfied: grpcio-tools==1.14.2 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 4)) (1.14.2)
Requirement already satisfied: protobuf==3.6.1 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 5)) (3.6.1)
Requirement already satisfied: six==1.12.0 in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 6)) (1.12.0)
Requirement already satisfied: setuptools in c:\users\sttramer\appdata\local\programs\python\python36\lib\site-packages (from protobuf==3.6.1->-r requirements.txt (line 5)) (39.0.1)
```

So the venv under CMD is completely ignored, it seems. But when running `func host start`:

```
[1/10/2019 6:10:59 PM] python process with Id=16660 started
[1/10/2019 6:10:59 PM] Traceback (most recent call last):
[1/10/2019 6:10:59 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[1/10/2019 6:10:59 PM]     main()
[1/10/2019 6:10:59 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[1/10/2019 6:10:59 PM]     import azure.functions  # NoQA
[1/10/2019 6:10:59 PM] ModuleNotFoundError: No module named 'azure'
[1/10/2019 6:10:59 PM] Language Worker Process exited.
[1/10/2019 6:10:59 PM] python exited with code 1
```

## Summary

It looks like the PowerShell issue is a straight-up bug in Python's venv module, but I can't give a lot of information in a bug report without understanding why `func init` works correctly to run pip and generate the freeze.

CMD is more interesting because it says the requirements are satisfied, but then fails to load the `azure` module. Again, this could be a bug with Python venv, since the local environment seems to be circumvented. But I'd like to know more about core tools behavior with Python before filing a bug.

**Comment by sptramer** [comment]
@ankitkumarr Sorry to come back a little late, but is there a repo for the core tools so that I can get a look at the code itself to see what syscalls are invoked?

**Comment by ankitkumarr** [comment]
This (`azure-functions-core-tools`) is the core-tools repo. [Here's ](https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Helpers/PythonHelpers.cs#L22-L27)the code for the init for Python.

**Comment by sptramer** [comment]
Whoops, my extreme bad on the repo... I lost track of where I filed this after a while. I'll spend some time investigating how you're detecting the venv and invoking its commands, then file an appropriate bug with the Python team. I'll link it here once it's complete.

Thanks!

**Comment by ahmedelnably** [comment]
Closing as stale
